<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TblCompanyExpenseTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_company_expense')->delete();
        
        \DB::table('tbl_company_expense')->insert(array (
            0 => 
            array (
                'company_expense_id' => 1345,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/JY2/23010004',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '150.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-10 08:50:28',
                'company_expense_updated' => '2023-01-10 08:50:28',
                'company_expense_day' => 1,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6119,
                'worker_role_id' => 0,
            ),
            1 => 
            array (
                'company_expense_id' => 1346,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/JY2/23010003',
                'company_land_id' => 0,
                'user_id' => 2,
                'worker_id' => 2,
                'company_expense_total' => '143.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-10 08:49:43',
                'company_expense_updated' => '2023-01-10 08:51:03',
                'company_expense_day' => 9,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6119,
                'worker_role_id' => 0,
            ),
            2 => 
            array (
                'company_expense_id' => 1347,
                'setting_expense_category_id' => 8,
                'company_expense_number' => 'EP/ER/JY2/23010011',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '25.80',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-10 09:05:46',
                'company_expense_updated' => '2023-01-10 09:05:46',
                'company_expense_day' => 9,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6122,
                'worker_role_id' => 0,
            ),
            3 => 
            array (
                'company_expense_id' => 1348,
                'setting_expense_category_id' => 8,
                'company_expense_number' => 'EP/ER/JY2/23010010',
                'company_land_id' => 0,
                'user_id' => 2,
                'worker_id' => 2,
                'company_expense_total' => '116.68',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-10 09:05:12',
                'company_expense_updated' => '2023-01-10 09:07:09',
                'company_expense_day' => 1,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6122,
                'worker_role_id' => 0,
            ),
            4 => 
            array (
                'company_expense_id' => 1349,
                'setting_expense_category_id' => 8,
                'company_expense_number' => 'EP/ER/JY2/23010009',
                'company_land_id' => 0,
                'user_id' => 2,
                'worker_id' => 2,
                'company_expense_total' => '786.20',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-10 09:04:06',
                'company_expense_updated' => '2023-01-10 09:06:46',
                'company_expense_day' => 1,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6122,
                'worker_role_id' => 0,
            ),
            5 => 
            array (
                'company_expense_id' => 1350,
                'setting_expense_category_id' => 8,
                'company_expense_number' => 'EP/ER/JY2/23010008',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '51.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-10 09:03:04',
                'company_expense_updated' => '2023-01-10 09:03:04',
                'company_expense_day' => 6,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6122,
                'worker_role_id' => 0,
            ),
            6 => 
            array (
                'company_expense_id' => 1351,
                'setting_expense_category_id' => 6,
                'company_expense_number' => 'EP/ER/JY2/23010007',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '280.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-10 09:01:26',
                'company_expense_updated' => '2023-01-10 09:01:26',
                'company_expense_day' => 9,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6122,
                'worker_role_id' => 0,
            ),
            7 => 
            array (
                'company_expense_id' => 1352,
                'setting_expense_category_id' => 9,
                'company_expense_number' => 'EP/ER/JY2/23010006',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '130.10',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-10 09:00:19',
                'company_expense_updated' => '2023-01-10 09:00:19',
                'company_expense_day' => 6,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6122,
                'worker_role_id' => 0,
            ),
            8 => 
            array (
                'company_expense_id' => 1353,
                'setting_expense_category_id' => 9,
                'company_expense_number' => 'EP/ER/JY2/23010005',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '11.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-10 08:59:39',
                'company_expense_updated' => '2023-01-10 08:59:39',
                'company_expense_day' => 9,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6122,
                'worker_role_id' => 0,
            ),
            9 => 
            array (
                'company_expense_id' => 1354,
                'setting_expense_category_id' => 8,
                'company_expense_number' => 'EP/ER/JY2/23010012',
                'company_land_id' => 0,
                'user_id' => 2,
                'worker_id' => 2,
                'company_expense_total' => '1928.90',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-10 09:08:29',
                'company_expense_updated' => '2023-01-10 09:09:15',
                'company_expense_day' => 1,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6123,
                'worker_role_id' => 0,
            ),
            10 => 
            array (
                'company_expense_id' => 1364,
                'setting_expense_category_id' => 8,
                'company_expense_number' => 'EP/ER/JY2/23010012',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '102.05',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 08:56:35',
                'company_expense_updated' => '2023-01-15 08:56:35',
                'company_expense_day' => 11,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6463,
                'worker_role_id' => 0,
            ),
            11 => 
            array (
                'company_expense_id' => 1365,
                'setting_expense_category_id' => 5,
                'company_expense_number' => 'EP/ER/JY2/23010014',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '180.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 10:43:38',
                'company_expense_updated' => '2023-01-15 10:43:38',
                'company_expense_day' => 11,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6475,
                'worker_role_id' => 0,
            ),
            12 => 
            array (
                'company_expense_id' => 1366,
                'setting_expense_category_id' => 23,
                'company_expense_number' => 'EP/ER/JY2/23010013',
                'company_land_id' => 0,
                'user_id' => 2,
                'worker_id' => 2,
                'company_expense_total' => '58.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 10:38:29',
                'company_expense_updated' => '2023-01-15 10:53:55',
                'company_expense_day' => 13,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6475,
                'worker_role_id' => 0,
            ),
            13 => 
            array (
                'company_expense_id' => 1367,
                'setting_expense_category_id' => 24,
                'company_expense_number' => 'EP/ER/JY2/23010015',
                'company_land_id' => 0,
                'user_id' => 2,
                'worker_id' => 2,
                'company_expense_total' => '13.80',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 10:57:17',
                'company_expense_updated' => '2023-01-15 11:06:38',
                'company_expense_day' => 11,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6480,
                'worker_role_id' => 0,
            ),
            14 => 
            array (
                'company_expense_id' => 1368,
                'setting_expense_category_id' => 6,
                'company_expense_number' => 'EP/ER/JY2/23010017',
                'company_land_id' => 0,
                'user_id' => 2,
                'worker_id' => 2,
                'company_expense_total' => '200.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 11:23:35',
                'company_expense_updated' => '2023-01-15 11:33:02',
                'company_expense_day' => 11,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6487,
                'worker_role_id' => 0,
            ),
            15 => 
            array (
                'company_expense_id' => 1369,
                'setting_expense_category_id' => 5,
                'company_expense_number' => 'EP/ER/JY2/23010016',
                'company_land_id' => 0,
                'user_id' => 2,
                'worker_id' => 2,
                'company_expense_total' => '150.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 11:22:12',
                'company_expense_updated' => '2023-01-15 11:33:14',
                'company_expense_day' => 15,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6487,
                'worker_role_id' => 0,
            ),
            16 => 
            array (
                'company_expense_id' => 1370,
                'setting_expense_category_id' => 5,
                'company_expense_number' => 'EP/ER/JY2/23010019',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '490.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 11:35:51',
                'company_expense_updated' => '2023-01-15 11:35:51',
                'company_expense_day' => 11,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6488,
                'worker_role_id' => 0,
            ),
            17 => 
            array (
                'company_expense_id' => 1372,
                'setting_expense_category_id' => 24,
                'company_expense_number' => 'EP/ER/JY2/23010020',
                'company_land_id' => 0,
                'user_id' => 2,
                'worker_id' => 2,
                'company_expense_total' => '2600.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 11:38:31',
                'company_expense_updated' => '2023-01-15 11:39:47',
                'company_expense_day' => 12,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6489,
                'worker_role_id' => 0,
            ),
            18 => 
            array (
                'company_expense_id' => 1373,
                'setting_expense_category_id' => 23,
                'company_expense_number' => 'EP/ER/ZC/23010008',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '238.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 13:58:10',
                'company_expense_updated' => '2023-01-15 13:58:10',
                'company_expense_day' => 4,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6506,
                'worker_role_id' => 0,
            ),
            19 => 
            array (
                'company_expense_id' => 1374,
                'setting_expense_category_id' => 23,
                'company_expense_number' => 'EP/ER/ZC/23010007',
                'company_land_id' => 0,
                'user_id' => 2,
                'worker_id' => 2,
                'company_expense_total' => '552.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 13:57:12',
                'company_expense_updated' => '2023-01-15 14:02:04',
                'company_expense_day' => 11,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6506,
                'worker_role_id' => 0,
            ),
            20 => 
            array (
                'company_expense_id' => 1375,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/ZC/23010006',
                'company_land_id' => 0,
                'user_id' => 2,
                'worker_id' => 2,
                'company_expense_total' => '180.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 13:54:38',
                'company_expense_updated' => '2023-01-15 14:30:35',
                'company_expense_day' => 5,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6506,
                'worker_role_id' => 0,
            ),
            21 => 
            array (
                'company_expense_id' => 1376,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/ZC/23010005',
                'company_land_id' => 0,
                'user_id' => 2,
                'worker_id' => 2,
                'company_expense_total' => '800.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 13:54:06',
                'company_expense_updated' => '2023-01-15 14:30:21',
                'company_expense_day' => 10,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6506,
                'worker_role_id' => 0,
            ),
            22 => 
            array (
                'company_expense_id' => 1377,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/ZC/23010004',
                'company_land_id' => 0,
                'user_id' => 2,
                'worker_id' => 2,
                'company_expense_total' => '129.02',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 13:52:55',
                'company_expense_updated' => '2023-01-15 14:30:06',
                'company_expense_day' => 10,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6506,
                'worker_role_id' => 0,
            ),
            23 => 
            array (
                'company_expense_id' => 1378,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/ZC/23010003',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '113.31',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 13:52:14',
                'company_expense_updated' => '2023-01-15 13:52:14',
                'company_expense_day' => 3,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6506,
                'worker_role_id' => 0,
            ),
            24 => 
            array (
                'company_expense_id' => 1379,
                'setting_expense_category_id' => 6,
                'company_expense_number' => 'EP/ER/ZC/23010002',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '47.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 13:51:02',
                'company_expense_updated' => '2023-01-15 13:51:02',
                'company_expense_day' => 11,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6506,
                'worker_role_id' => 0,
            ),
            25 => 
            array (
                'company_expense_id' => 1380,
                'setting_expense_category_id' => 23,
                'company_expense_number' => 'EP/ER/ZC/23010009',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '259.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-15 14:02:48',
                'company_expense_updated' => '2023-01-15 14:02:48',
                'company_expense_day' => 4,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 6507,
                'worker_role_id' => 0,
            ),
            26 => 
            array (
                'company_expense_id' => 1411,
                'setting_expense_category_id' => 5,
                'company_expense_number' => 'EP/ER/ZC/23010018',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '200.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 20:51:01',
                'company_expense_updated' => '2023-01-29 20:51:01',
                'company_expense_day' => 26,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7054,
                'worker_role_id' => 0,
            ),
            27 => 
            array (
                'company_expense_id' => 1412,
                'setting_expense_category_id' => 5,
                'company_expense_number' => 'EP/ER/ZC/23010017',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '12996.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 20:49:53',
                'company_expense_updated' => '2023-01-29 20:49:53',
                'company_expense_day' => 26,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7054,
                'worker_role_id' => 0,
            ),
            28 => 
            array (
                'company_expense_id' => 1413,
                'setting_expense_category_id' => 8,
                'company_expense_number' => 'EP/ER/ZC/23010016',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '249.75',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 20:49:02',
                'company_expense_updated' => '2023-01-29 20:49:02',
                'company_expense_day' => 24,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7054,
                'worker_role_id' => 0,
            ),
            29 => 
            array (
                'company_expense_id' => 1414,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/ZC/23010015',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '55.15',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 20:48:05',
                'company_expense_updated' => '2023-01-29 20:48:05',
                'company_expense_day' => 26,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7054,
                'worker_role_id' => 0,
            ),
            30 => 
            array (
                'company_expense_id' => 1415,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/ZC/23010014',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '124.05',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 20:47:21',
                'company_expense_updated' => '2023-01-29 20:47:21',
                'company_expense_day' => 24,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7054,
                'worker_role_id' => 0,
            ),
            31 => 
            array (
                'company_expense_id' => 1416,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/ZC/23010013',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '115.12',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 20:46:39',
                'company_expense_updated' => '2023-01-29 20:46:39',
                'company_expense_day' => 7,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7054,
                'worker_role_id' => 0,
            ),
            32 => 
            array (
                'company_expense_id' => 1417,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/ZC/23010012',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '400.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 20:45:19',
                'company_expense_updated' => '2023-01-29 20:45:19',
                'company_expense_day' => 24,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7054,
                'worker_role_id' => 0,
            ),
            33 => 
            array (
                'company_expense_id' => 1418,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/ZC/23010011',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '320.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 20:44:42',
                'company_expense_updated' => '2023-01-29 20:44:42',
                'company_expense_day' => 24,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7054,
                'worker_role_id' => 0,
            ),
            34 => 
            array (
                'company_expense_id' => 1419,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/ZC/23010010',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '116.25',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 20:43:38',
                'company_expense_updated' => '2023-01-29 20:43:38',
                'company_expense_day' => 19,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7054,
                'worker_role_id' => 0,
            ),
            35 => 
            array (
                'company_expense_id' => 1420,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/JY2/23010024',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '107.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 21:15:43',
                'company_expense_updated' => '2023-01-29 21:15:43',
                'company_expense_day' => 15,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7057,
                'worker_role_id' => 0,
            ),
            36 => 
            array (
                'company_expense_id' => 1421,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/JY2/23010023',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '50.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 21:15:04',
                'company_expense_updated' => '2023-01-29 21:15:04',
                'company_expense_day' => 23,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7057,
                'worker_role_id' => 0,
            ),
            37 => 
            array (
                'company_expense_id' => 1422,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/JY2/23010022',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '200.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 21:12:58',
                'company_expense_updated' => '2023-01-29 21:12:58',
                'company_expense_day' => 23,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7057,
                'worker_role_id' => 0,
            ),
            38 => 
            array (
                'company_expense_id' => 1423,
                'setting_expense_category_id' => 5,
                'company_expense_number' => 'EP/ER/JY2/23010021',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '7.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 21:12:24',
                'company_expense_updated' => '2023-01-29 21:12:24',
                'company_expense_day' => 19,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7057,
                'worker_role_id' => 0,
            ),
            39 => 
            array (
                'company_expense_id' => 1424,
                'setting_expense_category_id' => 6,
                'company_expense_number' => 'EP/ER/JY2/23010020',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '14.50',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 21:10:28',
                'company_expense_updated' => '2023-01-29 21:10:28',
                'company_expense_day' => 16,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7057,
                'worker_role_id' => 0,
            ),
            40 => 
            array (
                'company_expense_id' => 1425,
                'setting_expense_category_id' => 23,
                'company_expense_number' => 'EP/ER/JY2/23010026',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '304.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 21:22:24',
                'company_expense_updated' => '2023-01-29 21:22:24',
                'company_expense_day' => 19,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7058,
                'worker_role_id' => 0,
            ),
            41 => 
            array (
                'company_expense_id' => 1426,
                'setting_expense_category_id' => 5,
                'company_expense_number' => 'EP/ER/JY2/23010025',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '197.80',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 21:21:48',
                'company_expense_updated' => '2023-01-29 21:21:48',
                'company_expense_day' => 19,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7058,
                'worker_role_id' => 0,
            ),
            42 => 
            array (
                'company_expense_id' => 1427,
                'setting_expense_category_id' => 8,
                'company_expense_number' => 'EP/ER/JY2/23010027',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '324.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 21:36:48',
                'company_expense_updated' => '2023-01-29 21:36:48',
                'company_expense_day' => 16,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7059,
                'worker_role_id' => 0,
            ),
            43 => 
            array (
                'company_expense_id' => 1428,
                'setting_expense_category_id' => 8,
                'company_expense_number' => 'EP/ER/JY2/23010030',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '462.80',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 21:46:49',
                'company_expense_updated' => '2023-01-29 21:46:49',
                'company_expense_day' => 9,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7061,
                'worker_role_id' => 0,
            ),
            44 => 
            array (
                'company_expense_id' => 1429,
                'setting_expense_category_id' => 8,
                'company_expense_number' => 'EP/ER/JY2/23010029',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '1214.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 21:46:07',
                'company_expense_updated' => '2023-01-29 21:46:07',
                'company_expense_day' => 9,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7061,
                'worker_role_id' => 0,
            ),
            45 => 
            array (
                'company_expense_id' => 1430,
                'setting_expense_category_id' => 8,
                'company_expense_number' => 'EP/ER/JY2/23010028',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '683.50',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-29 21:40:24',
                'company_expense_updated' => '2023-01-29 21:40:24',
                'company_expense_day' => 16,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7061,
                'worker_role_id' => 0,
            ),
            46 => 
            array (
                'company_expense_id' => 1479,
                'setting_expense_category_id' => 5,
                'company_expense_number' => 'EP/ER/ZC/23010019',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '1021.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-31 21:48:55',
                'company_expense_updated' => '2023-01-31 21:48:55',
                'company_expense_day' => 31,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7108,
                'worker_role_id' => 0,
            ),
            47 => 
            array (
                'company_expense_id' => 1480,
                'setting_expense_category_id' => 5,
                'company_expense_number' => 'EP/ER/ZC/23010020',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '2640.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-31 21:54:23',
                'company_expense_updated' => '2023-01-31 21:54:23',
                'company_expense_day' => 31,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7109,
                'worker_role_id' => 0,
            ),
            48 => 
            array (
                'company_expense_id' => 1481,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/ZC/23010022',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '49.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-31 22:01:01',
                'company_expense_updated' => '2023-01-31 22:01:01',
                'company_expense_day' => 30,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7110,
                'worker_role_id' => 0,
            ),
            49 => 
            array (
                'company_expense_id' => 1482,
                'setting_expense_category_id' => 5,
                'company_expense_number' => 'EP/ER/ZC/23010021',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '18.50',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-31 21:59:31',
                'company_expense_updated' => '2023-01-31 21:59:31',
                'company_expense_day' => 31,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7110,
                'worker_role_id' => 0,
            ),
            50 => 
            array (
                'company_expense_id' => 1483,
                'setting_expense_category_id' => 8,
                'company_expense_number' => 'EP/ER/ZC/23010023',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '11.30',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-31 22:03:30',
                'company_expense_updated' => '2023-01-31 22:03:30',
                'company_expense_day' => 28,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7112,
                'worker_role_id' => 0,
            ),
            51 => 
            array (
                'company_expense_id' => 1484,
                'setting_expense_category_id' => 5,
                'company_expense_number' => 'EP/ER/ZC/23010024',
                'company_land_id' => NULL,
                'user_id' => 4,
                'worker_id' => 2,
                'company_expense_total' => '14.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-01-31 22:07:14',
                'company_expense_updated' => '2023-01-31 22:07:14',
                'company_expense_day' => 28,
                'company_expense_month' => 1,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 7114,
                'worker_role_id' => 0,
            ),
            52 => 
            array (
                'company_expense_id' => 3374,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/JY2/23050010',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '100.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-05-08 09:56:51',
                'company_expense_updated' => '2023-05-08 09:56:51',
                'company_expense_day' => 21,
                'company_expense_month' => 4,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 8031,
                'worker_role_id' => 0,
            ),
            53 => 
            array (
                'company_expense_id' => 3375,
                'setting_expense_category_id' => 8,
                'company_expense_number' => 'EP/ER/JY2/23050009',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '73.80',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-05-08 09:56:16',
                'company_expense_updated' => '2023-05-08 09:56:16',
                'company_expense_day' => 12,
                'company_expense_month' => 4,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 8031,
                'worker_role_id' => 0,
            ),
            54 => 
            array (
                'company_expense_id' => 3376,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/JY2/23050008',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '50.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-05-08 09:55:39',
                'company_expense_updated' => '2023-05-08 09:55:39',
                'company_expense_day' => 12,
                'company_expense_month' => 4,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 8031,
                'worker_role_id' => 0,
            ),
            55 => 
            array (
                'company_expense_id' => 3377,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/JY2/23050007',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '50.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-05-08 09:55:08',
                'company_expense_updated' => '2023-05-08 09:55:08',
                'company_expense_day' => 11,
                'company_expense_month' => 4,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 8031,
                'worker_role_id' => 0,
            ),
            56 => 
            array (
                'company_expense_id' => 3378,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/JY2/23050006',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '62.02',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-05-08 09:54:33',
                'company_expense_updated' => '2023-05-08 09:54:33',
                'company_expense_day' => 11,
                'company_expense_month' => 4,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 8031,
                'worker_role_id' => 0,
            ),
            57 => 
            array (
                'company_expense_id' => 3379,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/JY2/23050005',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '6.10',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-05-08 09:53:53',
                'company_expense_updated' => '2023-05-08 09:53:53',
                'company_expense_day' => 4,
                'company_expense_month' => 4,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 8031,
                'worker_role_id' => 0,
            ),
            58 => 
            array (
                'company_expense_id' => 3380,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/JY2/23050004',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '18.75',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-05-08 09:52:54',
                'company_expense_updated' => '2023-05-08 09:52:54',
                'company_expense_day' => 4,
                'company_expense_month' => 4,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 8031,
                'worker_role_id' => 0,
            ),
            59 => 
            array (
                'company_expense_id' => 3381,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/JY2/23050003',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '31.27',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-05-08 09:52:12',
                'company_expense_updated' => '2023-05-08 09:52:12',
                'company_expense_day' => 4,
                'company_expense_month' => 4,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 8031,
                'worker_role_id' => 0,
            ),
            60 => 
            array (
                'company_expense_id' => 3382,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/JY2/23050002',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '38.11',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-05-08 09:51:29',
                'company_expense_updated' => '2023-05-08 09:51:29',
                'company_expense_day' => 2,
                'company_expense_month' => 4,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 8031,
                'worker_role_id' => 0,
            ),
            61 => 
            array (
                'company_expense_id' => 3383,
                'setting_expense_category_id' => 4,
                'company_expense_number' => 'EP/ER/JY2/23050001',
                'company_land_id' => NULL,
                'user_id' => 3,
                'worker_id' => 2,
                'company_expense_total' => '150.00',
                'company_id' => 2,
                'company_expense_type' => 'daily',
                'company_expense_created' => '2023-05-08 09:50:41',
                'company_expense_updated' => '2023-05-08 09:50:41',
                'company_expense_day' => 2,
                'company_expense_month' => 4,
                'company_expense_year' => 2023,
                'company_expense_status' => 'completed',
                'sync_id' => 8031,
                'worker_role_id' => 0,
            ),
        ));
        
        
    }
}