<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TblCompanyExpenseItemTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_company_expense_item')->delete();
        
        \DB::table('tbl_company_expense_item')->insert(array (
            0 => 
            array (
                'company_expense_item_id' => 2125,
                'company_expense_id' => 1345,
                'setting_expense_id' => 14,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '150.00',
                'company_expense_item_total' => '150.00',
                'company_expense_item_created' => '2023-01-10 08:50:26',
                'company_expense_item_updated' => '2023-01-10 08:50:26',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '150.00',
                'company_expense_item_average_price_per_tree' => '0.07',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            1 => 
            array (
                'company_expense_item_id' => 2126,
                'company_expense_id' => 1346,
                'setting_expense_id' => 14,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '143.00',
                'company_expense_item_total' => '143.00',
                'company_expense_item_created' => '2023-01-10 08:51:03',
                'company_expense_item_updated' => '2023-01-10 08:51:03',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '143.00',
                'company_expense_item_average_price_per_tree' => '0.06',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            2 => 
            array (
                'company_expense_item_id' => 2127,
                'company_expense_id' => 1347,
                'setting_expense_id' => 22,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '25.80',
                'company_expense_item_total' => '25.80',
                'company_expense_item_created' => '2023-01-10 09:05:44',
                'company_expense_item_updated' => '2023-01-10 09:05:44',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '25.80',
                'company_expense_item_average_price_per_tree' => '0.01',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            3 => 
            array (
                'company_expense_item_id' => 2128,
                'company_expense_id' => 1348,
                'setting_expense_id' => 22,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '116.68',
                'company_expense_item_total' => '116.68',
                'company_expense_item_created' => '2023-01-10 09:07:09',
                'company_expense_item_updated' => '2023-01-10 09:07:09',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '116.68',
                'company_expense_item_average_price_per_tree' => '0.04',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            4 => 
            array (
                'company_expense_item_id' => 2129,
                'company_expense_id' => 1349,
                'setting_expense_id' => 20,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '786.20',
                'company_expense_item_total' => '786.20',
                'company_expense_item_created' => '2023-01-10 09:06:46',
                'company_expense_item_updated' => '2023-01-10 09:06:46',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '786.20',
                'company_expense_item_average_price_per_tree' => '0.25',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            5 => 
            array (
                'company_expense_item_id' => 2130,
                'company_expense_id' => 1350,
                'setting_expense_id' => 21,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '51.00',
                'company_expense_item_total' => '51.00',
                'company_expense_item_created' => '2023-01-10 09:02:27',
                'company_expense_item_updated' => '2023-01-10 09:02:27',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '51.00',
                'company_expense_item_average_price_per_tree' => '0.02',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            6 => 
            array (
                'company_expense_item_id' => 2131,
                'company_expense_id' => 1351,
                'setting_expense_id' => 15,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '280.00',
                'company_expense_item_total' => '280.00',
                'company_expense_item_created' => '2023-01-10 09:01:24',
                'company_expense_item_updated' => '2023-01-10 09:01:24',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '280.00',
                'company_expense_item_average_price_per_tree' => '0.09',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            7 => 
            array (
                'company_expense_item_id' => 2132,
                'company_expense_id' => 1352,
                'setting_expense_id' => 19,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '130.10',
                'company_expense_item_total' => '130.10',
                'company_expense_item_created' => '2023-01-10 09:00:17',
                'company_expense_item_updated' => '2023-01-10 09:00:17',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '130.10',
                'company_expense_item_average_price_per_tree' => '0.04',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            8 => 
            array (
                'company_expense_item_id' => 2133,
                'company_expense_id' => 1353,
                'setting_expense_id' => 18,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '11.00',
                'company_expense_item_total' => '11.00',
                'company_expense_item_created' => '2023-01-10 08:59:31',
                'company_expense_item_updated' => '2023-01-10 08:59:31',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '11.00',
                'company_expense_item_average_price_per_tree' => '0.00',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            9 => 
            array (
                'company_expense_item_id' => 2134,
                'company_expense_id' => 1354,
                'setting_expense_id' => 13,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '1928.90',
                'company_expense_item_total' => '1928.90',
                'company_expense_item_created' => '2023-01-10 09:09:15',
                'company_expense_item_updated' => '2023-01-10 09:09:15',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '1928.90',
                'company_expense_item_average_price_per_tree' => '0.61',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            10 => 
            array (
                'company_expense_item_id' => 2183,
                'company_expense_id' => 1364,
                'setting_expense_id' => 20,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '102.05',
                'company_expense_item_total' => '102.05',
                'company_expense_item_created' => '2023-01-15 08:56:32',
                'company_expense_item_updated' => '2023-01-15 08:56:32',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '102.05',
                'company_expense_item_average_price_per_tree' => '0.03',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            11 => 
            array (
                'company_expense_item_id' => 2184,
                'company_expense_id' => 1365,
                'setting_expense_id' => 25,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '180.00',
                'company_expense_item_total' => '180.00',
                'company_expense_item_created' => '2023-01-15 10:43:32',
                'company_expense_item_updated' => '2023-01-15 10:43:32',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '180.00',
                'company_expense_item_average_price_per_tree' => '0.06',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            12 => 
            array (
                'company_expense_item_id' => 2185,
                'company_expense_id' => 1366,
                'setting_expense_id' => 26,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '58.00',
                'company_expense_item_total' => '58.00',
                'company_expense_item_created' => '2023-01-15 10:53:55',
                'company_expense_item_updated' => '2023-01-15 10:53:55',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '58.00',
                'company_expense_item_average_price_per_tree' => '0.02',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            13 => 
            array (
                'company_expense_item_id' => 2186,
                'company_expense_id' => 1367,
                'setting_expense_id' => 27,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '13.80',
                'company_expense_item_total' => '13.80',
                'company_expense_item_created' => '2023-01-15 11:06:38',
                'company_expense_item_updated' => '2023-01-15 11:06:38',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '13.80',
                'company_expense_item_average_price_per_tree' => '0.00',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            14 => 
            array (
                'company_expense_item_id' => 2187,
                'company_expense_id' => 1368,
                'setting_expense_id' => 20,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '200.00',
                'company_expense_item_total' => '200.00',
                'company_expense_item_created' => '2023-01-15 11:33:02',
                'company_expense_item_updated' => '2023-01-15 11:33:02',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '200.00',
                'company_expense_item_average_price_per_tree' => '0.06',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            15 => 
            array (
                'company_expense_item_id' => 2188,
                'company_expense_id' => 1369,
                'setting_expense_id' => 24,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '150.00',
                'company_expense_item_total' => '150.00',
                'company_expense_item_created' => '2023-01-15 11:33:14',
                'company_expense_item_updated' => '2023-01-15 11:33:14',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '150.00',
                'company_expense_item_average_price_per_tree' => '0.05',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            16 => 
            array (
                'company_expense_item_id' => 2189,
                'company_expense_id' => 1370,
                'setting_expense_id' => 28,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '490.00',
                'company_expense_item_total' => '490.00',
                'company_expense_item_created' => '2023-01-15 11:35:39',
                'company_expense_item_updated' => '2023-01-15 11:35:39',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '490.00',
                'company_expense_item_average_price_per_tree' => '0.15',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            17 => 
            array (
                'company_expense_item_id' => 2191,
                'company_expense_id' => 1372,
                'setting_expense_id' => 30,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '2600.00',
                'company_expense_item_total' => '2600.00',
                'company_expense_item_created' => '2023-01-15 11:39:47',
                'company_expense_item_updated' => '2023-01-15 11:39:47',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '2600.00',
                'company_expense_item_average_price_per_tree' => '0.82',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            18 => 
            array (
                'company_expense_item_id' => 2192,
                'company_expense_id' => 1373,
                'setting_expense_id' => 26,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '238.00',
                'company_expense_item_total' => '238.00',
                'company_expense_item_created' => '2023-01-15 13:58:08',
                'company_expense_item_updated' => '2023-01-15 13:58:08',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '238.00',
                'company_expense_item_average_price_per_tree' => '0.08',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            19 => 
            array (
                'company_expense_item_id' => 2194,
                'company_expense_id' => 1374,
                'setting_expense_id' => 24,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '552.00',
                'company_expense_item_total' => '552.00',
                'company_expense_item_created' => '2023-01-15 13:57:09',
                'company_expense_item_updated' => '2023-01-15 13:57:09',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '552.00',
                'company_expense_item_average_price_per_tree' => '0.17',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            20 => 
            array (
                'company_expense_item_id' => 2195,
                'company_expense_id' => 1375,
                'setting_expense_id' => 21,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '180.00',
                'company_expense_item_total' => '180.00',
                'company_expense_item_created' => '2023-01-15 14:30:35',
                'company_expense_item_updated' => '2023-01-15 14:30:35',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '180.00',
                'company_expense_item_average_price_per_tree' => '0.06',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            21 => 
            array (
                'company_expense_item_id' => 2196,
                'company_expense_id' => 1376,
                'setting_expense_id' => 23,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 2,
                'company_expense_item_unit_price' => '400.00',
                'company_expense_item_total' => '800.00',
                'company_expense_item_created' => '2023-01-15 14:30:21',
                'company_expense_item_updated' => '2023-01-15 14:30:21',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '800.00',
                'company_expense_item_average_price_per_tree' => '0.25',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            22 => 
            array (
                'company_expense_item_id' => 2197,
                'company_expense_id' => 1377,
                'setting_expense_id' => 22,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '129.02',
                'company_expense_item_total' => '129.02',
                'company_expense_item_created' => '2023-01-15 14:30:06',
                'company_expense_item_updated' => '2023-01-15 14:30:06',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '129.02',
                'company_expense_item_average_price_per_tree' => '0.04',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            23 => 
            array (
                'company_expense_item_id' => 2198,
                'company_expense_id' => 1378,
                'setting_expense_id' => 22,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '113.31',
                'company_expense_item_total' => '113.31',
                'company_expense_item_created' => '2023-01-15 13:52:12',
                'company_expense_item_updated' => '2023-01-15 13:52:12',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '113.31',
                'company_expense_item_average_price_per_tree' => '0.04',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            24 => 
            array (
                'company_expense_item_id' => 2199,
                'company_expense_id' => 1379,
                'setting_expense_id' => 19,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '47.00',
                'company_expense_item_total' => '47.00',
                'company_expense_item_created' => '2023-01-15 13:51:00',
                'company_expense_item_updated' => '2023-01-15 13:51:00',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '47.00',
                'company_expense_item_average_price_per_tree' => '0.01',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            25 => 
            array (
                'company_expense_item_id' => 2200,
                'company_expense_id' => 1380,
                'setting_expense_id' => 26,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '259.00',
                'company_expense_item_total' => '259.00',
                'company_expense_item_created' => '2023-01-15 14:02:46',
                'company_expense_item_updated' => '2023-01-15 14:02:46',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '259.00',
                'company_expense_item_average_price_per_tree' => '0.08',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            26 => 
            array (
                'company_expense_item_id' => 2312,
                'company_expense_id' => 1411,
                'setting_expense_id' => 28,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '200.00',
                'company_expense_item_total' => '200.00',
                'company_expense_item_created' => '2023-01-29 20:50:56',
                'company_expense_item_updated' => '2023-01-29 20:50:56',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '200.00',
                'company_expense_item_average_price_per_tree' => '0.06',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            27 => 
            array (
                'company_expense_item_id' => 2313,
                'company_expense_id' => 1412,
                'setting_expense_id' => 24,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 114,
                'company_expense_item_unit_price' => '114.00',
                'company_expense_item_total' => '12996.00',
                'company_expense_item_created' => '2023-01-29 20:49:51',
                'company_expense_item_updated' => '2023-01-29 20:49:51',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '12996.00',
                'company_expense_item_average_price_per_tree' => '4.10',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            28 => 
            array (
                'company_expense_item_id' => 2314,
                'company_expense_id' => 1413,
                'setting_expense_id' => 20,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '249.75',
                'company_expense_item_total' => '249.75',
                'company_expense_item_created' => '2023-01-29 20:48:51',
                'company_expense_item_updated' => '2023-01-29 20:48:51',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '249.75',
                'company_expense_item_average_price_per_tree' => '0.08',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            29 => 
            array (
                'company_expense_item_id' => 2315,
                'company_expense_id' => 1414,
                'setting_expense_id' => 22,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '55.15',
                'company_expense_item_total' => '55.15',
                'company_expense_item_created' => '2023-01-29 20:47:54',
                'company_expense_item_updated' => '2023-01-29 20:47:54',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '55.15',
                'company_expense_item_average_price_per_tree' => '0.02',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            30 => 
            array (
                'company_expense_item_id' => 2316,
                'company_expense_id' => 1415,
                'setting_expense_id' => 14,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '124.05',
                'company_expense_item_total' => '124.05',
                'company_expense_item_created' => '2023-01-29 20:47:12',
                'company_expense_item_updated' => '2023-01-29 20:47:12',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '124.05',
                'company_expense_item_average_price_per_tree' => '0.04',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            31 => 
            array (
                'company_expense_item_id' => 2317,
                'company_expense_id' => 1416,
                'setting_expense_id' => 22,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '115.12',
                'company_expense_item_total' => '115.12',
                'company_expense_item_created' => '2023-01-29 20:46:28',
                'company_expense_item_updated' => '2023-01-29 20:46:28',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '115.12',
                'company_expense_item_average_price_per_tree' => '0.04',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            32 => 
            array (
                'company_expense_item_id' => 2318,
                'company_expense_id' => 1417,
                'setting_expense_id' => 23,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '400.00',
                'company_expense_item_total' => '400.00',
                'company_expense_item_created' => '2023-01-29 20:45:17',
                'company_expense_item_updated' => '2023-01-29 20:45:17',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '400.00',
                'company_expense_item_average_price_per_tree' => '0.13',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            33 => 
            array (
                'company_expense_item_id' => 2319,
                'company_expense_id' => 1418,
                'setting_expense_id' => 23,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '320.00',
                'company_expense_item_total' => '320.00',
                'company_expense_item_created' => '2023-01-29 20:44:38',
                'company_expense_item_updated' => '2023-01-29 20:44:38',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '320.00',
                'company_expense_item_average_price_per_tree' => '0.10',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            34 => 
            array (
                'company_expense_item_id' => 2320,
                'company_expense_id' => 1419,
                'setting_expense_id' => 14,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '116.25',
                'company_expense_item_total' => '116.25',
                'company_expense_item_created' => '2023-01-29 20:43:36',
                'company_expense_item_updated' => '2023-01-29 20:43:36',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '116.25',
                'company_expense_item_average_price_per_tree' => '0.04',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            35 => 
            array (
                'company_expense_item_id' => 2321,
                'company_expense_id' => 1420,
                'setting_expense_id' => 22,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '107.00',
                'company_expense_item_total' => '107.00',
                'company_expense_item_created' => '2023-01-29 21:15:34',
                'company_expense_item_updated' => '2023-01-29 21:15:34',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '107.00',
                'company_expense_item_average_price_per_tree' => '0.03',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            36 => 
            array (
                'company_expense_item_id' => 2322,
                'company_expense_id' => 1421,
                'setting_expense_id' => 14,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '50.00',
                'company_expense_item_total' => '50.00',
                'company_expense_item_created' => '2023-01-29 21:14:54',
                'company_expense_item_updated' => '2023-01-29 21:14:54',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '50.00',
                'company_expense_item_average_price_per_tree' => '0.02',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            37 => 
            array (
                'company_expense_item_id' => 2323,
                'company_expense_id' => 1422,
                'setting_expense_id' => 10,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '200.00',
                'company_expense_item_total' => '200.00',
                'company_expense_item_created' => '2023-01-29 21:12:55',
                'company_expense_item_updated' => '2023-01-29 21:12:55',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '200.00',
                'company_expense_item_average_price_per_tree' => '0.06',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            38 => 
            array (
                'company_expense_item_id' => 2324,
                'company_expense_id' => 1423,
                'setting_expense_id' => 24,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '7.00',
                'company_expense_item_total' => '7.00',
                'company_expense_item_created' => '2023-01-29 21:11:19',
                'company_expense_item_updated' => '2023-01-29 21:11:19',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '7.00',
                'company_expense_item_average_price_per_tree' => '0.00',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            39 => 
            array (
                'company_expense_item_id' => 2325,
                'company_expense_id' => 1424,
                'setting_expense_id' => 19,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '14.50',
                'company_expense_item_total' => '14.50',
                'company_expense_item_created' => '2023-01-29 21:10:24',
                'company_expense_item_updated' => '2023-01-29 21:10:24',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '14.50',
                'company_expense_item_average_price_per_tree' => '0.00',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            40 => 
            array (
                'company_expense_item_id' => 2326,
                'company_expense_id' => 1425,
                'setting_expense_id' => 27,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '304.00',
                'company_expense_item_total' => '304.00',
                'company_expense_item_created' => '2023-01-29 21:22:18',
                'company_expense_item_updated' => '2023-01-29 21:22:18',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '304.00',
                'company_expense_item_average_price_per_tree' => '0.10',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            41 => 
            array (
                'company_expense_item_id' => 2327,
                'company_expense_id' => 1426,
                'setting_expense_id' => 28,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '197.80',
                'company_expense_item_total' => '197.80',
                'company_expense_item_created' => '2023-01-29 21:21:46',
                'company_expense_item_updated' => '2023-01-29 21:21:46',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '197.80',
                'company_expense_item_average_price_per_tree' => '0.06',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            42 => 
            array (
                'company_expense_item_id' => 2328,
                'company_expense_id' => 1427,
                'setting_expense_id' => 23,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '324.00',
                'company_expense_item_total' => '324.00',
                'company_expense_item_created' => '2023-01-29 21:36:46',
                'company_expense_item_updated' => '2023-01-29 21:36:46',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '324.00',
                'company_expense_item_average_price_per_tree' => '0.10',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            43 => 
            array (
                'company_expense_item_id' => 2329,
                'company_expense_id' => 1428,
                'setting_expense_id' => 29,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '462.80',
                'company_expense_item_total' => '462.80',
                'company_expense_item_created' => '2023-01-29 21:46:44',
                'company_expense_item_updated' => '2023-01-29 21:46:44',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '462.80',
                'company_expense_item_average_price_per_tree' => '0.15',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            44 => 
            array (
                'company_expense_item_id' => 2330,
                'company_expense_id' => 1429,
                'setting_expense_id' => 23,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '1214.00',
                'company_expense_item_total' => '1214.00',
                'company_expense_item_created' => '2023-01-29 21:46:03',
                'company_expense_item_updated' => '2023-01-29 21:46:03',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '1214.00',
                'company_expense_item_average_price_per_tree' => '0.38',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            45 => 
            array (
                'company_expense_item_id' => 2331,
                'company_expense_id' => 1430,
                'setting_expense_id' => 29,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '683.50',
                'company_expense_item_total' => '683.50',
                'company_expense_item_created' => '2023-01-29 21:40:04',
                'company_expense_item_updated' => '2023-01-29 21:40:04',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '683.50',
                'company_expense_item_average_price_per_tree' => '0.22',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            46 => 
            array (
                'company_expense_item_id' => 2423,
                'company_expense_id' => 1479,
                'setting_expense_id' => 30,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '1021.00',
                'company_expense_item_total' => '1021.00',
                'company_expense_item_created' => '2023-01-31 21:48:30',
                'company_expense_item_updated' => '2023-01-31 21:48:30',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '1021.00',
                'company_expense_item_average_price_per_tree' => '0.32',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            47 => 
            array (
                'company_expense_item_id' => 2424,
                'company_expense_id' => 1480,
                'setting_expense_id' => 21,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '2640.00',
                'company_expense_item_total' => '2640.00',
                'company_expense_item_created' => '2023-01-31 21:54:21',
                'company_expense_item_updated' => '2023-01-31 21:54:21',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '2640.00',
                'company_expense_item_average_price_per_tree' => '0.83',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            48 => 
            array (
                'company_expense_item_id' => 2425,
                'company_expense_id' => 1481,
                'setting_expense_id' => 14,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '49.00',
                'company_expense_item_total' => '49.00',
                'company_expense_item_created' => '2023-01-31 22:00:59',
                'company_expense_item_updated' => '2023-01-31 22:00:59',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '49.00',
                'company_expense_item_average_price_per_tree' => '0.02',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            49 => 
            array (
                'company_expense_item_id' => 2426,
                'company_expense_id' => 1482,
                'setting_expense_id' => 22,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '18.50',
                'company_expense_item_total' => '18.50',
                'company_expense_item_created' => '2023-01-31 21:59:29',
                'company_expense_item_updated' => '2023-01-31 21:59:29',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '18.50',
                'company_expense_item_average_price_per_tree' => '0.01',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            50 => 
            array (
                'company_expense_item_id' => 2427,
                'company_expense_id' => 1483,
                'setting_expense_id' => 23,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '11.30',
                'company_expense_item_total' => '11.30',
                'company_expense_item_created' => '2023-01-31 22:03:23',
                'company_expense_item_updated' => '2023-01-31 22:03:23',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '11.30',
                'company_expense_item_average_price_per_tree' => '0.00',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            51 => 
            array (
                'company_expense_item_id' => 2428,
                'company_expense_id' => 1484,
                'setting_expense_id' => 10,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '14.00',
                'company_expense_item_total' => '14.00',
                'company_expense_item_created' => '2023-01-31 22:07:12',
                'company_expense_item_updated' => '2023-01-31 22:07:12',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '14.00',
                'company_expense_item_average_price_per_tree' => '0.00',
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            52 => 
            array (
                'company_expense_item_id' => 5623,
                'company_expense_id' => 3374,
                'setting_expense_id' => 20,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '100.00',
                'company_expense_item_total' => '100.00',
                'company_expense_item_created' => '2023-05-08 09:56:48',
                'company_expense_item_updated' => '2023-05-08 09:56:48',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '100.00',
                'company_expense_item_average_price_per_tree' => NULL,
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            53 => 
            array (
                'company_expense_item_id' => 5624,
                'company_expense_id' => 3375,
                'setting_expense_id' => 10,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '73.80',
                'company_expense_item_total' => '73.80',
                'company_expense_item_created' => '2023-05-08 09:56:13',
                'company_expense_item_updated' => '2023-05-08 09:56:13',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '73.80',
                'company_expense_item_average_price_per_tree' => NULL,
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            54 => 
            array (
                'company_expense_item_id' => 5625,
                'company_expense_id' => 3376,
                'setting_expense_id' => 21,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '50.00',
                'company_expense_item_total' => '50.00',
                'company_expense_item_created' => '2023-05-08 09:55:35',
                'company_expense_item_updated' => '2023-05-08 09:55:35',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '50.00',
                'company_expense_item_average_price_per_tree' => NULL,
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            55 => 
            array (
                'company_expense_item_id' => 5626,
                'company_expense_id' => 3377,
                'setting_expense_id' => 20,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '50.00',
                'company_expense_item_total' => '50.00',
                'company_expense_item_created' => '2023-05-08 09:55:05',
                'company_expense_item_updated' => '2023-05-08 09:55:05',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '50.00',
                'company_expense_item_average_price_per_tree' => NULL,
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            56 => 
            array (
                'company_expense_item_id' => 5627,
                'company_expense_id' => 3378,
                'setting_expense_id' => 26,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 30,
                'company_expense_item_unit_price' => '2.05',
                'company_expense_item_total' => '62.02',
                'company_expense_item_created' => '2023-05-08 09:54:30',
                'company_expense_item_updated' => '2023-05-08 09:54:30',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '62.02',
                'company_expense_item_average_price_per_tree' => NULL,
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            57 => 
            array (
                'company_expense_item_id' => 5628,
                'company_expense_id' => 3379,
                'setting_expense_id' => 26,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 2,
                'company_expense_item_unit_price' => '2.05',
                'company_expense_item_total' => '6.10',
                'company_expense_item_created' => '2023-05-08 09:53:50',
                'company_expense_item_updated' => '2023-05-08 09:53:50',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '6.10',
                'company_expense_item_average_price_per_tree' => NULL,
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            58 => 
            array (
                'company_expense_item_id' => 5629,
                'company_expense_id' => 3380,
                'setting_expense_id' => 26,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 9,
                'company_expense_item_unit_price' => '2.05',
                'company_expense_item_total' => '18.75',
                'company_expense_item_created' => '2023-05-08 09:52:50',
                'company_expense_item_updated' => '2023-05-08 09:52:50',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '18.75',
                'company_expense_item_average_price_per_tree' => NULL,
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            59 => 
            array (
                'company_expense_item_id' => 5630,
                'company_expense_id' => 3381,
                'setting_expense_id' => 26,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 15,
                'company_expense_item_unit_price' => '2.05',
                'company_expense_item_total' => '31.27',
                'company_expense_item_created' => '2023-05-08 09:52:09',
                'company_expense_item_updated' => '2023-05-08 09:52:09',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '31.27',
                'company_expense_item_average_price_per_tree' => NULL,
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            60 => 
            array (
                'company_expense_item_id' => 5631,
                'company_expense_id' => 3382,
                'setting_expense_id' => 26,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 18,
                'company_expense_item_unit_price' => '2.05',
                'company_expense_item_total' => '38.11',
                'company_expense_item_created' => '2023-05-08 09:51:25',
                'company_expense_item_updated' => '2023-05-08 09:51:25',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '38.11',
                'company_expense_item_average_price_per_tree' => NULL,
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
            61 => 
            array (
                'company_expense_item_id' => 5632,
                'company_expense_id' => 3383,
                'setting_expense_id' => 20,
                'company_expense_item_detail' => NULL,
                'company_expense_item_unit' => 1,
                'company_expense_item_unit_price' => '150.00',
                'company_expense_item_total' => '150.00',
                'company_expense_item_created' => '2023-05-08 09:50:38',
                'company_expense_item_updated' => '2023-05-08 09:50:38',
                'is_claim' => 1,
                'user_wallet_history_id' => NULL,
                'worker_wallet_history_id' => NULL,
                'claim_remaining_amount' => '150.00',
                'company_expense_item_average_price_per_tree' => NULL,
                'supplier_id' => NULL,
                'remark' => NULL,
            ),
        ));
        
        
    }
}