<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TblClaimItemTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_claim_item')->delete();
        
        \DB::table('tbl_claim_item')->insert(array (
            0 => 
            array (
                'claim_item_id' => 1,
                'claim_id' => 1,
                'claim_item_date' => '2023-05-08',
                'claim_item_name' => '{"en":"Touch N Go","cn":"\\u8fc7\\u8def\\u8d39"}',
                'claim_item_created' => '2023-05-09 12:49:23',
                'claim_item_updated' => '2023-05-09 12:49:23',
                'claim_item_value' => '100.00',
                'claim_item_amount' => '100.00',
                'claim_item_amount_claim' => '100.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 5623,
            ),
            1 => 
            array (
                'claim_item_id' => 2,
                'claim_id' => 1,
                'claim_item_date' => '2023-05-08',
                'claim_item_name' => '{"en":"Staff Meal","cn":"\\u5458\\u5de5\\u805a\\u9910"}',
                'claim_item_created' => '2023-05-09 12:49:23',
                'claim_item_updated' => '2023-05-09 12:49:23',
                'claim_item_value' => '73.80',
                'claim_item_amount' => '73.80',
                'claim_item_amount_claim' => '73.80',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 5624,
            ),
            2 => 
            array (
                'claim_item_id' => 3,
                'claim_id' => 1,
                'claim_item_date' => '2023-05-08',
                'claim_item_name' => '{"en":"Petrol 95","cn":"\\u6c14\\u6cb9 95"}',
                'claim_item_created' => '2023-05-09 12:49:24',
                'claim_item_updated' => '2023-05-09 12:49:24',
                'claim_item_value' => '50.00',
                'claim_item_amount' => '50.00',
                'claim_item_amount_claim' => '50.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 5625,
            ),
            3 => 
            array (
                'claim_item_id' => 4,
                'claim_id' => 1,
                'claim_item_date' => '2023-05-08',
                'claim_item_name' => '{"en":"Touch N Go","cn":"\\u8fc7\\u8def\\u8d39"}',
                'claim_item_created' => '2023-05-09 12:49:25',
                'claim_item_updated' => '2023-05-09 12:49:25',
                'claim_item_value' => '50.00',
                'claim_item_amount' => '50.00',
                'claim_item_amount_claim' => '50.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 5626,
            ),
            4 => 
            array (
                'claim_item_id' => 5,
                'claim_id' => 2,
                'claim_item_date' => '2023-05-08',
                'claim_item_name' => '{"en":"Petrol 95","cn":"\\u6c14\\u6cb9 95"}',
                'claim_item_created' => '2023-05-09 12:49:25',
                'claim_item_updated' => '2023-05-09 12:49:25',
                'claim_item_value' => '2.05',
                'claim_item_amount' => '62.02',
                'claim_item_amount_claim' => '62.02',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 5627,
            ),
            5 => 
            array (
                'claim_item_id' => 6,
                'claim_id' => 2,
                'claim_item_date' => '2023-05-08',
                'claim_item_name' => '{"en":"Petrol 95","cn":"\\u6c14\\u6cb9 95"}',
                'claim_item_created' => '2023-05-09 12:49:26',
                'claim_item_updated' => '2023-05-09 12:49:26',
                'claim_item_value' => '2.05',
                'claim_item_amount' => '6.10',
                'claim_item_amount_claim' => '6.10',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 5628,
            ),
            6 => 
            array (
                'claim_item_id' => 7,
                'claim_id' => 2,
                'claim_item_date' => '2023-05-08',
                'claim_item_name' => '{"en":"Petrol 95","cn":"\\u6c14\\u6cb9 95"}',
                'claim_item_created' => '2023-05-09 12:49:27',
                'claim_item_updated' => '2023-05-09 12:49:27',
                'claim_item_value' => '2.05',
                'claim_item_amount' => '18.75',
                'claim_item_amount_claim' => '18.75',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 5629,
            ),
            7 => 
            array (
                'claim_item_id' => 8,
                'claim_id' => 2,
                'claim_item_date' => '2023-05-08',
                'claim_item_name' => '{"en":"Petrol 95","cn":"\\u6c14\\u6cb9 95"}',
                'claim_item_created' => '2023-05-09 12:49:27',
                'claim_item_updated' => '2023-05-09 12:49:27',
                'claim_item_value' => '2.05',
                'claim_item_amount' => '31.27',
                'claim_item_amount_claim' => '31.27',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 5630,
            ),
            8 => 
            array (
                'claim_item_id' => 9,
                'claim_id' => 2,
                'claim_item_date' => '2023-05-08',
                'claim_item_name' => '{"en":"Petrol 95","cn":"\\u6c14\\u6cb9 95"}',
                'claim_item_created' => '2023-05-09 12:49:28',
                'claim_item_updated' => '2023-05-09 12:49:28',
                'claim_item_value' => '2.05',
                'claim_item_amount' => '38.11',
                'claim_item_amount_claim' => '38.11',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 5631,
            ),
            9 => 
            array (
                'claim_item_id' => 10,
                'claim_id' => 2,
                'claim_item_date' => '2023-05-08',
                'claim_item_name' => '{"en":"Touch N Go","cn":"\\u8fc7\\u8def\\u8d39"}',
                'claim_item_created' => '2023-05-09 12:49:28',
                'claim_item_updated' => '2023-05-09 12:49:28',
                'claim_item_value' => '150.00',
                'claim_item_amount' => '150.00',
                'claim_item_amount_claim' => '150.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 5632,
            ),
            10 => 
            array (
                'claim_item_id' => 11,
                'claim_id' => 3,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"TK Cheong Auto Bike","cn":"\\u7ef4\\u6301\\u7535\\u5355\\u8f66"}',
                'claim_item_created' => '2023-05-12 21:24:04',
                'claim_item_updated' => '2023-05-12 21:24:04',
                'claim_item_value' => '238.00',
                'claim_item_amount' => '238.00',
                'claim_item_amount_claim' => '238.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2192,
            ),
            11 => 
            array (
                'claim_item_id' => 12,
                'claim_id' => 3,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"Opulence Auto Parts","cn":"\\u7ef4\\u4fee\\u00b7\\u6c7d\\u8f66\\u4e2d\\u5fc3"}',
                'claim_item_created' => '2023-05-12 21:24:06',
                'claim_item_updated' => '2023-05-12 21:24:06',
                'claim_item_value' => '552.00',
                'claim_item_amount' => '552.00',
                'claim_item_amount_claim' => '552.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2194,
            ),
            12 => 
            array (
                'claim_item_id' => 13,
                'claim_id' => 3,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"Aisyigir Firash Enterprise","cn":"\\u62d6\\u8f66"}',
                'claim_item_created' => '2023-05-12 21:24:08',
                'claim_item_updated' => '2023-05-12 21:24:08',
                'claim_item_value' => '180.00',
                'claim_item_amount' => '180.00',
                'claim_item_amount_claim' => '180.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2195,
            ),
            13 => 
            array (
                'claim_item_id' => 14,
                'claim_id' => 4,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"Five Petrol Jalan Tras","cn":"5Petrol \\u6253\\u6cb9"}',
                'claim_item_created' => '2023-05-12 21:24:09',
                'claim_item_updated' => '2023-05-12 21:24:09',
                'claim_item_value' => '400.00',
                'claim_item_amount' => '800.00',
                'claim_item_amount_claim' => '800.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2196,
            ),
            14 => 
            array (
                'claim_item_id' => 15,
                'claim_id' => 4,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"BH Petrol Raub","cn":"BHP \\u6253\\u6cb9"}',
                'claim_item_created' => '2023-05-12 21:24:10',
                'claim_item_updated' => '2023-05-12 21:24:10',
                'claim_item_value' => '129.02',
                'claim_item_amount' => '129.02',
                'claim_item_amount_claim' => '129.02',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2197,
            ),
            15 => 
            array (
                'claim_item_id' => 16,
                'claim_id' => 4,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"BH Petrol Raub","cn":"BHP \\u6253\\u6cb9"}',
                'claim_item_created' => '2023-05-12 21:24:11',
                'claim_item_updated' => '2023-05-12 21:24:11',
                'claim_item_value' => '113.31',
                'claim_item_amount' => '113.31',
                'claim_item_amount_claim' => '113.31',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2198,
            ),
            16 => 
            array (
                'claim_item_id' => 17,
                'claim_id' => 4,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"LEE HING CHEONG","cn":"LEE HING CHEONG"}',
                'claim_item_created' => '2023-05-12 21:24:12',
                'claim_item_updated' => '2023-05-12 21:24:12',
                'claim_item_value' => '47.00',
                'claim_item_amount' => '47.00',
                'claim_item_amount_claim' => '47.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2199,
            ),
            17 => 
            array (
                'claim_item_id' => 18,
                'claim_id' => 4,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"TK Cheong Auto Bike","cn":"\\u7ef4\\u6301\\u7535\\u5355\\u8f66"}',
                'claim_item_created' => '2023-05-12 21:24:13',
                'claim_item_updated' => '2023-05-12 21:24:13',
                'claim_item_value' => '259.00',
                'claim_item_amount' => '259.00',
                'claim_item_amount_claim' => '259.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2200,
            ),
            18 => 
            array (
                'claim_item_id' => 19,
                'claim_id' => 4,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"FL HOME CENTRE SDN BHD","cn":"\\u4e94\\u91d1\\u5e97"}',
                'claim_item_created' => '2023-05-12 21:24:13',
                'claim_item_updated' => '2023-05-12 21:24:13',
                'claim_item_value' => '200.00',
                'claim_item_amount' => '200.00',
                'claim_item_amount_claim' => '200.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2312,
            ),
            19 => 
            array (
                'claim_item_id' => 20,
                'claim_id' => 5,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"LEE HING CHEONG","cn":"LEE HING CHEONG"}',
                'claim_item_created' => '2023-05-12 21:24:14',
                'claim_item_updated' => '2023-05-12 21:24:14',
                'claim_item_value' => '114.00',
                'claim_item_amount' => '12996.00',
                'claim_item_amount_claim' => '12996.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2313,
            ),
            20 => 
            array (
                'claim_item_id' => 21,
                'claim_id' => 5,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"KUMPULAN PASARAYA PANTAI TIMOR","cn":"\\u4e1c\\u6d77\\u5cb8\\u8d85\\u5e02"}',
                'claim_item_created' => '2023-05-12 21:24:15',
                'claim_item_updated' => '2023-05-12 21:24:15',
                'claim_item_value' => '249.75',
                'claim_item_amount' => '249.75',
                'claim_item_amount_claim' => '249.75',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2314,
            ),
            21 => 
            array (
                'claim_item_id' => 22,
                'claim_id' => 5,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"BH Petrol Raub","cn":"BHP \\u6253\\u6cb9"}',
                'claim_item_created' => '2023-05-12 21:24:16',
                'claim_item_updated' => '2023-05-12 21:24:16',
                'claim_item_value' => '55.15',
                'claim_item_amount' => '55.15',
                'claim_item_amount_claim' => '55.15',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2315,
            ),
            22 => 
            array (
                'claim_item_id' => 23,
                'claim_id' => 5,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"Petrol","cn":"Petrol"}',
                'claim_item_created' => '2023-05-12 21:24:17',
                'claim_item_updated' => '2023-05-12 21:24:17',
                'claim_item_value' => '124.05',
                'claim_item_amount' => '124.05',
                'claim_item_amount_claim' => '124.05',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2316,
            ),
            23 => 
            array (
                'claim_item_id' => 24,
                'claim_id' => 5,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"BH Petrol Raub","cn":"BHP \\u6253\\u6cb9"}',
                'claim_item_created' => '2023-05-12 21:24:18',
                'claim_item_updated' => '2023-05-12 21:24:18',
                'claim_item_value' => '115.12',
                'claim_item_amount' => '115.12',
                'claim_item_amount_claim' => '115.12',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2317,
            ),
            24 => 
            array (
                'claim_item_id' => 25,
                'claim_id' => 5,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"Five Petrol Jalan Tras","cn":"5Petrol \\u6253\\u6cb9"}',
                'claim_item_created' => '2023-05-12 21:24:19',
                'claim_item_updated' => '2023-05-12 21:24:19',
                'claim_item_value' => '400.00',
                'claim_item_amount' => '400.00',
                'claim_item_amount_claim' => '400.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2318,
            ),
            25 => 
            array (
                'claim_item_id' => 26,
                'claim_id' => 5,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"Five Petrol Jalan Tras","cn":"5Petrol \\u6253\\u6cb9"}',
                'claim_item_created' => '2023-05-12 21:24:20',
                'claim_item_updated' => '2023-05-12 21:24:20',
                'claim_item_value' => '320.00',
                'claim_item_amount' => '320.00',
                'claim_item_amount_claim' => '320.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2319,
            ),
            26 => 
            array (
                'claim_item_id' => 27,
                'claim_id' => 6,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"Petrol","cn":"Petrol"}',
                'claim_item_created' => '2023-05-12 21:24:21',
                'claim_item_updated' => '2023-05-12 21:24:21',
                'claim_item_value' => '116.25',
                'claim_item_amount' => '116.25',
                'claim_item_amount_claim' => '116.25',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2320,
            ),
            27 => 
            array (
                'claim_item_id' => 28,
                'claim_id' => 6,
                'claim_item_date' => '2023-01-31',
                'claim_item_name' => '{"en":"Agro Chemical and Hardware Enterprise Sdn Bhd","cn":"\\u6c34\\u5589"}',
                'claim_item_created' => '2023-05-12 21:24:22',
                'claim_item_updated' => '2023-05-12 21:24:22',
                'claim_item_value' => '1021.00',
                'claim_item_amount' => '1021.00',
                'claim_item_amount_claim' => '1021.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2423,
            ),
            28 => 
            array (
                'claim_item_id' => 29,
                'claim_id' => 6,
                'claim_item_date' => '2023-01-31',
                'claim_item_name' => '{"en":"KLH Hardware & Machinery Trading","cn":"\\u7535\\u5668- \\u5272\\u8349\\u673a"}',
                'claim_item_created' => '2023-05-12 21:24:23',
                'claim_item_updated' => '2023-05-12 21:24:23',
                'claim_item_value' => '2640.00',
                'claim_item_amount' => '2640.00',
                'claim_item_amount_claim' => '2640.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2424,
            ),
            29 => 
            array (
                'claim_item_id' => 30,
                'claim_id' => 6,
                'claim_item_date' => '2023-01-31',
                'claim_item_name' => '{"en":"Petrol","cn":"Petrol"}',
                'claim_item_created' => '2023-05-12 21:24:24',
                'claim_item_updated' => '2023-05-12 21:24:24',
                'claim_item_value' => '49.00',
                'claim_item_amount' => '49.00',
                'claim_item_amount_claim' => '49.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2425,
            ),
            30 => 
            array (
                'claim_item_id' => 31,
                'claim_id' => 6,
                'claim_item_date' => '2023-01-31',
                'claim_item_name' => '{"en":"Perniagaan Fook Tuck","cn":"\\u6742\\u8d27"}',
                'claim_item_created' => '2023-05-12 21:24:25',
                'claim_item_updated' => '2023-05-12 21:24:25',
                'claim_item_value' => '18.50',
                'claim_item_amount' => '18.50',
                'claim_item_amount_claim' => '18.50',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2426,
            ),
            31 => 
            array (
                'claim_item_id' => 32,
                'claim_id' => 6,
                'claim_item_date' => '2023-01-31',
                'claim_item_name' => '{"en":"Pahang Pharmacy Sdn Bhd","cn":"\\u836f\\u7269"}',
                'claim_item_created' => '2023-05-12 21:24:26',
                'claim_item_updated' => '2023-05-12 21:24:26',
                'claim_item_value' => '11.30',
                'claim_item_amount' => '11.30',
                'claim_item_amount_claim' => '11.30',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2427,
            ),
            32 => 
            array (
                'claim_item_id' => 33,
                'claim_id' => 6,
                'claim_item_date' => '2023-01-31',
                'claim_item_name' => '{"en":"Pustaka Pertama","cn":"\\u7b2c\\u4e00\\u4e66\\u5c40"}',
                'claim_item_created' => '2023-05-12 21:24:27',
                'claim_item_updated' => '2023-05-12 21:24:27',
                'claim_item_value' => '14.00',
                'claim_item_amount' => '14.00',
                'claim_item_amount_claim' => '14.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2428,
            ),
            33 => 
            array (
                'claim_item_id' => 34,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-10',
                'claim_item_name' => '{"en":"Petrol","cn":"Petrol"}',
                'claim_item_created' => '2023-05-12 21:40:45',
                'claim_item_updated' => '2023-05-12 21:40:45',
                'claim_item_value' => '150.00',
                'claim_item_amount' => '150.00',
                'claim_item_amount_claim' => '150.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2125,
            ),
            34 => 
            array (
                'claim_item_id' => 35,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-10',
                'claim_item_name' => '{"en":"Petrol","cn":"Petrol"}',
                'claim_item_created' => '2023-05-12 21:40:46',
                'claim_item_updated' => '2023-05-12 21:40:46',
                'claim_item_value' => '143.00',
                'claim_item_amount' => '143.00',
                'claim_item_amount_claim' => '143.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2126,
            ),
            35 => 
            array (
                'claim_item_id' => 36,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-10',
                'claim_item_name' => '{"en":"TF Value- Mart Sdn Bhd","cn":"TF\\u8d85\\u5e02"}',
                'claim_item_created' => '2023-05-12 21:40:46',
                'claim_item_updated' => '2023-05-12 21:40:46',
                'claim_item_value' => '25.80',
                'claim_item_amount' => '25.80',
                'claim_item_amount_claim' => '25.80',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2127,
            ),
            36 => 
            array (
                'claim_item_id' => 37,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-10',
                'claim_item_name' => '{"en":"TF Value- Mart Sdn Bhd","cn":"TF\\u8d85\\u5e02"}',
                'claim_item_created' => '2023-05-12 21:40:47',
                'claim_item_updated' => '2023-05-12 21:40:47',
                'claim_item_value' => '116.68',
                'claim_item_amount' => '116.68',
                'claim_item_amount_claim' => '116.68',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2128,
            ),
            37 => 
            array (
                'claim_item_id' => 38,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-10',
                'claim_item_name' => '{"en":"KUMPULAN PASARAYA PANTAI TIMOR","cn":"\\u4e1c\\u6d77\\u5cb8\\u8d85\\u5e02"}',
                'claim_item_created' => '2023-05-12 21:40:47',
                'claim_item_updated' => '2023-05-12 21:40:47',
                'claim_item_value' => '786.20',
                'claim_item_amount' => '786.20',
                'claim_item_amount_claim' => '786.20',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2129,
            ),
            38 => 
            array (
                'claim_item_id' => 39,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-10',
                'claim_item_name' => '{"en":"99 Speed Mart  Sdn Bhd","cn":"99\\u8d85\\u5e02"}',
                'claim_item_created' => '2023-05-12 21:40:48',
                'claim_item_updated' => '2023-05-12 21:40:48',
                'claim_item_value' => '51.00',
                'claim_item_amount' => '51.00',
                'claim_item_amount_claim' => '51.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2130,
            ),
            39 => 
            array (
                'claim_item_id' => 40,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-10',
                'claim_item_name' => '{"en":"KLH HARDWARE & MACHINERY TRADING","cn":"N\\/A"}',
                'claim_item_created' => '2023-05-12 21:40:49',
                'claim_item_updated' => '2023-05-12 21:40:49',
                'claim_item_value' => '280.00',
                'claim_item_amount' => '280.00',
                'claim_item_amount_claim' => '280.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2131,
            ),
            40 => 
            array (
                'claim_item_id' => 41,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-10',
                'claim_item_name' => '{"en":"MR D.I.Y","cn":"\\u624b\\u5957\\u7c7b"}',
                'claim_item_created' => '2023-05-12 21:40:49',
                'claim_item_updated' => '2023-05-12 21:40:49',
                'claim_item_value' => '130.10',
                'claim_item_amount' => '130.10',
                'claim_item_amount_claim' => '130.10',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2132,
            ),
            41 => 
            array (
                'claim_item_id' => 42,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-10',
                'claim_item_name' => '{"en":"MEGA COPIER SALES AND SERVICES","cn":"\\u590d\\u5370"}',
                'claim_item_created' => '2023-05-12 21:40:50',
                'claim_item_updated' => '2023-05-12 21:40:50',
                'claim_item_value' => '11.00',
                'claim_item_amount' => '11.00',
                'claim_item_amount_claim' => '11.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2133,
            ),
            42 => 
            array (
                'claim_item_id' => 43,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-10',
                'claim_item_name' => '{"en":"Lai Wan Loong Hong Soon Food Court","cn":"\\u65e9\\u5348\\u9910\\uff08\\u5916\\u5356\\uff09"}',
                'claim_item_created' => '2023-05-12 21:40:51',
                'claim_item_updated' => '2023-05-12 21:40:51',
                'claim_item_value' => '1928.90',
                'claim_item_amount' => '1928.90',
                'claim_item_amount_claim' => '1928.90',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2134,
            ),
            43 => 
            array (
                'claim_item_id' => 44,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"KUMPULAN PASARAYA PANTAI TIMOR","cn":"\\u4e1c\\u6d77\\u5cb8\\u8d85\\u5e02"}',
                'claim_item_created' => '2023-05-12 21:40:51',
                'claim_item_updated' => '2023-05-12 21:40:51',
                'claim_item_value' => '102.05',
                'claim_item_amount' => '102.05',
                'claim_item_amount_claim' => '102.05',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2183,
            ),
            44 => 
            array (
                'claim_item_id' => 45,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"Raub Air Con Services","cn":"\\u52b3\\u52ff\\u51b7\\u6c14\\u670d\\u52a1"}',
                'claim_item_created' => '2023-05-12 21:40:52',
                'claim_item_updated' => '2023-05-12 21:40:52',
                'claim_item_value' => '180.00',
                'claim_item_amount' => '180.00',
                'claim_item_amount_claim' => '180.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2184,
            ),
            45 => 
            array (
                'claim_item_id' => 46,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"KLH Hardware & Machinery Trading","cn":"\\u7ef4\\u4fee\\u673a\\u5668"}',
                'claim_item_created' => '2023-05-12 21:40:53',
                'claim_item_updated' => '2023-05-12 21:40:53',
                'claim_item_value' => '58.00',
                'claim_item_amount' => '58.00',
                'claim_item_amount_claim' => '58.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2185,
            ),
            46 => 
            array (
                'claim_item_id' => 47,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"Emporium Metro","cn":"\\u5e03\\u5e97"}',
                'claim_item_created' => '2023-05-12 21:40:53',
                'claim_item_updated' => '2023-05-12 21:40:53',
                'claim_item_value' => '13.80',
                'claim_item_amount' => '13.80',
                'claim_item_amount_claim' => '13.80',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2186,
            ),
            47 => 
            array (
                'claim_item_id' => 48,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"Lee Foh Cheong","cn":"Lee Foh Cheong"}',
                'claim_item_created' => '2023-05-12 21:40:54',
                'claim_item_updated' => '2023-05-12 21:40:54',
                'claim_item_value' => '200.00',
                'claim_item_amount' => '200.00',
                'claim_item_amount_claim' => '200.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2187,
            ),
            48 => 
            array (
                'claim_item_id' => 49,
                'claim_id' => 7,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"LEE HING CHEONG","cn":"LEE HING CHEONG"}',
                'claim_item_created' => '2023-05-12 21:40:54',
                'claim_item_updated' => '2023-05-12 21:40:54',
                'claim_item_value' => '150.00',
                'claim_item_amount' => '150.00',
                'claim_item_amount_claim' => '150.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2188,
            ),
            49 => 
            array (
                'claim_item_id' => 50,
                'claim_id' => 8,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"FL HOME CENTRE SDN BHD","cn":"\\u4e94\\u91d1\\u5e97"}',
                'claim_item_created' => '2023-05-12 21:40:55',
                'claim_item_updated' => '2023-05-12 21:40:55',
                'claim_item_value' => '490.00',
                'claim_item_amount' => '490.00',
                'claim_item_amount_claim' => '490.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2189,
            ),
            50 => 
            array (
                'claim_item_id' => 1462,
                'claim_id' => 8,
                'claim_item_date' => '2023-01-15',
                'claim_item_name' => '{"en":"Raub Air Con Services","cn":"\\u7535\\u5668\\u5e97"}',
                'claim_item_created' => '2023-05-12 21:40:56',
                'claim_item_updated' => '2023-05-12 21:40:56',
                'claim_item_value' => '2600.00',
                'claim_item_amount' => '2600.00',
                'claim_item_amount_claim' => '2600.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2191,
            ),
            51 => 
            array (
                'claim_item_id' => 1463,
                'claim_id' => 8,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"BH Petrol Raub","cn":"BHP \\u6253\\u6cb9"}',
                'claim_item_created' => '2023-05-12 21:40:56',
                'claim_item_updated' => '2023-05-12 21:40:56',
                'claim_item_value' => '107.00',
                'claim_item_amount' => '107.00',
                'claim_item_amount_claim' => '107.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2321,
            ),
            52 => 
            array (
                'claim_item_id' => 1464,
                'claim_id' => 8,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"Petrol","cn":"Petrol"}',
                'claim_item_created' => '2023-05-12 21:40:57',
                'claim_item_updated' => '2023-05-12 21:40:57',
                'claim_item_value' => '50.00',
                'claim_item_amount' => '50.00',
                'claim_item_amount_claim' => '50.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2322,
            ),
            53 => 
            array (
                'claim_item_id' => 1465,
                'claim_id' => 8,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"Touch N Go","cn":"\\u8fc7\\u8def\\u8d39"}',
                'claim_item_created' => '2023-05-12 21:40:58',
                'claim_item_updated' => '2023-05-12 21:40:58',
                'claim_item_value' => '200.00',
                'claim_item_amount' => '200.00',
                'claim_item_amount_claim' => '200.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2323,
            ),
            54 => 
            array (
                'claim_item_id' => 1466,
                'claim_id' => 8,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"LEE HING CHEONG","cn":"LEE HING CHEONG"}',
                'claim_item_created' => '2023-05-12 21:40:58',
                'claim_item_updated' => '2023-05-12 21:40:58',
                'claim_item_value' => '7.00',
                'claim_item_amount' => '7.00',
                'claim_item_amount_claim' => '7.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2324,
            ),
            55 => 
            array (
                'claim_item_id' => 1467,
                'claim_id' => 8,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"LEE HING CHEONG","cn":"LEE HING CHEONG"}',
                'claim_item_created' => '2023-05-12 21:40:59',
                'claim_item_updated' => '2023-05-12 21:40:59',
                'claim_item_value' => '14.50',
                'claim_item_amount' => '14.50',
                'claim_item_amount_claim' => '14.50',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2325,
            ),
            56 => 
            array (
                'claim_item_id' => 1468,
                'claim_id' => 8,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"Toyota HLT Motors SDN BHD","cn":"\\u7ef4\\u4fee\\u8f66"}',
                'claim_item_created' => '2023-05-12 21:41:00',
                'claim_item_updated' => '2023-05-12 21:41:00',
                'claim_item_value' => '304.00',
                'claim_item_amount' => '304.00',
                'claim_item_amount_claim' => '304.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2326,
            ),
            57 => 
            array (
                'claim_item_id' => 1469,
                'claim_id' => 8,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"SWC Enterprise Sdn Bhd","cn":"\\u9505"}',
                'claim_item_created' => '2023-05-12 21:41:00',
                'claim_item_updated' => '2023-05-12 21:41:00',
                'claim_item_value' => '197.80',
                'claim_item_amount' => '197.80',
                'claim_item_amount_claim' => '197.80',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2327,
            ),
            58 => 
            array (
                'claim_item_id' => 1470,
                'claim_id' => 8,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"Lai Wan Loong Hong Soon Food Court","cn":"\\u65e9\\u5348\\u9910\\uff08\\u5916\\u5356\\uff09"}',
                'claim_item_created' => '2023-05-12 21:41:01',
                'claim_item_updated' => '2023-05-12 21:41:01',
                'claim_item_value' => '324.00',
                'claim_item_amount' => '324.00',
                'claim_item_amount_claim' => '324.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2328,
            ),
            59 => 
            array (
                'claim_item_id' => 1471,
                'claim_id' => 8,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"Tian Loong Food Court","cn":"\\u5348\\u9910"}',
                'claim_item_created' => '2023-05-12 21:41:02',
                'claim_item_updated' => '2023-05-12 21:41:02',
                'claim_item_value' => '462.80',
                'claim_item_amount' => '462.80',
                'claim_item_amount_claim' => '462.80',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2329,
            ),
            60 => 
            array (
                'claim_item_id' => 1472,
                'claim_id' => 9,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"Lai Wan Loong Hong Soon Food Court","cn":"\\u65e9\\u5348\\u9910\\uff08\\u5916\\u5356\\uff09"}',
                'claim_item_created' => '2023-05-12 21:41:02',
                'claim_item_updated' => '2023-05-12 21:41:02',
                'claim_item_value' => '1214.00',
                'claim_item_amount' => '1214.00',
                'claim_item_amount_claim' => '1214.00',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2330,
            ),
            61 => 
            array (
                'claim_item_id' => 1473,
                'claim_id' => 9,
                'claim_item_date' => '2023-01-29',
                'claim_item_name' => '{"en":"Tian Loong Food Court","cn":"\\u5348\\u9910"}',
                'claim_item_created' => '2023-05-12 21:41:03',
                'claim_item_updated' => '2023-05-12 21:41:03',
                'claim_item_value' => '683.50',
                'claim_item_amount' => '683.50',
                'claim_item_amount_claim' => '683.50',
                'is_deleted' => 0,
                'is_rejected' => 0,
                'claim_item_rejected_by' => 0,
                'claim_item_rejected_date' => NULL,
                'claim_item_rejected_remark' => '',
                'claim_item_type' => 'company_expense_item_id',
                'claim_item_type_value' => 2331,
            ),
        ));
        
        
    }
}