<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TblInvoiceItemTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_invoice_item')->delete();
        
        \DB::table('tbl_invoice_item')->insert(array (
            0 => 
            array (
                'invoice_item_id' => 1,
                'invoice_id' => 1,
                'product_id' => 1,
                'setting_product_size_id' => 7,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '2',
                'invoice_item_quantity' => '222.0000',
                'invoice_item_subtotal' => '444.00',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '444.00',
                'invoice_item_created' => '2022-07-25 16:37:13',
                'invoice_item_updated' => '2022-07-25 16:37:13',
                'delivery_order_item_id' => 0,
            ),
            1 => 
            array (
                'invoice_item_id' => 2,
                'invoice_id' => 1,
                'product_id' => 2,
                'setting_product_size_id' => 2,
                'invoice_item_name' => '101',
                'invoice_item_price' => '4',
                'invoice_item_quantity' => '50.0000',
                'invoice_item_subtotal' => '200.00',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '200.00',
                'invoice_item_created' => '2022-07-25 16:37:13',
                'invoice_item_updated' => '2022-07-25 16:37:13',
                'delivery_order_item_id' => 0,
            ),
            2 => 
            array (
                'invoice_item_id' => 36777,
                'invoice_id' => 7321,
                'product_id' => 2,
                'setting_product_size_id' => 4,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '35',
                'invoice_item_quantity' => '29.9000',
                'invoice_item_subtotal' => '1046.50',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '1046.50',
                'invoice_item_created' => '2023-08-23 16:50:16',
                'invoice_item_updated' => '2023-08-23 16:50:16',
                'delivery_order_item_id' => 0,
            ),
            3 => 
            array (
                'invoice_item_id' => 36801,
                'invoice_id' => 7325,
                'product_id' => 2,
                'setting_product_size_id' => 3,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '38.00',
                'invoice_item_quantity' => '4.6000',
                'invoice_item_subtotal' => '174.80',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '174.80',
                'invoice_item_created' => '2023-08-23 21:07:07',
                'invoice_item_updated' => '2023-08-23 21:07:07',
                'delivery_order_item_id' => 0,
            ),
            4 => 
            array (
                'invoice_item_id' => 36802,
                'invoice_id' => 7325,
                'product_id' => 2,
                'setting_product_size_id' => 4,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '31.00',
                'invoice_item_quantity' => '7.0000',
                'invoice_item_subtotal' => '217.00',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '217.00',
                'invoice_item_created' => '2023-08-23 21:07:07',
                'invoice_item_updated' => '2023-08-23 21:07:07',
                'delivery_order_item_id' => 0,
            ),
            5 => 
            array (
                'invoice_item_id' => 36803,
                'invoice_id' => 7325,
                'product_id' => 2,
                'setting_product_size_id' => 7,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '16.00',
                'invoice_item_quantity' => '5.7500',
                'invoice_item_subtotal' => '92.00',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '92.00',
                'invoice_item_created' => '2023-08-23 21:07:07',
                'invoice_item_updated' => '2023-08-23 21:07:07',
                'delivery_order_item_id' => 0,
            ),
            6 => 
            array (
                'invoice_item_id' => 36804,
                'invoice_id' => 7325,
                'product_id' => 2,
                'setting_product_size_id' => 9,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '9.00',
                'invoice_item_quantity' => '3.7500',
                'invoice_item_subtotal' => '33.75',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '33.75',
                'invoice_item_created' => '2023-08-23 21:07:07',
                'invoice_item_updated' => '2023-08-23 21:07:07',
                'delivery_order_item_id' => 0,
            ),
            7 => 
            array (
                'invoice_item_id' => 36805,
                'invoice_id' => 7325,
                'product_id' => 4,
                'setting_product_size_id' => 2,
                'invoice_item_name' => 'Tekka 竹脚',
                'invoice_item_price' => '18.00',
                'invoice_item_quantity' => '2.3500',
                'invoice_item_subtotal' => '42.30',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '42.30',
                'invoice_item_created' => '2023-08-23 21:07:07',
                'invoice_item_updated' => '2023-08-23 21:07:07',
                'delivery_order_item_id' => 0,
            ),
            8 => 
            array (
                'invoice_item_id' => 36806,
                'invoice_id' => 7325,
                'product_id' => 7,
                'setting_product_size_id' => 3,
                'invoice_item_name' => 'D24',
                'invoice_item_price' => '7.00',
                'invoice_item_quantity' => '8.7500',
                'invoice_item_subtotal' => '61.25',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '61.25',
                'invoice_item_created' => '2023-08-23 21:07:07',
                'invoice_item_updated' => '2023-08-23 21:07:07',
                'delivery_order_item_id' => 0,
            ),
            9 => 
            array (
                'invoice_item_id' => 36807,
                'invoice_id' => 7325,
                'product_id' => 1,
                'setting_product_size_id' => 7,
                'invoice_item_name' => 'ZAI',
                'invoice_item_price' => '2.00',
                'invoice_item_quantity' => '16.7500',
                'invoice_item_subtotal' => '33.50',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '33.50',
                'invoice_item_created' => '2023-08-23 21:07:07',
                'invoice_item_updated' => '2023-08-23 21:07:07',
                'delivery_order_item_id' => 0,
            ),
            10 => 
            array (
                'invoice_item_id' => 36886,
                'invoice_id' => 7340,
                'product_id' => 2,
                'setting_product_size_id' => 10,
                'invoice_item_name' => 'FG 废果',
                'invoice_item_price' => '0.7',
                'invoice_item_quantity' => '46.4000',
                'invoice_item_subtotal' => '32.48',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '32.48',
                'invoice_item_created' => '2023-08-24 14:54:04',
                'invoice_item_updated' => '2023-08-24 14:54:04',
                'delivery_order_item_id' => 0,
            ),
            11 => 
            array (
                'invoice_item_id' => 36909,
                'invoice_id' => 7344,
                'product_id' => 1,
                'setting_product_size_id' => 2,
                'invoice_item_name' => 'Black Thon 黑刺',
                'invoice_item_price' => '65',
                'invoice_item_quantity' => '3.7500',
                'invoice_item_subtotal' => '243.75',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '243.75',
                'invoice_item_created' => '2023-08-24 15:13:12',
                'invoice_item_updated' => '2023-08-24 15:13:12',
                'delivery_order_item_id' => 0,
            ),
            12 => 
            array (
                'invoice_item_id' => 36910,
                'invoice_id' => 7344,
                'product_id' => 1,
                'setting_product_size_id' => 4,
                'invoice_item_name' => 'Black Thon 黑刺',
                'invoice_item_price' => '32',
                'invoice_item_quantity' => '2.3000',
                'invoice_item_subtotal' => '73.60',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '73.60',
                'invoice_item_created' => '2023-08-24 15:13:12',
                'invoice_item_updated' => '2023-08-24 15:13:12',
                'delivery_order_item_id' => 0,
            ),
            13 => 
            array (
                'invoice_item_id' => 36930,
                'invoice_id' => 7347,
                'product_id' => 2,
                'setting_product_size_id' => 4,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '31.00',
                'invoice_item_quantity' => '5.1500',
                'invoice_item_subtotal' => '159.65',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '159.65',
                'invoice_item_created' => '2023-08-24 16:56:58',
                'invoice_item_updated' => '2023-08-24 16:56:58',
                'delivery_order_item_id' => 0,
            ),
            14 => 
            array (
                'invoice_item_id' => 36931,
                'invoice_id' => 7347,
                'product_id' => 2,
                'setting_product_size_id' => 7,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '16.00',
                'invoice_item_quantity' => '5.0500',
                'invoice_item_subtotal' => '80.80',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '80.80',
                'invoice_item_created' => '2023-08-24 16:56:58',
                'invoice_item_updated' => '2023-08-24 16:56:58',
                'delivery_order_item_id' => 0,
            ),
            15 => 
            array (
                'invoice_item_id' => 36932,
                'invoice_id' => 7347,
                'product_id' => 2,
                'setting_product_size_id' => 11,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '9.00',
                'invoice_item_quantity' => '8.1000',
                'invoice_item_subtotal' => '72.90',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '72.90',
                'invoice_item_created' => '2023-08-24 16:56:58',
                'invoice_item_updated' => '2023-08-24 16:56:58',
                'delivery_order_item_id' => 0,
            ),
            16 => 
            array (
                'invoice_item_id' => 36933,
                'invoice_id' => 7347,
                'product_id' => 4,
                'setting_product_size_id' => 4,
                'invoice_item_name' => 'Tekka 竹脚',
                'invoice_item_price' => '10.00',
                'invoice_item_quantity' => '2.0000',
                'invoice_item_subtotal' => '20.00',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '20.00',
                'invoice_item_created' => '2023-08-24 16:56:59',
                'invoice_item_updated' => '2023-08-24 16:56:59',
                'delivery_order_item_id' => 0,
            ),
            17 => 
            array (
                'invoice_item_id' => 36934,
                'invoice_id' => 7347,
                'product_id' => 7,
                'setting_product_size_id' => 3,
                'invoice_item_name' => 'D24',
                'invoice_item_price' => '7.00',
                'invoice_item_quantity' => '20.7500',
                'invoice_item_subtotal' => '145.25',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '145.25',
                'invoice_item_created' => '2023-08-24 16:56:59',
                'invoice_item_updated' => '2023-08-24 16:56:59',
                'delivery_order_item_id' => 0,
            ),
            18 => 
            array (
                'invoice_item_id' => 36935,
                'invoice_id' => 7347,
                'product_id' => 4,
                'setting_product_size_id' => 7,
                'invoice_item_name' => 'ZAI',
                'invoice_item_price' => '2.00',
                'invoice_item_quantity' => '15.8000',
                'invoice_item_subtotal' => '31.60',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '31.60',
                'invoice_item_created' => '2023-08-24 16:56:59',
                'invoice_item_updated' => '2023-08-24 16:56:59',
                'delivery_order_item_id' => 0,
            ),
            19 => 
            array (
                'invoice_item_id' => 36936,
                'invoice_id' => 7348,
                'product_id' => 2,
                'setting_product_size_id' => 2,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '47.00',
                'invoice_item_quantity' => '2.0200',
                'invoice_item_subtotal' => '94.94',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '94.94',
                'invoice_item_created' => '2023-08-25 08:06:23',
                'invoice_item_updated' => '2023-08-25 08:06:23',
                'delivery_order_item_id' => 0,
            ),
            20 => 
            array (
                'invoice_item_id' => 36937,
                'invoice_id' => 7348,
                'product_id' => 2,
                'setting_product_size_id' => 4,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '28.00',
                'invoice_item_quantity' => '10.6800',
                'invoice_item_subtotal' => '299.04',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '299.04',
                'invoice_item_created' => '2023-08-25 08:06:23',
                'invoice_item_updated' => '2023-08-25 08:06:23',
                'delivery_order_item_id' => 0,
            ),
            21 => 
            array (
                'invoice_item_id' => 36938,
                'invoice_id' => 7348,
                'product_id' => 2,
                'setting_product_size_id' => 7,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '15.00',
                'invoice_item_quantity' => '31.5000',
                'invoice_item_subtotal' => '472.50',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '472.50',
                'invoice_item_created' => '2023-08-25 08:06:23',
                'invoice_item_updated' => '2023-08-25 08:06:23',
                'delivery_order_item_id' => 0,
            ),
            22 => 
            array (
                'invoice_item_id' => 36939,
                'invoice_id' => 7348,
                'product_id' => 2,
                'setting_product_size_id' => 11,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '7.00',
                'invoice_item_quantity' => '27.0800',
                'invoice_item_subtotal' => '189.56',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '189.56',
                'invoice_item_created' => '2023-08-25 08:06:23',
                'invoice_item_updated' => '2023-08-25 08:06:23',
                'delivery_order_item_id' => 0,
            ),
            23 => 
            array (
                'invoice_item_id' => 36940,
                'invoice_id' => 7348,
                'product_id' => 1,
                'setting_product_size_id' => 2,
                'invoice_item_name' => '101',
                'invoice_item_price' => '16.00',
                'invoice_item_quantity' => '3.3600',
                'invoice_item_subtotal' => '53.76',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '53.76',
                'invoice_item_created' => '2023-08-25 08:06:23',
                'invoice_item_updated' => '2023-08-25 08:06:23',
                'delivery_order_item_id' => 0,
            ),
            24 => 
            array (
                'invoice_item_id' => 36941,
                'invoice_id' => 7348,
                'product_id' => 4,
                'setting_product_size_id' => 2,
                'invoice_item_name' => 'Tekka 竹脚',
                'invoice_item_price' => '16.00',
                'invoice_item_quantity' => '1.5000',
                'invoice_item_subtotal' => '24.00',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '24.00',
                'invoice_item_created' => '2023-08-25 08:06:23',
                'invoice_item_updated' => '2023-08-25 08:06:23',
                'delivery_order_item_id' => 0,
            ),
            25 => 
            array (
                'invoice_item_id' => 36942,
                'invoice_id' => 7348,
                'product_id' => 4,
                'setting_product_size_id' => 4,
                'invoice_item_name' => 'Tekka 竹脚',
                'invoice_item_price' => '9.00',
                'invoice_item_quantity' => '4.2000',
                'invoice_item_subtotal' => '37.80',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '37.80',
                'invoice_item_created' => '2023-08-25 08:06:23',
                'invoice_item_updated' => '2023-08-25 08:06:23',
                'delivery_order_item_id' => 0,
            ),
            26 => 
            array (
                'invoice_item_id' => 36943,
                'invoice_id' => 7348,
                'product_id' => 7,
                'setting_product_size_id' => 2,
                'invoice_item_name' => 'D24',
                'invoice_item_price' => '9.50',
                'invoice_item_quantity' => '23.1600',
                'invoice_item_subtotal' => '220.02',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '220.02',
                'invoice_item_created' => '2023-08-25 08:06:23',
                'invoice_item_updated' => '2023-08-25 08:06:23',
                'delivery_order_item_id' => 0,
            ),
            27 => 
            array (
                'invoice_item_id' => 36944,
                'invoice_id' => 7348,
                'product_id' => 7,
                'setting_product_size_id' => 4,
                'invoice_item_name' => 'D24',
                'invoice_item_price' => '6.00',
                'invoice_item_quantity' => '55.9000',
                'invoice_item_subtotal' => '335.40',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '335.40',
                'invoice_item_created' => '2023-08-25 08:06:23',
                'invoice_item_updated' => '2023-08-25 08:06:23',
                'delivery_order_item_id' => 0,
            ),
            28 => 
            array (
                'invoice_item_id' => 36945,
                'invoice_id' => 7348,
                'product_id' => 7,
                'setting_product_size_id' => 7,
                'invoice_item_name' => 'D24',
                'invoice_item_price' => '2.00',
                'invoice_item_quantity' => '151.3800',
                'invoice_item_subtotal' => '302.76',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '302.76',
                'invoice_item_created' => '2023-08-25 08:06:23',
                'invoice_item_updated' => '2023-08-25 08:06:23',
                'delivery_order_item_id' => 0,
            ),
            29 => 
            array (
                'invoice_item_id' => 36946,
                'invoice_id' => 7348,
                'product_id' => 9,
                'setting_product_size_id' => 2,
                'invoice_item_name' => 'KUN 坤',
                'invoice_item_price' => '7.00',
                'invoice_item_quantity' => '13.7600',
                'invoice_item_subtotal' => '96.32',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '96.32',
                'invoice_item_created' => '2023-08-25 08:06:23',
                'invoice_item_updated' => '2023-08-25 08:06:23',
                'delivery_order_item_id' => 0,
            ),
            30 => 
            array (
                'invoice_item_id' => 36947,
                'invoice_id' => 7348,
                'product_id' => 9,
                'setting_product_size_id' => 4,
                'invoice_item_name' => 'KUN 坤',
                'invoice_item_price' => '5.00',
                'invoice_item_quantity' => '27.2200',
                'invoice_item_subtotal' => '136.10',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '136.10',
                'invoice_item_created' => '2023-08-25 08:06:23',
                'invoice_item_updated' => '2023-08-25 08:06:23',
                'delivery_order_item_id' => 0,
            ),
            31 => 
            array (
                'invoice_item_id' => 36958,
                'invoice_id' => 7351,
                'product_id' => 2,
                'setting_product_size_id' => 7,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '18',
                'invoice_item_quantity' => '2.8000',
                'invoice_item_subtotal' => '50.40',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '50.40',
                'invoice_item_created' => '2023-08-25 12:25:45',
                'invoice_item_updated' => '2023-08-25 12:25:45',
                'delivery_order_item_id' => 0,
            ),
            32 => 
            array (
                'invoice_item_id' => 36959,
                'invoice_id' => 7351,
                'product_id' => 2,
                'setting_product_size_id' => 11,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '10.00',
                'invoice_item_quantity' => '1.6000',
                'invoice_item_subtotal' => '16.00',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '16.00',
                'invoice_item_created' => '2023-08-25 12:25:45',
                'invoice_item_updated' => '2023-08-25 12:25:45',
                'delivery_order_item_id' => 0,
            ),
            33 => 
            array (
                'invoice_item_id' => 36960,
                'invoice_id' => 7351,
                'product_id' => 7,
                'setting_product_size_id' => 3,
                'invoice_item_name' => 'D24',
                'invoice_item_price' => '8',
                'invoice_item_quantity' => '2.9000',
                'invoice_item_subtotal' => '23.20',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '23.20',
                'invoice_item_created' => '2023-08-25 12:25:45',
                'invoice_item_updated' => '2023-08-25 12:25:45',
                'delivery_order_item_id' => 0,
            ),
            34 => 
            array (
                'invoice_item_id' => 36961,
                'invoice_id' => 7351,
                'product_id' => 11,
                'setting_product_size_id' => 7,
                'invoice_item_name' => 'ZAI',
                'invoice_item_price' => '3',
                'invoice_item_quantity' => '4.2000',
                'invoice_item_subtotal' => '12.60',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '12.60',
                'invoice_item_created' => '2023-08-25 12:25:45',
                'invoice_item_updated' => '2023-08-25 12:25:45',
                'delivery_order_item_id' => 0,
            ),
            35 => 
            array (
                'invoice_item_id' => 36962,
                'invoice_id' => 7352,
                'product_id' => 2,
                'setting_product_size_id' => 4,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '32',
                'invoice_item_quantity' => '9.6000',
                'invoice_item_subtotal' => '307.20',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '307.20',
                'invoice_item_created' => '2023-08-25 12:28:16',
                'invoice_item_updated' => '2023-08-25 12:28:16',
                'delivery_order_item_id' => 0,
            ),
            36 => 
            array (
                'invoice_item_id' => 36963,
                'invoice_id' => 7352,
                'product_id' => 2,
                'setting_product_size_id' => 7,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '18',
                'invoice_item_quantity' => '2.3000',
                'invoice_item_subtotal' => '41.40',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '41.40',
                'invoice_item_created' => '2023-08-25 12:28:16',
                'invoice_item_updated' => '2023-08-25 12:28:16',
                'delivery_order_item_id' => 0,
            ),
            37 => 
            array (
                'invoice_item_id' => 36964,
                'invoice_id' => 7352,
                'product_id' => 2,
                'setting_product_size_id' => 11,
                'invoice_item_name' => 'Musang',
                'invoice_item_price' => '10',
                'invoice_item_quantity' => '2.7000',
                'invoice_item_subtotal' => '27.00',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '27.00',
                'invoice_item_created' => '2023-08-25 12:28:16',
                'invoice_item_updated' => '2023-08-25 12:28:16',
                'delivery_order_item_id' => 0,
            ),
            38 => 
            array (
                'invoice_item_id' => 36965,
                'invoice_id' => 7352,
                'product_id' => 7,
                'setting_product_size_id' => 2,
                'invoice_item_name' => 'D24',
                'invoice_item_price' => '8',
                'invoice_item_quantity' => '1.2000',
                'invoice_item_subtotal' => '9.60',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '9.60',
                'invoice_item_created' => '2023-08-25 12:28:17',
                'invoice_item_updated' => '2023-08-25 12:28:17',
                'delivery_order_item_id' => 0,
            ),
            39 => 
            array (
                'invoice_item_id' => 36966,
                'invoice_id' => 7352,
                'product_id' => 10,
                'setting_product_size_id' => 2,
                'invoice_item_name' => 'Kampung',
                'invoice_item_price' => '5',
                'invoice_item_quantity' => '7.9000',
                'invoice_item_subtotal' => '39.50',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '39.50',
                'invoice_item_created' => '2023-08-25 12:28:17',
                'invoice_item_updated' => '2023-08-25 12:28:17',
                'delivery_order_item_id' => 0,
            ),
            40 => 
            array (
                'invoice_item_id' => 36967,
                'invoice_id' => 7352,
                'product_id' => 4,
                'setting_product_size_id' => 7,
                'invoice_item_name' => 'ZAI',
                'invoice_item_price' => '3',
                'invoice_item_quantity' => '2.5000',
                'invoice_item_subtotal' => '7.50',
                'invoice_item_discount' => '0.00',
                'invoice_item_total' => '7.50',
                'invoice_item_created' => '2023-08-25 12:28:17',
                'invoice_item_updated' => '2023-08-25 12:28:17',
                'delivery_order_item_id' => 0,
            ),
        ));
        
        
    }
}