<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TblProductStockTransferTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_product_stock_transfer')->delete();
        
        \DB::table('tbl_product_stock_transfer')->insert(array (
            0 => 
            array (
                'product_stock_transfer_id' => 7874,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74260 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -70292,
                'product_stock_transfer_qty_after' => -70348,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:42:11',
                'product_stock_transfer_created' => '2023-03-30 16:42:11',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            1 => 
            array (
                'product_stock_transfer_id' => 7875,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74261 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -70348,
                'product_stock_transfer_qty_after' => -70404,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:42:19',
                'product_stock_transfer_created' => '2023-03-30 16:42:19',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            2 => 
            array (
                'product_stock_transfer_id' => 7876,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74262 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -70404,
                'product_stock_transfer_qty_after' => -70460,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:42:27',
                'product_stock_transfer_created' => '2023-03-30 16:42:27',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            3 => 
            array (
                'product_stock_transfer_id' => 7877,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74263 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -70460,
                'product_stock_transfer_qty_after' => -70516,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:42:36',
                'product_stock_transfer_created' => '2023-03-30 16:42:36',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            4 => 
            array (
                'product_stock_transfer_id' => 7878,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74264 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -70516,
                'product_stock_transfer_qty_after' => -70572,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:42:45',
                'product_stock_transfer_created' => '2023-03-30 16:42:45',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            5 => 
            array (
                'product_stock_transfer_id' => 7879,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74265 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -70572,
                'product_stock_transfer_qty_after' => -70628,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:42:54',
                'product_stock_transfer_created' => '2023-03-30 16:42:54',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            6 => 
            array (
                'product_stock_transfer_id' => 7880,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74266 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -70628,
                'product_stock_transfer_qty_after' => -70684,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:43:03',
                'product_stock_transfer_created' => '2023-03-30 16:43:03',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            7 => 
            array (
                'product_stock_transfer_id' => 7881,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74267 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -70684,
                'product_stock_transfer_qty_after' => -70740,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:43:13',
                'product_stock_transfer_created' => '2023-03-30 16:43:13',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            8 => 
            array (
                'product_stock_transfer_id' => 7882,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74268 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -70740,
                'product_stock_transfer_qty_after' => -70796,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:43:22',
                'product_stock_transfer_created' => '2023-03-30 16:43:22',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            9 => 
            array (
                'product_stock_transfer_id' => 7883,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74269 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -70796,
                'product_stock_transfer_qty_after' => -70852,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:43:31',
                'product_stock_transfer_created' => '2023-03-30 16:43:31',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            10 => 
            array (
                'product_stock_transfer_id' => 7884,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74270 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -70852,
                'product_stock_transfer_qty_after' => -70908,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:43:40',
                'product_stock_transfer_created' => '2023-03-30 16:43:40',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            11 => 
            array (
                'product_stock_transfer_id' => 7885,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74271 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -70908,
                'product_stock_transfer_qty_after' => -70964,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:43:49',
                'product_stock_transfer_created' => '2023-03-30 16:43:49',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            12 => 
            array (
                'product_stock_transfer_id' => 7886,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74272 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -70964,
                'product_stock_transfer_qty_after' => -71020,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:43:58',
                'product_stock_transfer_created' => '2023-03-30 16:43:58',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            13 => 
            array (
                'product_stock_transfer_id' => 7887,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74273 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71020,
                'product_stock_transfer_qty_after' => -71076,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:44:08',
                'product_stock_transfer_created' => '2023-03-30 16:44:08',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            14 => 
            array (
                'product_stock_transfer_id' => 7888,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74274 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71076,
                'product_stock_transfer_qty_after' => -71132,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:44:18',
                'product_stock_transfer_created' => '2023-03-30 16:44:18',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            15 => 
            array (
                'product_stock_transfer_id' => 7889,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74275 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71132,
                'product_stock_transfer_qty_after' => -71188,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:44:27',
                'product_stock_transfer_created' => '2023-03-30 16:44:27',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            16 => 
            array (
                'product_stock_transfer_id' => 7890,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74276 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71188,
                'product_stock_transfer_qty_after' => -71244,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:44:36',
                'product_stock_transfer_created' => '2023-03-30 16:44:36',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            17 => 
            array (
                'product_stock_transfer_id' => 7891,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74277 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71244,
                'product_stock_transfer_qty_after' => -71300,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:44:45',
                'product_stock_transfer_created' => '2023-03-30 16:44:45',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            18 => 
            array (
                'product_stock_transfer_id' => 7892,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74278 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71300,
                'product_stock_transfer_qty_after' => -71356,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:44:54',
                'product_stock_transfer_created' => '2023-03-30 16:44:54',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            19 => 
            array (
                'product_stock_transfer_id' => 7893,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74279 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71356,
                'product_stock_transfer_qty_after' => -71412,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:45:04',
                'product_stock_transfer_created' => '2023-03-30 16:45:04',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            20 => 
            array (
                'product_stock_transfer_id' => 7894,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74280 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71412,
                'product_stock_transfer_qty_after' => -71468,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:45:13',
                'product_stock_transfer_created' => '2023-03-30 16:45:13',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            21 => 
            array (
                'product_stock_transfer_id' => 7895,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74281 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71468,
                'product_stock_transfer_qty_after' => -71524,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:45:22',
                'product_stock_transfer_created' => '2023-03-30 16:45:22',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            22 => 
            array (
                'product_stock_transfer_id' => 7896,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74282 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71524,
                'product_stock_transfer_qty_after' => -71580,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:45:31',
                'product_stock_transfer_created' => '2023-03-30 16:45:31',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            23 => 
            array (
                'product_stock_transfer_id' => 7897,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74283 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71580,
                'product_stock_transfer_qty_after' => -71636,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:45:40',
                'product_stock_transfer_created' => '2023-03-30 16:45:40',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            24 => 
            array (
                'product_stock_transfer_id' => 7898,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74284 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71636,
                'product_stock_transfer_qty_after' => -71692,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:45:50',
                'product_stock_transfer_created' => '2023-03-30 16:45:50',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            25 => 
            array (
                'product_stock_transfer_id' => 7899,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74285 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71692,
                'product_stock_transfer_qty_after' => -71748,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:45:59',
                'product_stock_transfer_created' => '2023-03-30 16:45:59',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            26 => 
            array (
                'product_stock_transfer_id' => 7900,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74286 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71748,
                'product_stock_transfer_qty_after' => -71804,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:46:08',
                'product_stock_transfer_created' => '2023-03-30 16:46:08',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            27 => 
            array (
                'product_stock_transfer_id' => 7901,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74287 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71804,
                'product_stock_transfer_qty_after' => -71860,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:46:17',
                'product_stock_transfer_created' => '2023-03-30 16:46:17',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            28 => 
            array (
                'product_stock_transfer_id' => 7902,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74288 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71860,
                'product_stock_transfer_qty_after' => -71916,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:46:27',
                'product_stock_transfer_created' => '2023-03-30 16:46:27',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            29 => 
            array (
                'product_stock_transfer_id' => 7903,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74289 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71916,
                'product_stock_transfer_qty_after' => -71972,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:46:36',
                'product_stock_transfer_created' => '2023-03-30 16:46:36',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            30 => 
            array (
                'product_stock_transfer_id' => 7904,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74290 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -71972,
                'product_stock_transfer_qty_after' => -72028,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:46:46',
                'product_stock_transfer_created' => '2023-03-30 16:46:46',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            31 => 
            array (
                'product_stock_transfer_id' => 7905,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74291 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72028,
                'product_stock_transfer_qty_after' => -72084,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:46:55',
                'product_stock_transfer_created' => '2023-03-30 16:46:55',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            32 => 
            array (
                'product_stock_transfer_id' => 7906,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74292 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72084,
                'product_stock_transfer_qty_after' => -72140,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:47:05',
                'product_stock_transfer_created' => '2023-03-30 16:47:05',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            33 => 
            array (
                'product_stock_transfer_id' => 7907,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74293 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72140,
                'product_stock_transfer_qty_after' => -72196,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:47:14',
                'product_stock_transfer_created' => '2023-03-30 16:47:14',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            34 => 
            array (
                'product_stock_transfer_id' => 7908,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74294 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72196,
                'product_stock_transfer_qty_after' => -72252,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:47:23',
                'product_stock_transfer_created' => '2023-03-30 16:47:23',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            35 => 
            array (
                'product_stock_transfer_id' => 7909,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74295 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72252,
                'product_stock_transfer_qty_after' => -72308,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:47:32',
                'product_stock_transfer_created' => '2023-03-30 16:47:32',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            36 => 
            array (
                'product_stock_transfer_id' => 7910,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74296 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72308,
                'product_stock_transfer_qty_after' => -72364,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:47:41',
                'product_stock_transfer_created' => '2023-03-30 16:47:41',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            37 => 
            array (
                'product_stock_transfer_id' => 7911,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74297 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72364,
                'product_stock_transfer_qty_after' => -72420,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:47:50',
                'product_stock_transfer_created' => '2023-03-30 16:47:50',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            38 => 
            array (
                'product_stock_transfer_id' => 7912,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74298 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72420,
                'product_stock_transfer_qty_after' => -72476,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:47:59',
                'product_stock_transfer_created' => '2023-03-30 16:47:59',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            39 => 
            array (
                'product_stock_transfer_id' => 7913,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74299 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72476,
                'product_stock_transfer_qty_after' => -72532,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:48:09',
                'product_stock_transfer_created' => '2023-03-30 16:48:09',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            40 => 
            array (
                'product_stock_transfer_id' => 7914,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74300 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72532,
                'product_stock_transfer_qty_after' => -72588,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:48:19',
                'product_stock_transfer_created' => '2023-03-30 16:48:19',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            41 => 
            array (
                'product_stock_transfer_id' => 7915,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74301 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72588,
                'product_stock_transfer_qty_after' => -72644,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:48:28',
                'product_stock_transfer_created' => '2023-03-30 16:48:28',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            42 => 
            array (
                'product_stock_transfer_id' => 7916,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74302 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72644,
                'product_stock_transfer_qty_after' => -72700,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:48:37',
                'product_stock_transfer_created' => '2023-03-30 16:48:37',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            43 => 
            array (
                'product_stock_transfer_id' => 7917,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74303 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72700,
                'product_stock_transfer_qty_after' => -72756,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:48:47',
                'product_stock_transfer_created' => '2023-03-30 16:48:47',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            44 => 
            array (
                'product_stock_transfer_id' => 7918,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74304 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72756,
                'product_stock_transfer_qty_after' => -72812,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:48:56',
                'product_stock_transfer_created' => '2023-03-30 16:48:56',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            45 => 
            array (
                'product_stock_transfer_id' => 7919,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74305 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72812,
                'product_stock_transfer_qty_after' => -72868,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:49:05',
                'product_stock_transfer_created' => '2023-03-30 16:49:05',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            46 => 
            array (
                'product_stock_transfer_id' => 7920,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74306 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72868,
                'product_stock_transfer_qty_after' => -72924,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:49:15',
                'product_stock_transfer_created' => '2023-03-30 16:49:15',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            47 => 
            array (
                'product_stock_transfer_id' => 7921,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74307 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72924,
                'product_stock_transfer_qty_after' => -72980,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:49:24',
                'product_stock_transfer_created' => '2023-03-30 16:49:24',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            48 => 
            array (
                'product_stock_transfer_id' => 7922,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74308 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -72980,
                'product_stock_transfer_qty_after' => -73036,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:49:34',
                'product_stock_transfer_created' => '2023-03-30 16:49:34',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            49 => 
            array (
                'product_stock_transfer_id' => 7923,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74309 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -73036,
                'product_stock_transfer_qty_after' => -73092,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:49:43',
                'product_stock_transfer_created' => '2023-03-30 16:49:43',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            50 => 
            array (
                'product_stock_transfer_id' => 7924,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74310 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -73092,
                'product_stock_transfer_qty_after' => -73148,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:49:52',
                'product_stock_transfer_created' => '2023-03-30 16:49:52',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            51 => 
            array (
                'product_stock_transfer_id' => 7925,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74311 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -73148,
                'product_stock_transfer_qty_after' => -73204,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:50:01',
                'product_stock_transfer_created' => '2023-03-30 16:50:01',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            52 => 
            array (
                'product_stock_transfer_id' => 7926,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74312 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -73204,
                'product_stock_transfer_qty_after' => -73260,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:50:11',
                'product_stock_transfer_created' => '2023-03-30 16:50:11',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            53 => 
            array (
                'product_stock_transfer_id' => 7927,
                'product_stock_transfer_description' => 'Transfer from Delivery Order',
                'product_stock_transfer_remark' => 'Item #74313 has been transfer to warehouse #',
                'product_stock_transfer_qty' => 56,
                'product_stock_transfer_qty_before' => -73260,
                'product_stock_transfer_qty_after' => -73316,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 3,
                'product_stock_transfer_updated' => '2023-03-30 16:50:18',
                'product_stock_transfer_created' => '2023-03-30 16:50:18',
                'setting_product_size_id' => 3,
                'product_id' => 2,
            ),
            54 => 
            array (
                'product_stock_transfer_id' => 7928,
                'product_stock_transfer_description' => '#DO/NMP/LCY/23010030',
                'product_stock_transfer_remark' => 'Transfer',
                'product_stock_transfer_qty' => 34,
                'product_stock_transfer_qty_before' => 2863,
                'product_stock_transfer_qty_after' => 2897,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 21,
                'product_stock_transfer_updated' => '2023-05-26 15:07:04',
                'product_stock_transfer_created' => '2023-05-26 15:07:04',
                'setting_product_size_id' => 2,
                'product_id' => 2,
            ),
            55 => 
            array (
                'product_stock_transfer_id' => 7929,
                'product_stock_transfer_description' => '#DO/NMP/LCY/23010030',
                'product_stock_transfer_remark' => 'Transfer',
                'product_stock_transfer_qty' => 0,
                'product_stock_transfer_qty_before' => 2897,
                'product_stock_transfer_qty_after' => 2897,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 21,
                'product_stock_transfer_updated' => '2023-05-26 15:07:04',
                'product_stock_transfer_created' => '2023-05-26 15:07:04',
                'setting_product_size_id' => 2,
                'product_id' => 2,
            ),
            56 => 
            array (
                'product_stock_transfer_id' => 7930,
                'product_stock_transfer_description' => '#DO/NMP/LCY/23010030',
                'product_stock_transfer_remark' => 'Transfer',
                'product_stock_transfer_qty' => 0,
                'product_stock_transfer_qty_before' => 2897,
                'product_stock_transfer_qty_after' => 2897,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 21,
                'product_stock_transfer_updated' => '2023-05-26 15:07:04',
                'product_stock_transfer_created' => '2023-05-26 15:07:04',
                'setting_product_size_id' => 2,
                'product_id' => 2,
            ),
            57 => 
            array (
                'product_stock_transfer_id' => 7931,
                'product_stock_transfer_description' => '#DO/NMP/LCY/23010030',
                'product_stock_transfer_remark' => 'Transfer',
                'product_stock_transfer_qty' => 0,
                'product_stock_transfer_qty_before' => 2897,
                'product_stock_transfer_qty_after' => 2897,
                'product_stock_transfer_status' => NULL,
                'product_stock_transfer_action' => NULL,
                'product_stock_warehouse_id' => 21,
                'product_stock_transfer_updated' => '2023-05-26 15:07:04',
                'product_stock_transfer_created' => '2023-05-26 15:07:04',
                'setting_product_size_id' => 2,
                'product_id' => 2,
            ),
        ));
        
        
    }
}