<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TblProductTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_product')->delete();
        
        \DB::table('tbl_product')->insert(array (
            0 => 
            array (
                'product_id' => 1,
                'product_name' => 'Musang',
                'product_remarks' => '',
                'product_description' => 'Musang',
                'product_sku' => 'musang',
                'is_deleted' => 0,
                'product_created' => '2022-02-26 12:04:47',
                'product_updated' => '2022-03-08 18:11:29',
                'product_slug' => 'musang',
                'product_status_id' => 2,
                'product_ranking' => 2,
                'product_category_id' => 1,
                'company_id' => 1,
            ),
            1 => 
            array (
                'product_id' => 2,
                'product_name' => '101',
                'product_remarks' => '',
                'product_description' => '101',
                'product_sku' => '101',
                'is_deleted' => 0,
                'product_created' => '2022-02-26 12:05:20',
                'product_updated' => '2022-03-08 18:11:58',
                'product_slug' => '101',
                'product_status_id' => 2,
                'product_ranking' => 3,
                'product_category_id' => 2,
                'company_id' => NULL,
            ),
            2 => 
            array (
                'product_id' => 4,
                'product_name' => 'Tekka 竹脚',
                'product_remarks' => '',
                'product_description' => 'Tekka&nbsp;竹脚',
                'product_sku' => 'tekka-xo',
                'is_deleted' => 0,
                'product_created' => '2022-02-26 12:06:28',
                'product_updated' => '2022-03-08 18:16:12',
                'product_slug' => 'tekka',
                'product_status_id' => 2,
                'product_ranking' => 3,
                'product_category_id' => 2,
                'company_id' => NULL,
            ),
            3 => 
            array (
                'product_id' => 5,
                'product_name' => 'D13',
                'product_remarks' => '',
                'product_description' => 'd13',
                'product_sku' => 'd13',
                'is_deleted' => 0,
                'product_created' => '2022-02-26 12:07:03',
                'product_updated' => '2022-03-08 18:12:19',
                'product_slug' => 'd13',
                'product_status_id' => 2,
                'product_ranking' => 4,
                'product_category_id' => 3,
                'company_id' => NULL,
            ),
            4 => 
            array (
                'product_id' => 6,
                'product_name' => 'KIM FONG 金凤',
                'product_remarks' => '',
                'product_description' => 'Kim Fong&nbsp;金凤',
                'product_sku' => 'kim-fong',
                'is_deleted' => 0,
                'product_created' => '2022-02-26 12:07:51',
                'product_updated' => '2022-03-13 19:38:06',
                'product_slug' => 'kim-fong',
                'product_status_id' => 2,
                'product_ranking' => 3,
                'product_category_id' => 2,
                'company_id' => NULL,
            ),
            5 => 
            array (
                'product_id' => 7,
                'product_name' => 'D24',
                'product_remarks' => '',
                'product_description' => 'd24',
                'product_sku' => 'd24',
                'is_deleted' => 0,
                'product_created' => '2022-02-26 12:08:19',
                'product_updated' => '2022-03-08 18:13:57',
                'product_slug' => 'd24',
                'product_status_id' => 2,
                'product_ranking' => 4,
                'product_category_id' => 3,
                'company_id' => NULL,
            ),
            6 => 
            array (
                'product_id' => 8,
                'product_name' => 'D2',
                'product_remarks' => '',
                'product_description' => 'D2&nbsp;',
                'product_sku' => 'd2-g-puteri',
                'is_deleted' => 0,
                'product_created' => '2022-02-26 12:09:14',
                'product_updated' => '2022-03-08 18:14:08',
                'product_slug' => 'd2',
                'product_status_id' => 2,
                'product_ranking' => 4,
                'product_category_id' => 3,
                'company_id' => NULL,
            ),
            7 => 
            array (
                'product_id' => 9,
                'product_name' => 'KUN 坤',
                'product_remarks' => '',
                'product_description' => 'KUN 坤&nbsp;',
                'product_sku' => 'kun-kappai',
                'is_deleted' => 0,
                'product_created' => '2022-02-26 12:10:10',
                'product_updated' => '2022-03-08 18:14:44',
                'product_slug' => 'kun',
                'product_status_id' => 2,
                'product_ranking' => 4,
                'product_category_id' => 3,
                'company_id' => NULL,
            ),
            8 => 
            array (
                'product_id' => 10,
                'product_name' => 'Kampung',
                'product_remarks' => '',
                'product_description' => 'Kampung',
                'product_sku' => 'kampung',
                'is_deleted' => 0,
                'product_created' => '2022-02-26 12:10:37',
                'product_updated' => '2022-03-08 18:13:41',
                'product_slug' => 'kampung',
                'product_status_id' => 2,
                'product_ranking' => 5,
                'product_category_id' => 4,
                'company_id' => NULL,
            ),
            9 => 
            array (
                'product_id' => 11,
                'product_name' => 'TPY',
                'product_remarks' => '',
                'product_description' => 'TPY',
                'product_sku' => 'tpy',
                'is_deleted' => 1,
                'product_created' => '2022-02-26 12:11:16',
                'product_updated' => '2022-10-26 19:15:55',
                'product_slug' => 'tpy',
                'product_status_id' => 2,
                'product_ranking' => 5,
                'product_category_id' => 4,
                'company_id' => NULL,
            ),
            10 => 
            array (
                'product_id' => 12,
                'product_name' => 'Mangosteen',
                'product_remarks' => '',
                'product_description' => 'Mangosteen',
                'product_sku' => 'mangosteen',
                'is_deleted' => 0,
                'product_created' => '2022-02-26 12:12:03',
                'product_updated' => '2022-03-08 18:13:18',
                'product_slug' => 'mangosteen',
                'product_status_id' => 2,
                'product_ranking' => 6,
                'product_category_id' => 5,
                'company_id' => NULL,
            ),
            11 => 
            array (
                'product_id' => 13,
                'product_name' => 'Tai Yuan 太原',
                'product_remarks' => '',
                'product_description' => '太原',
                'product_sku' => 'tai-yuan',
                'is_deleted' => 0,
                'product_created' => '2022-03-08 17:07:16',
                'product_updated' => '2022-03-08 18:13:05',
                'product_slug' => 'tai-yuan',
                'product_status_id' => 2,
                'product_ranking' => 4,
                'product_category_id' => 3,
                'company_id' => NULL,
            ),
            12 => 
            array (
                'product_id' => 14,
                'product_name' => 'Kaipai',
                'product_remarks' => '',
                'product_description' => 'Kaipai',
                'product_sku' => 'kaipai',
                'is_deleted' => 0,
                'product_created' => '2022-03-08 17:12:11',
                'product_updated' => '2022-03-08 18:12:54',
                'product_slug' => 'kaipai',
                'product_status_id' => 2,
                'product_ranking' => 4,
                'product_category_id' => 3,
                'company_id' => NULL,
            ),
            13 => 
            array (
                'product_id' => 15,
                'product_name' => 'Udang Merah 红虾',
                'product_remarks' => '',
                'product_description' => 'Udang Merah 红虾',
                'product_sku' => 'udang-merah-',
                'is_deleted' => 0,
                'product_created' => '2022-03-08 17:17:02',
                'product_updated' => '2022-03-08 18:12:44',
                'product_slug' => 'udang-merah',
                'product_status_id' => 2,
                'product_ranking' => 3,
                'product_category_id' => 2,
                'company_id' => NULL,
            ),
            14 => 
            array (
                'product_id' => 16,
                'product_name' => 'D13 半',
                'product_remarks' => '',
                'product_description' => 'D13 半',
                'product_sku' => 'D13 半',
                'is_deleted' => 0,
                'product_created' => '2022-03-08 17:18:19',
                'product_updated' => '2022-03-08 18:10:19',
                'product_slug' => 'd13-1',
                'product_status_id' => 2,
                'product_ranking' => 3,
                'product_category_id' => 3,
                'company_id' => NULL,
            ),
            15 => 
            array (
                'product_id' => 17,
                'product_name' => 'D4',
                'product_remarks' => '',
                'product_description' => 'D4',
                'product_sku' => 'D4',
                'is_deleted' => 0,
                'product_created' => '2022-03-08 17:19:43',
                'product_updated' => '2022-03-08 18:12:08',
                'product_slug' => 'd4',
                'product_status_id' => 2,
                'product_ranking' => 4,
                'product_category_id' => 3,
                'company_id' => NULL,
            ),
            16 => 
            array (
                'product_id' => 18,
                'product_name' => 'G.Puteri 金山公主',
                'product_remarks' => '',
                'product_description' => 'G.Puteri&nbsp;金山公主',
                'product_sku' => 'gputeri-',
                'is_deleted' => 0,
                'product_created' => '2022-03-08 21:01:15',
                'product_updated' => '2022-03-08 21:01:15',
                'product_slug' => 'gputeri',
                'product_status_id' => 2,
                'product_ranking' => 4,
                'product_category_id' => 3,
                'company_id' => NULL,
            ),
            17 => 
            array (
                'product_id' => 19,
                'product_name' => 'Coconut',
                'product_remarks' => '',
                'product_description' => 'Coconut',
                'product_sku' => 'coconut',
                'is_deleted' => 0,
                'product_created' => '2022-03-23 12:59:43',
                'product_updated' => '2022-03-23 12:59:43',
                'product_slug' => 'coconut',
                'product_status_id' => 2,
                'product_ranking' => 5,
                'product_category_id' => 6,
                'company_id' => NULL,
            ),
            18 => 
            array (
                'product_id' => 20,
                'product_name' => 'Chanee',
                'product_remarks' => '',
                'product_description' => 'Durian Chanee D123',
                'product_sku' => 'chanee',
                'is_deleted' => 0,
                'product_created' => '2022-03-24 17:39:44',
                'product_updated' => '2022-03-24 17:39:44',
                'product_slug' => 'chanee',
                'product_status_id' => 2,
                'product_ranking' => 5,
                'product_category_id' => 3,
                'company_id' => NULL,
            ),
            19 => 
            array (
                'product_id' => 21,
                'product_name' => 'ZAI',
                'product_remarks' => '',
                'product_description' => '臭果',
                'product_sku' => 'zai',
                'is_deleted' => 0,
                'product_created' => '2022-03-29 11:38:50',
                'product_updated' => '2022-03-29 11:38:50',
                'product_slug' => 'zai',
                'product_status_id' => 2,
                'product_ranking' => 5,
                'product_category_id' => 4,
                'company_id' => NULL,
            ),
            20 => 
            array (
                'product_id' => 22,
                'product_name' => '杂名',
                'product_remarks' => '',
                'product_description' => 'Durian',
                'product_sku' => '杂名',
                'is_deleted' => 0,
                'product_created' => '2022-04-04 18:05:30',
                'product_updated' => '2022-04-04 18:05:30',
                'product_slug' => '-1',
                'product_status_id' => 2,
                'product_ranking' => 5,
                'product_category_id' => 3,
                'company_id' => NULL,
            ),
            21 => 
            array (
                'product_id' => 23,
                'product_name' => '88',
                'product_remarks' => '',
                'product_description' => '88',
                'product_sku' => '88',
                'is_deleted' => 0,
                'product_created' => '2022-04-12 17:08:01',
                'product_updated' => '2022-04-12 17:10:05',
                'product_slug' => '88',
                'product_status_id' => 2,
                'product_ranking' => 4,
                'product_category_id' => 3,
                'company_id' => NULL,
            ),
            22 => 
            array (
                'product_id' => 24,
                'product_name' => 'FG 废果',
                'product_remarks' => '',
                'product_description' => 'Unwanted or unsellable durian fruit',
                'product_sku' => 'FG 废果',
                'is_deleted' => 0,
                'product_created' => '2022-10-26 18:12:55',
                'product_updated' => '2022-10-26 18:12:55',
                'product_slug' => 'fg',
                'product_status_id' => 2,
                'product_ranking' => 15,
                'product_category_id' => 1,
                'company_id' => 8,
            ),
            23 => 
            array (
                'product_id' => 25,
                'product_name' => 'FG 废果',
                'product_remarks' => '',
                'product_description' => 'Unwanted or unsellable durian fruit',
                'product_sku' => 'FG 废果a',
                'is_deleted' => 1,
                'product_created' => '2022-10-26 18:17:05',
                'product_updated' => '2022-10-26 19:10:36',
                'product_slug' => 'fg-1',
                'product_status_id' => 2,
                'product_ranking' => 50,
                'product_category_id' => 1,
                'company_id' => 5,
            ),
            24 => 
            array (
                'product_id' => 26,
                'product_name' => 'Black Thorn',
                'product_remarks' => '',
                'product_description' => 'Black Thorn',
                'product_sku' => 'black-thorn',
                'is_deleted' => 1,
                'product_created' => '2022-12-02 19:59:55',
                'product_updated' => '2022-12-02 19:59:55',
                'product_slug' => 'black-thorn',
                'product_status_id' => 2,
                'product_ranking' => 1,
                'product_category_id' => 1,
                'company_id' => 6,
            ),
            25 => 
            array (
                'product_id' => 27,
                'product_name' => 'Blackthorn',
                'product_remarks' => '',
                'product_description' => 'Black Thorn',
                'product_sku' => 'blackthorn',
                'is_deleted' => 1,
                'product_created' => '2022-12-02 20:08:37',
                'product_updated' => '2023-03-06 10:10:16',
                'product_slug' => 'blackthorn',
                'product_status_id' => 2,
                'product_ranking' => 1,
                'product_category_id' => 1,
                'company_id' => NULL,
            ),
        ));
        
        
    }
}