<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TblRawMaterialCompanyUsageTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_raw_material_company_usage')->delete();
        
        \DB::table('tbl_raw_material_company_usage')->insert(array (
            0 => 
            array (
                'raw_material_company_usage_id' => 23,
                'raw_material_id' => 49,
                'raw_material_company_id' => 97,
                'raw_material_company_usage_type' => 'stock in',
                'raw_material_company_usage_qty' => 100,
                'raw_material_company_usage_price_per_qty' => '30.00',
                'raw_material_company_usage_value_per_qty' => '45.00',
                'raw_material_company_usage_total_price' => '3000.00',
                'raw_material_company_usage_total_value' => '4500.00',
                'raw_material_company_usage_created' => '2022-07-20 02:05:03',
                'raw_material_company_usage_updated' => '2022-08-02 10:29:34',
                'user_id' => 2,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => '0.667',
                'raw_material_company_usage_total_value_remaining' => '1749.00',
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => 0,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-07-20',
                'claim_worker_id' => NULL,
            ),
            1 => 
            array (
                'raw_material_company_usage_id' => 24,
                'raw_material_id' => 50,
                'raw_material_company_id' => 98,
                'raw_material_company_usage_type' => 'stock in',
                'raw_material_company_usage_qty' => 100,
                'raw_material_company_usage_price_per_qty' => '30.00',
                'raw_material_company_usage_value_per_qty' => '30.00',
                'raw_material_company_usage_total_price' => '3000.00',
                'raw_material_company_usage_total_value' => '3000.00',
                'raw_material_company_usage_created' => '2022-07-20 02:05:32',
                'raw_material_company_usage_updated' => '2022-07-20 04:01:31',
                'user_id' => 2,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => '1.000',
                'raw_material_company_usage_total_value_remaining' => '2600.00',
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => 0,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-07-20',
                'claim_worker_id' => NULL,
            ),
            2 => 
            array (
                'raw_material_company_usage_id' => 25,
                'raw_material_id' => 49,
                'raw_material_company_id' => 97,
                'raw_material_company_usage_type' => 'usage',
                'raw_material_company_usage_qty' => 50,
                'raw_material_company_usage_price_per_qty' => '0.00',
                'raw_material_company_usage_value_per_qty' => '0.00',
                'raw_material_company_usage_total_price' => '0.00',
                'raw_material_company_usage_total_value' => '2500.00',
                'raw_material_company_usage_created' => '2022-07-20 02:08:56',
                'raw_material_company_usage_updated' => '2022-07-20 02:08:56',
                'user_id' => 1,
                'formula_usage_id' => 11,
                'formula_usage_item_id' => 15,
                'unit_price_per_value' => NULL,
                'raw_material_company_usage_total_value_remaining' => NULL,
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => NULL,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-07-20',
                'claim_worker_id' => NULL,
            ),
            3 => 
            array (
                'raw_material_company_usage_id' => 26,
                'raw_material_id' => 50,
                'raw_material_company_id' => 98,
                'raw_material_company_usage_type' => 'usage',
                'raw_material_company_usage_qty' => 50,
                'raw_material_company_usage_price_per_qty' => '0.00',
                'raw_material_company_usage_value_per_qty' => '0.00',
                'raw_material_company_usage_total_price' => '0.00',
                'raw_material_company_usage_total_value' => '100.00',
                'raw_material_company_usage_created' => '2022-07-20 02:14:39',
                'raw_material_company_usage_updated' => '2022-07-20 02:14:39',
                'user_id' => 4,
                'formula_usage_id' => 12,
                'formula_usage_item_id' => 16,
                'unit_price_per_value' => NULL,
                'raw_material_company_usage_total_value_remaining' => NULL,
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => NULL,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-07-20',
                'claim_worker_id' => NULL,
            ),
            4 => 
            array (
                'raw_material_company_usage_id' => 32,
                'raw_material_id' => 49,
                'raw_material_company_id' => 97,
                'raw_material_company_usage_type' => 'usage',
                'raw_material_company_usage_qty' => 50,
                'raw_material_company_usage_price_per_qty' => '0.00',
                'raw_material_company_usage_value_per_qty' => '0.00',
                'raw_material_company_usage_total_price' => '0.00',
                'raw_material_company_usage_total_value' => '250.00',
                'raw_material_company_usage_created' => '2022-07-20 02:28:24',
                'raw_material_company_usage_updated' => '2022-07-20 02:28:24',
                'user_id' => 2,
                'formula_usage_id' => 16,
                'formula_usage_item_id' => 17,
                'unit_price_per_value' => NULL,
                'raw_material_company_usage_total_value_remaining' => NULL,
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => NULL,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-07-20',
                'claim_worker_id' => NULL,
            ),
            5 => 
            array (
                'raw_material_company_usage_id' => 40,
                'raw_material_id' => 54,
                'raw_material_company_id' => 102,
                'raw_material_company_usage_type' => 'stock in',
                'raw_material_company_usage_qty' => 100,
                'raw_material_company_usage_price_per_qty' => '100.00',
                'raw_material_company_usage_value_per_qty' => '40.00',
                'raw_material_company_usage_total_price' => '10000.00',
                'raw_material_company_usage_total_value' => '4000.00',
                'raw_material_company_usage_created' => '2022-07-20 02:42:32',
                'raw_material_company_usage_updated' => '2022-07-20 03:13:19',
                'user_id' => 2,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => '2.500',
                'raw_material_company_usage_total_value_remaining' => '3904.00',
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => 0,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-07-20',
                'claim_worker_id' => NULL,
            ),
            6 => 
            array (
                'raw_material_company_usage_id' => 41,
                'raw_material_id' => 54,
                'raw_material_company_id' => 102,
                'raw_material_company_usage_type' => 'usage',
                'raw_material_company_usage_qty' => 1,
                'raw_material_company_usage_price_per_qty' => '0.00',
                'raw_material_company_usage_value_per_qty' => '0.00',
                'raw_material_company_usage_total_price' => '0.00',
                'raw_material_company_usage_total_value' => '50.00',
                'raw_material_company_usage_created' => '2022-07-20 02:43:13',
                'raw_material_company_usage_updated' => '2022-07-20 02:43:13',
                'user_id' => 2,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => NULL,
                'raw_material_company_usage_total_value_remaining' => NULL,
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => NULL,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-07-20',
                'claim_worker_id' => NULL,
            ),
            7 => 
            array (
                'raw_material_company_usage_id' => 42,
                'raw_material_id' => 58,
                'raw_material_company_id' => 106,
                'raw_material_company_usage_type' => 'stock in',
                'raw_material_company_usage_qty' => 100,
                'raw_material_company_usage_price_per_qty' => '10.00',
                'raw_material_company_usage_value_per_qty' => '10.00',
                'raw_material_company_usage_total_price' => '1000.00',
                'raw_material_company_usage_total_value' => '1000.00',
                'raw_material_company_usage_created' => '2022-07-20 02:43:31',
                'raw_material_company_usage_updated' => '2022-07-20 02:43:31',
                'user_id' => 3,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => '1.000',
                'raw_material_company_usage_total_value_remaining' => '1000.00',
                'user_wallet_history_id' => NULL,
                'is_claim' => 1,
                'claim_user_id' => 9,
                'claim_remaining_amount' => '1000.00',
                'raw_material_company_usage_date' => '2022-07-20',
                'claim_worker_id' => NULL,
            ),
            8 => 
            array (
                'raw_material_company_usage_id' => 43,
                'raw_material_id' => 54,
                'raw_material_company_id' => 102,
                'raw_material_company_usage_type' => 'usage',
                'raw_material_company_usage_qty' => 23,
                'raw_material_company_usage_price_per_qty' => '0.00',
                'raw_material_company_usage_value_per_qty' => '2.00',
                'raw_material_company_usage_total_price' => '0.00',
                'raw_material_company_usage_total_value' => '46.00',
                'raw_material_company_usage_created' => '2022-07-20 03:13:18',
                'raw_material_company_usage_updated' => '2022-07-20 03:13:18',
                'user_id' => 2,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => NULL,
                'raw_material_company_usage_total_value_remaining' => NULL,
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => NULL,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-07-20',
                'claim_worker_id' => NULL,
            ),
            9 => 
            array (
                'raw_material_company_usage_id' => 49,
                'raw_material_id' => 50,
                'raw_material_company_id' => 98,
                'raw_material_company_usage_type' => 'usage',
                'raw_material_company_usage_qty' => 10,
                'raw_material_company_usage_price_per_qty' => '0.00',
                'raw_material_company_usage_value_per_qty' => '0.00',
                'raw_material_company_usage_total_price' => '0.00',
                'raw_material_company_usage_total_value' => '300.00',
                'raw_material_company_usage_created' => '2022-07-20 04:01:30',
                'raw_material_company_usage_updated' => '2022-07-20 04:01:30',
                'user_id' => 2,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => NULL,
                'raw_material_company_usage_total_value_remaining' => NULL,
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => NULL,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-07-20',
                'claim_worker_id' => NULL,
            ),
            10 => 
            array (
                'raw_material_company_usage_id' => 50,
                'raw_material_id' => 49,
                'raw_material_company_id' => 97,
                'raw_material_company_usage_type' => 'usage',
                'raw_material_company_usage_qty' => 1,
                'raw_material_company_usage_price_per_qty' => '0.00',
                'raw_material_company_usage_value_per_qty' => '0.00',
                'raw_material_company_usage_total_price' => '0.00',
                'raw_material_company_usage_total_value' => '1.00',
                'raw_material_company_usage_created' => '2022-08-02 10:29:32',
                'raw_material_company_usage_updated' => '2022-08-02 10:29:32',
                'user_id' => 1,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => NULL,
                'raw_material_company_usage_total_value_remaining' => NULL,
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => NULL,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-08-02',
                'claim_worker_id' => NULL,
            ),
            11 => 
            array (
                'raw_material_company_usage_id' => 55,
                'raw_material_id' => 54,
                'raw_material_company_id' => 138,
                'raw_material_company_usage_type' => 'stock in',
                'raw_material_company_usage_qty' => 509,
                'raw_material_company_usage_price_per_qty' => '22.77',
                'raw_material_company_usage_value_per_qty' => '40.00',
                'raw_material_company_usage_total_price' => '11590.00',
                'raw_material_company_usage_total_value' => '20360.00',
                'raw_material_company_usage_created' => '2022-08-24 18:07:26',
                'raw_material_company_usage_updated' => '2022-10-25 15:18:35',
                'user_id' => 3,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => '0.569',
                'raw_material_company_usage_total_value_remaining' => '20360.00',
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => 0,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-01-31',
                'claim_worker_id' => NULL,
            ),
            12 => 
            array (
                'raw_material_company_usage_id' => 56,
                'raw_material_id' => 51,
                'raw_material_company_id' => 139,
                'raw_material_company_usage_type' => 'stock in',
                'raw_material_company_usage_qty' => 67,
                'raw_material_company_usage_price_per_qty' => '188.00',
                'raw_material_company_usage_value_per_qty' => '50.00',
                'raw_material_company_usage_total_price' => '12596.00',
                'raw_material_company_usage_total_value' => '3350.00',
                'raw_material_company_usage_created' => '2022-08-24 18:07:26',
                'raw_material_company_usage_updated' => '2022-10-25 15:18:35',
                'user_id' => 1,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => '3.760',
                'raw_material_company_usage_total_value_remaining' => '3350.00',
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => 0,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-01-31',
                'claim_worker_id' => NULL,
            ),
            13 => 
            array (
                'raw_material_company_usage_id' => 68,
                'raw_material_id' => 51,
                'raw_material_company_id' => 139,
                'raw_material_company_usage_type' => 'stock in',
                'raw_material_company_usage_qty' => 2,
                'raw_material_company_usage_price_per_qty' => '170.00',
                'raw_material_company_usage_value_per_qty' => '1.00',
                'raw_material_company_usage_total_price' => '340.00',
                'raw_material_company_usage_total_value' => '2.00',
                'raw_material_company_usage_created' => '2022-08-25 15:59:36',
                'raw_material_company_usage_updated' => '2022-08-25 15:59:36',
                'user_id' => 3,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => '170.000',
                'raw_material_company_usage_total_value_remaining' => '2.00',
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => 0,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-04-30',
                'claim_worker_id' => NULL,
            ),
            14 => 
            array (
                'raw_material_company_usage_id' => 87,
                'raw_material_id' => 52,
                'raw_material_company_id' => 174,
                'raw_material_company_usage_type' => 'stock in',
                'raw_material_company_usage_qty' => 35,
                'raw_material_company_usage_price_per_qty' => '260.00',
                'raw_material_company_usage_value_per_qty' => '50.00',
                'raw_material_company_usage_total_price' => '9100.00',
                'raw_material_company_usage_total_value' => '1750.00',
                'raw_material_company_usage_created' => '2022-08-29 10:56:16',
                'raw_material_company_usage_updated' => '2022-08-29 10:56:16',
                'user_id' => 3,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => '5.200',
                'raw_material_company_usage_total_value_remaining' => '1750.00',
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => 0,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-08-23',
                'claim_worker_id' => NULL,
            ),
            15 => 
            array (
                'raw_material_company_usage_id' => 89,
                'raw_material_id' => 49,
                'raw_material_company_id' => 175,
                'raw_material_company_usage_type' => 'stock in',
                'raw_material_company_usage_qty' => 27,
                'raw_material_company_usage_price_per_qty' => '193.00',
                'raw_material_company_usage_value_per_qty' => '50.00',
                'raw_material_company_usage_total_price' => '5211.00',
                'raw_material_company_usage_total_value' => '1350.00',
                'raw_material_company_usage_created' => '2022-08-29 11:13:12',
                'raw_material_company_usage_updated' => '2022-08-29 11:13:12',
                'user_id' => 2,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => '3.860',
                'raw_material_company_usage_total_value_remaining' => '1350.00',
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => 0,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-02-11',
                'claim_worker_id' => NULL,
            ),
            16 => 
            array (
                'raw_material_company_usage_id' => 90,
                'raw_material_id' => 52,
                'raw_material_company_id' => 174,
                'raw_material_company_usage_type' => 'stock in',
                'raw_material_company_usage_qty' => 18,
                'raw_material_company_usage_price_per_qty' => '75.00',
                'raw_material_company_usage_value_per_qty' => '25.00',
                'raw_material_company_usage_total_price' => '1350.00',
                'raw_material_company_usage_total_value' => '450.00',
                'raw_material_company_usage_created' => '2022-08-29 11:13:12',
                'raw_material_company_usage_updated' => '2022-08-29 11:13:12',
                'user_id' => 3,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => '3.000',
                'raw_material_company_usage_total_value_remaining' => '450.00',
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => 0,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-02-11',
                'claim_worker_id' => NULL,
            ),
            17 => 
            array (
                'raw_material_company_usage_id' => 93,
                'raw_material_id' => 55,
                'raw_material_company_id' => 179,
                'raw_material_company_usage_type' => 'stock in',
                'raw_material_company_usage_qty' => 2,
                'raw_material_company_usage_price_per_qty' => '144.00',
                'raw_material_company_usage_value_per_qty' => '5.00',
                'raw_material_company_usage_total_price' => '288.00',
                'raw_material_company_usage_total_value' => '10.00',
                'raw_material_company_usage_created' => '2022-08-29 11:44:37',
                'raw_material_company_usage_updated' => '2022-08-29 11:44:37',
                'user_id' => 3,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => '28.800',
                'raw_material_company_usage_total_value_remaining' => '10.00',
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => 0,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-03-15',
                'claim_worker_id' => NULL,
            ),
            18 => 
            array (
                'raw_material_company_usage_id' => 104,
                'raw_material_id' => 60,
                'raw_material_company_id' => 193,
                'raw_material_company_usage_type' => 'stock in',
                'raw_material_company_usage_qty' => 30,
                'raw_material_company_usage_price_per_qty' => '32.00',
                'raw_material_company_usage_value_per_qty' => '1.00',
                'raw_material_company_usage_total_price' => '960.00',
                'raw_material_company_usage_total_value' => '30.00',
                'raw_material_company_usage_created' => '2022-08-29 12:40:16',
                'raw_material_company_usage_updated' => '2022-08-29 12:40:16',
                'user_id' => 3,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => '32.000',
                'raw_material_company_usage_total_value_remaining' => '30.00',
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => 0,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-04-30',
                'claim_worker_id' => NULL,
            ),
            19 => 
            array (
                'raw_material_company_usage_id' => 110,
                'raw_material_id' => 57,
                'raw_material_company_id' => 194,
                'raw_material_company_usage_type' => 'stock in',
                'raw_material_company_usage_qty' => 5,
                'raw_material_company_usage_price_per_qty' => '220.00',
                'raw_material_company_usage_value_per_qty' => '5.00',
                'raw_material_company_usage_total_price' => '1100.00',
                'raw_material_company_usage_total_value' => '25.00',
                'raw_material_company_usage_created' => '2022-08-29 12:45:41',
                'raw_material_company_usage_updated' => '2022-08-29 12:45:41',
                'user_id' => 3,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => '44.000',
                'raw_material_company_usage_total_value_remaining' => '25.00',
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => 0,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-05-12',
                'claim_worker_id' => NULL,
            ),
            20 => 
            array (
                'raw_material_company_usage_id' => 115,
                'raw_material_id' => 52,
                'raw_material_company_id' => 174,
                'raw_material_company_usage_type' => 'stock in',
                'raw_material_company_usage_qty' => 35,
                'raw_material_company_usage_price_per_qty' => '260.00',
                'raw_material_company_usage_value_per_qty' => '50.00',
                'raw_material_company_usage_total_price' => '9100.00',
                'raw_material_company_usage_total_value' => '1750.00',
                'raw_material_company_usage_created' => '2022-08-30 17:07:26',
                'raw_material_company_usage_updated' => '2022-08-30 17:07:26',
                'user_id' => 3,
                'formula_usage_id' => 0,
                'formula_usage_item_id' => 0,
                'unit_price_per_value' => '5.200',
                'raw_material_company_usage_total_value_remaining' => '1750.00',
                'user_wallet_history_id' => NULL,
                'is_claim' => 0,
                'claim_user_id' => 0,
                'claim_remaining_amount' => NULL,
                'raw_material_company_usage_date' => '2022-08-23',
                'claim_worker_id' => NULL,
            ),
        ));
        
        
    }
}