<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TblRawMaterialCompanyUsageLogTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_raw_material_company_usage_log')->delete();
        
        \DB::table('tbl_raw_material_company_usage_log')->insert(array (
            0 => 
            array (
                'raw_material_company_usage_log_id' => 15,
                'raw_material_company_usage_id' => 23,
                'user_id' => 2,
                'raw_material_company_usage_log_created' => '2022-07-20 02:05:03',
                'raw_material_company_usage_log_action' => 'Add',
                'raw_material_company_usage_log_description' => 'Stock in.',
                'raw_material_company_usage_log_value_before' => '0.00',
                'raw_material_company_usage_log_value_after' => '4500.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            1 => 
            array (
                'raw_material_company_usage_log_id' => 16,
                'raw_material_company_usage_id' => 24,
                'user_id' => 2,
                'raw_material_company_usage_log_created' => '2022-07-20 02:05:32',
                'raw_material_company_usage_log_action' => 'Add',
                'raw_material_company_usage_log_description' => 'Stock in.',
                'raw_material_company_usage_log_value_before' => '0.00',
                'raw_material_company_usage_log_value_after' => '3000.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            2 => 
            array (
                'raw_material_company_usage_log_id' => 17,
                'raw_material_company_usage_id' => 23,
                'user_id' => 4,
                'raw_material_company_usage_log_created' => '2022-07-20 02:08:57',
                'raw_material_company_usage_log_action' => 'Deduct',
                'raw_material_company_usage_log_description' => 'Usage',
                'raw_material_company_usage_log_value_before' => '4500.00',
                'raw_material_company_usage_log_value_after' => '2000.00',
                'formula_usage_id' => 11,
                'formula_usage_item_id' => 15,
            ),
            3 => 
            array (
                'raw_material_company_usage_log_id' => 18,
                'raw_material_company_usage_id' => 24,
                'user_id' => 4,
                'raw_material_company_usage_log_created' => '2022-07-20 02:14:39',
                'raw_material_company_usage_log_action' => 'Deduct',
                'raw_material_company_usage_log_description' => 'Usage',
                'raw_material_company_usage_log_value_before' => '3000.00',
                'raw_material_company_usage_log_value_after' => '2900.00',
                'formula_usage_id' => 12,
                'formula_usage_item_id' => 16,
            ),
            4 => 
            array (
                'raw_material_company_usage_log_id' => 24,
                'raw_material_company_usage_id' => 23,
                'user_id' => 4,
                'raw_material_company_usage_log_created' => '2022-07-20 02:28:25',
                'raw_material_company_usage_log_action' => 'Deduct',
                'raw_material_company_usage_log_description' => 'Usage',
                'raw_material_company_usage_log_value_before' => '2000.00',
                'raw_material_company_usage_log_value_after' => '1750.00',
                'formula_usage_id' => 16,
                'formula_usage_item_id' => 17,
            ),
            5 => 
            array (
                'raw_material_company_usage_log_id' => 32,
                'raw_material_company_usage_id' => 40,
                'user_id' => 2,
                'raw_material_company_usage_log_created' => '2022-07-20 02:42:32',
                'raw_material_company_usage_log_action' => 'Add',
                'raw_material_company_usage_log_description' => 'Stock in.',
                'raw_material_company_usage_log_value_before' => '0.00',
                'raw_material_company_usage_log_value_after' => '4000.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            6 => 
            array (
                'raw_material_company_usage_log_id' => 33,
                'raw_material_company_usage_id' => 40,
                'user_id' => 4,
                'raw_material_company_usage_log_created' => '2022-07-20 02:43:14',
                'raw_material_company_usage_log_action' => 'Deduct',
                'raw_material_company_usage_log_description' => 'Usage',
                'raw_material_company_usage_log_value_before' => '4000.00',
                'raw_material_company_usage_log_value_after' => '3950.00',
                'formula_usage_id' => 28,
                'formula_usage_item_id' => 24,
            ),
            7 => 
            array (
                'raw_material_company_usage_log_id' => 34,
                'raw_material_company_usage_id' => 42,
                'user_id' => 2,
                'raw_material_company_usage_log_created' => '2022-07-20 02:43:31',
                'raw_material_company_usage_log_action' => 'Add',
                'raw_material_company_usage_log_description' => 'Stock in.',
                'raw_material_company_usage_log_value_before' => '0.00',
                'raw_material_company_usage_log_value_after' => '1000.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            8 => 
            array (
                'raw_material_company_usage_log_id' => 35,
                'raw_material_company_usage_id' => 40,
                'user_id' => 2,
                'raw_material_company_usage_log_created' => '2022-07-20 03:13:19',
                'raw_material_company_usage_log_action' => 'Deduct',
                'raw_material_company_usage_log_description' => 'Usage',
                'raw_material_company_usage_log_value_before' => '3950.00',
                'raw_material_company_usage_log_value_after' => '3904.00',
                'formula_usage_id' => 29,
                'formula_usage_item_id' => 25,
            ),
            9 => 
            array (
                'raw_material_company_usage_log_id' => 41,
                'raw_material_company_usage_id' => 24,
                'user_id' => 4,
                'raw_material_company_usage_log_created' => '2022-07-20 04:01:31',
                'raw_material_company_usage_log_action' => 'Deduct',
                'raw_material_company_usage_log_description' => 'Usage',
                'raw_material_company_usage_log_value_before' => '2900.00',
                'raw_material_company_usage_log_value_after' => '2600.00',
                'formula_usage_id' => 31,
                'formula_usage_item_id' => 31,
            ),
            10 => 
            array (
                'raw_material_company_usage_log_id' => 42,
                'raw_material_company_usage_id' => 23,
                'user_id' => 4,
                'raw_material_company_usage_log_created' => '2022-08-02 10:29:34',
                'raw_material_company_usage_log_action' => 'Deduct',
                'raw_material_company_usage_log_description' => 'Usage',
                'raw_material_company_usage_log_value_before' => '1750.00',
                'raw_material_company_usage_log_value_after' => '1749.00',
                'formula_usage_id' => 32,
                'formula_usage_item_id' => 32,
            ),
            11 => 
            array (
                'raw_material_company_usage_log_id' => 51,
                'raw_material_company_usage_id' => 55,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-24 18:07:26',
                'raw_material_company_usage_log_action' => 'Add',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '0.00',
                'raw_material_company_usage_log_value_after' => '20320.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            12 => 
            array (
                'raw_material_company_usage_log_id' => 52,
                'raw_material_company_usage_id' => 56,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-24 18:07:26',
                'raw_material_company_usage_log_action' => 'Add',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '0.00',
                'raw_material_company_usage_log_value_after' => '3350.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            13 => 
            array (
                'raw_material_company_usage_log_id' => 54,
                'raw_material_company_usage_id' => 55,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-25 11:16:31',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '20320.00',
                'raw_material_company_usage_log_value_after' => '20320.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            14 => 
            array (
                'raw_material_company_usage_log_id' => 55,
                'raw_material_company_usage_id' => 56,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-25 11:16:31',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '3350.00',
                'raw_material_company_usage_log_value_after' => '3350.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            15 => 
            array (
                'raw_material_company_usage_log_id' => 57,
                'raw_material_company_usage_id' => 55,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-25 11:21:30',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '20320.00',
                'raw_material_company_usage_log_value_after' => '20320.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            16 => 
            array (
                'raw_material_company_usage_log_id' => 58,
                'raw_material_company_usage_id' => 56,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-25 11:21:30',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '3350.00',
                'raw_material_company_usage_log_value_after' => '3350.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            17 => 
            array (
                'raw_material_company_usage_log_id' => 60,
                'raw_material_company_usage_id' => 55,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-25 11:30:16',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '20320.00',
                'raw_material_company_usage_log_value_after' => '20320.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            18 => 
            array (
                'raw_material_company_usage_log_id' => 61,
                'raw_material_company_usage_id' => 56,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-25 11:30:16',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '3350.00',
                'raw_material_company_usage_log_value_after' => '3350.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            19 => 
            array (
                'raw_material_company_usage_log_id' => 66,
                'raw_material_company_usage_id' => 55,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-25 11:31:33',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '20320.00',
                'raw_material_company_usage_log_value_after' => '20320.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            20 => 
            array (
                'raw_material_company_usage_log_id' => 67,
                'raw_material_company_usage_id' => 56,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-25 11:31:33',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '3350.00',
                'raw_material_company_usage_log_value_after' => '3350.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            21 => 
            array (
                'raw_material_company_usage_log_id' => 70,
                'raw_material_company_usage_id' => 55,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-25 12:31:26',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '20320.00',
                'raw_material_company_usage_log_value_after' => '20320.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            22 => 
            array (
                'raw_material_company_usage_log_id' => 71,
                'raw_material_company_usage_id' => 56,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-25 12:31:26',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '3350.00',
                'raw_material_company_usage_log_value_after' => '3350.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            23 => 
            array (
                'raw_material_company_usage_log_id' => 79,
                'raw_material_company_usage_id' => 55,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-25 15:43:35',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '20320.00',
                'raw_material_company_usage_log_value_after' => '20360.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            24 => 
            array (
                'raw_material_company_usage_log_id' => 80,
                'raw_material_company_usage_id' => 56,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-25 15:43:36',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '3350.00',
                'raw_material_company_usage_log_value_after' => '3350.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            25 => 
            array (
                'raw_material_company_usage_log_id' => 90,
                'raw_material_company_usage_id' => 68,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-25 15:59:36',
                'raw_material_company_usage_log_action' => 'Add',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '0.00',
                'raw_material_company_usage_log_value_after' => '2.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            26 => 
            array (
                'raw_material_company_usage_log_id' => 91,
                'raw_material_company_usage_id' => 56,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-25 16:07:16',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '3350.00',
                'raw_material_company_usage_log_value_after' => '3350.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            27 => 
            array (
                'raw_material_company_usage_log_id' => 93,
                'raw_material_company_usage_id' => 56,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-25 16:08:27',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '3350.00',
                'raw_material_company_usage_log_value_after' => '3350.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            28 => 
            array (
                'raw_material_company_usage_log_id' => 115,
                'raw_material_company_usage_id' => 87,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-29 10:56:16',
                'raw_material_company_usage_log_action' => 'Add',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '0.00',
                'raw_material_company_usage_log_value_after' => '1750.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            29 => 
            array (
                'raw_material_company_usage_log_id' => 117,
                'raw_material_company_usage_id' => 89,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-29 11:13:12',
                'raw_material_company_usage_log_action' => 'Add',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '0.00',
                'raw_material_company_usage_log_value_after' => '1350.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            30 => 
            array (
                'raw_material_company_usage_log_id' => 118,
                'raw_material_company_usage_id' => 90,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-29 11:13:12',
                'raw_material_company_usage_log_action' => 'Add',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '0.00',
                'raw_material_company_usage_log_value_after' => '450.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            31 => 
            array (
                'raw_material_company_usage_log_id' => 121,
                'raw_material_company_usage_id' => 93,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-29 11:44:37',
                'raw_material_company_usage_log_action' => 'Add',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '0.00',
                'raw_material_company_usage_log_value_after' => '10.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            32 => 
            array (
                'raw_material_company_usage_log_id' => 132,
                'raw_material_company_usage_id' => 104,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-29 12:40:16',
                'raw_material_company_usage_log_action' => 'Add',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '0.00',
                'raw_material_company_usage_log_value_after' => '30.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            33 => 
            array (
                'raw_material_company_usage_log_id' => 138,
                'raw_material_company_usage_id' => 110,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-29 12:45:41',
                'raw_material_company_usage_log_action' => 'Add',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '0.00',
                'raw_material_company_usage_log_value_after' => '25.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            34 => 
            array (
                'raw_material_company_usage_log_id' => 143,
                'raw_material_company_usage_id' => 115,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-08-30 17:07:26',
                'raw_material_company_usage_log_action' => 'Add',
                'raw_material_company_usage_log_description' => 'Multi stock in',
                'raw_material_company_usage_log_value_before' => '0.00',
                'raw_material_company_usage_log_value_after' => '1750.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            35 => 
            array (
                'raw_material_company_usage_log_id' => 144,
                'raw_material_company_usage_id' => 55,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-10-25 15:18:30',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in edit amount',
                'raw_material_company_usage_log_value_before' => '20360.00',
                'raw_material_company_usage_log_value_after' => '20360.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            36 => 
            array (
                'raw_material_company_usage_log_id' => 145,
                'raw_material_company_usage_id' => 56,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-10-25 15:18:30',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in edit amount',
                'raw_material_company_usage_log_value_before' => '3350.00',
                'raw_material_company_usage_log_value_after' => '3350.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            37 => 
            array (
                'raw_material_company_usage_log_id' => 155,
                'raw_material_company_usage_id' => 55,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-10-25 15:18:35',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in edit amount',
                'raw_material_company_usage_log_value_before' => '20360.00',
                'raw_material_company_usage_log_value_after' => '20360.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
            38 => 
            array (
                'raw_material_company_usage_log_id' => 156,
                'raw_material_company_usage_id' => 56,
                'user_id' => 3,
                'raw_material_company_usage_log_created' => '2022-10-25 15:18:35',
                'raw_material_company_usage_log_action' => 'Edit',
                'raw_material_company_usage_log_description' => 'Multi stock in edit amount',
                'raw_material_company_usage_log_value_before' => '3350.00',
                'raw_material_company_usage_log_value_after' => '3350.00',
                'formula_usage_id' => NULL,
                'formula_usage_item_id' => NULL,
            ),
        ));
        
        
    }
}