<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TblSyncCompanyExpenseItemTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_sync_company_expense_item')->delete();
        
        \DB::table('tbl_sync_company_expense_item')->insert(array (
            0 => 
            array (
                'sync_company_expense_item_id' => 101,
                'sync_company_expense_id' => 1,
                'setting_expense_id' => 20,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 5000,
                'sync_company_expense_item_unit_price' => '50.00',
                'sync_company_expense_item_total' => '250000.00',
                'sync_company_expense_item_created' => '2022-07-20 02:13:53',
                'sync_company_expense_item_updated' => '2022-07-20 02:13:53',
                'company_expense_item_id' => 1,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            1 => 
            array (
                'sync_company_expense_item_id' => 102,
                'sync_company_expense_id' => 1,
                'setting_expense_id' => 20,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 5000,
                'sync_company_expense_item_unit_price' => '5.00',
                'sync_company_expense_item_total' => '25000.00',
                'sync_company_expense_item_created' => '2022-07-20 02:14:21',
                'sync_company_expense_item_updated' => '2022-07-20 02:14:21',
                'company_expense_item_id' => 2,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            2 => 
            array (
                'sync_company_expense_item_id' => 103,
                'sync_company_expense_id' => 2,
                'setting_expense_id' => 11,
                'sync_company_expense_item_detail' => '{"9": {"detail": {"qty": 0, "time_slot": null, "expense_name": null, "expense_total": 250, "expense_value": 50, "setting_expense_type: ": null, "setting_expense_overwrite_commission": 0}, "worker_id": 9}, "11": {"detail": {"qty": 0, "time_slot": null, "expense_name": null, "expense_total": 400, "expense_value": 50, "setting_expense_type: ": null, "setting_expense_overwrite_commission": 0}, "worker_id": 11}, "exp_total": 650}',
                'sync_company_expense_item_unit' => NULL,
                'sync_company_expense_item_unit_price' => NULL,
                'sync_company_expense_item_total' => '650.00',
                'sync_company_expense_item_created' => '2022-07-20 02:12:12',
                'sync_company_expense_item_updated' => '2022-07-20 02:12:12',
                'company_expense_item_id' => 3,
                'is_claim' => NULL,
                'sync_supplier_id' => NULL,
            ),
            3 => 
            array (
                'sync_company_expense_item_id' => 104,
                'sync_company_expense_id' => 3,
                'setting_expense_id' => 10,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 500,
                'sync_company_expense_item_unit_price' => '5.00',
                'sync_company_expense_item_total' => '2500.00',
                'sync_company_expense_item_created' => '2022-07-20 02:11:09',
                'sync_company_expense_item_updated' => '2022-07-20 02:11:09',
                'company_expense_item_id' => 4,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            4 => 
            array (
                'sync_company_expense_item_id' => 105,
                'sync_company_expense_id' => 3,
                'setting_expense_id' => 7,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 100,
                'sync_company_expense_item_unit_price' => '2.00',
                'sync_company_expense_item_total' => '200.00',
                'sync_company_expense_item_created' => '2022-07-20 02:11:28',
                'sync_company_expense_item_updated' => '2022-07-20 02:11:28',
                'company_expense_item_id' => 31,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            5 => 
            array (
                'sync_company_expense_item_id' => 431,
                'sync_company_expense_id' => 210,
                'setting_expense_id' => 14,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '150.00',
                'sync_company_expense_item_total' => '150.00',
                'sync_company_expense_item_created' => '2023-01-10 08:50:26',
                'sync_company_expense_item_updated' => '2023-01-10 08:50:26',
                'company_expense_item_id' => 2125,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            6 => 
            array (
                'sync_company_expense_item_id' => 432,
                'sync_company_expense_id' => 211,
                'setting_expense_id' => 14,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '143.00',
                'sync_company_expense_item_total' => '143.00',
                'sync_company_expense_item_created' => '2023-01-10 08:49:40',
                'sync_company_expense_item_updated' => '2023-01-10 08:49:40',
                'company_expense_item_id' => 2126,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            7 => 
            array (
                'sync_company_expense_item_id' => 433,
                'sync_company_expense_id' => 212,
                'setting_expense_id' => 82,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '25.80',
                'sync_company_expense_item_total' => '25.80',
                'sync_company_expense_item_created' => '2023-01-10 09:05:44',
                'sync_company_expense_item_updated' => '2023-01-10 09:05:44',
                'company_expense_item_id' => 2127,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            8 => 
            array (
                'sync_company_expense_item_id' => 434,
                'sync_company_expense_id' => 213,
                'setting_expense_id' => 82,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '116.68',
                'sync_company_expense_item_total' => '116.68',
                'sync_company_expense_item_created' => '2023-01-10 09:04:52',
                'sync_company_expense_item_updated' => '2023-01-10 09:04:52',
                'company_expense_item_id' => 2128,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            9 => 
            array (
                'sync_company_expense_item_id' => 435,
                'sync_company_expense_id' => 214,
                'setting_expense_id' => 80,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '786.20',
                'sync_company_expense_item_total' => '786.20',
                'sync_company_expense_item_created' => '2023-01-10 09:04:04',
                'sync_company_expense_item_updated' => '2023-01-10 09:04:04',
                'company_expense_item_id' => 2129,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            10 => 
            array (
                'sync_company_expense_item_id' => 436,
                'sync_company_expense_id' => 215,
                'setting_expense_id' => 81,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '51.00',
                'sync_company_expense_item_total' => '51.00',
                'sync_company_expense_item_created' => '2023-01-10 09:02:27',
                'sync_company_expense_item_updated' => '2023-01-10 09:02:27',
                'company_expense_item_id' => 2130,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            11 => 
            array (
                'sync_company_expense_item_id' => 437,
                'sync_company_expense_id' => 216,
                'setting_expense_id' => 55,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '280.00',
                'sync_company_expense_item_total' => '280.00',
                'sync_company_expense_item_created' => '2023-01-10 09:01:24',
                'sync_company_expense_item_updated' => '2023-01-10 09:01:24',
                'company_expense_item_id' => 2131,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            12 => 
            array (
                'sync_company_expense_item_id' => 438,
                'sync_company_expense_id' => 217,
                'setting_expense_id' => 79,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '130.10',
                'sync_company_expense_item_total' => '130.10',
                'sync_company_expense_item_created' => '2023-01-10 09:00:17',
                'sync_company_expense_item_updated' => '2023-01-10 09:00:17',
                'company_expense_item_id' => 2132,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            13 => 
            array (
                'sync_company_expense_item_id' => 439,
                'sync_company_expense_id' => 218,
                'setting_expense_id' => 78,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '11.00',
                'sync_company_expense_item_total' => '11.00',
                'sync_company_expense_item_created' => '2023-01-10 08:59:31',
                'sync_company_expense_item_updated' => '2023-01-10 08:59:31',
                'company_expense_item_id' => 2133,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            14 => 
            array (
                'sync_company_expense_item_id' => 440,
                'sync_company_expense_id' => 219,
                'setting_expense_id' => 83,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '1928.90',
                'sync_company_expense_item_total' => '1928.90',
                'sync_company_expense_item_created' => '2023-01-10 09:08:25',
                'sync_company_expense_item_updated' => '2023-01-10 09:08:25',
                'company_expense_item_id' => 2134,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            15 => 
            array (
                'sync_company_expense_item_id' => 488,
                'sync_company_expense_id' => 228,
                'setting_expense_id' => 80,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '102.05',
                'sync_company_expense_item_total' => '102.05',
                'sync_company_expense_item_created' => '2023-01-15 08:56:32',
                'sync_company_expense_item_updated' => '2023-01-15 08:56:32',
                'company_expense_item_id' => 2183,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            16 => 
            array (
                'sync_company_expense_item_id' => 489,
                'sync_company_expense_id' => 229,
                'setting_expense_id' => 85,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '180.00',
                'sync_company_expense_item_total' => '180.00',
                'sync_company_expense_item_created' => '2023-01-15 10:43:32',
                'sync_company_expense_item_updated' => '2023-01-15 10:43:32',
                'company_expense_item_id' => 2184,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            17 => 
            array (
                'sync_company_expense_item_id' => 490,
                'sync_company_expense_id' => 230,
                'setting_expense_id' => 86,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '58.00',
                'sync_company_expense_item_total' => '58.00',
                'sync_company_expense_item_created' => '2023-01-15 10:38:16',
                'sync_company_expense_item_updated' => '2023-01-15 10:38:16',
                'company_expense_item_id' => 2185,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            18 => 
            array (
                'sync_company_expense_item_id' => 491,
                'sync_company_expense_id' => 231,
                'setting_expense_id' => 87,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '13.80',
                'sync_company_expense_item_total' => '13.80',
                'sync_company_expense_item_created' => '2023-01-15 10:57:10',
                'sync_company_expense_item_updated' => '2023-01-15 10:57:10',
                'company_expense_item_id' => 2186,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            19 => 
            array (
                'sync_company_expense_item_id' => 492,
                'sync_company_expense_id' => 232,
                'setting_expense_id' => 40,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '200.00',
                'sync_company_expense_item_total' => '200.00',
                'sync_company_expense_item_created' => '2023-01-15 11:23:33',
                'sync_company_expense_item_updated' => '2023-01-15 11:23:33',
                'company_expense_item_id' => 2187,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            20 => 
            array (
                'sync_company_expense_item_id' => 493,
                'sync_company_expense_id' => 233,
                'setting_expense_id' => 84,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '150.00',
                'sync_company_expense_item_total' => '150.00',
                'sync_company_expense_item_created' => '2023-01-15 11:22:08',
                'sync_company_expense_item_updated' => '2023-01-15 11:22:08',
                'company_expense_item_id' => 2188,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            21 => 
            array (
                'sync_company_expense_item_id' => 494,
                'sync_company_expense_id' => 234,
                'setting_expense_id' => 88,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '490.00',
                'sync_company_expense_item_total' => '490.00',
                'sync_company_expense_item_created' => '2023-01-15 11:35:39',
                'sync_company_expense_item_updated' => '2023-01-15 11:35:39',
                'company_expense_item_id' => 2189,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            22 => 
            array (
                'sync_company_expense_item_id' => 495,
                'sync_company_expense_id' => 235,
                'setting_expense_id' => 89,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '5772.50',
                'sync_company_expense_item_total' => '5772.50',
                'sync_company_expense_item_created' => '2023-01-15 11:34:09',
                'sync_company_expense_item_updated' => '2023-01-15 11:34:09',
                'company_expense_item_id' => 2190,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            23 => 
            array (
                'sync_company_expense_item_id' => 496,
                'sync_company_expense_id' => 236,
                'setting_expense_id' => 90,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '2600.00',
                'sync_company_expense_item_total' => '2600.00',
                'sync_company_expense_item_created' => '2023-01-15 11:38:27',
                'sync_company_expense_item_updated' => '2023-01-15 11:38:27',
                'company_expense_item_id' => 2191,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            24 => 
            array (
                'sync_company_expense_item_id' => 497,
                'sync_company_expense_id' => 237,
                'setting_expense_id' => 96,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '238.00',
                'sync_company_expense_item_total' => '238.00',
                'sync_company_expense_item_created' => '2023-01-15 13:58:08',
                'sync_company_expense_item_updated' => '2023-01-15 13:58:08',
                'company_expense_item_id' => 2192,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            25 => 
            array (
                'sync_company_expense_item_id' => 498,
                'sync_company_expense_id' => 238,
                'setting_expense_id' => 94,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '250.00',
                'sync_company_expense_item_total' => '250.00',
                'sync_company_expense_item_created' => '2023-01-15 13:55:23',
                'sync_company_expense_item_updated' => '2023-01-15 13:55:23',
                'company_expense_item_id' => 2193,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            26 => 
            array (
                'sync_company_expense_item_id' => 499,
                'sync_company_expense_id' => 238,
                'setting_expense_id' => 94,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '552.00',
                'sync_company_expense_item_total' => '552.00',
                'sync_company_expense_item_created' => '2023-01-15 13:57:09',
                'sync_company_expense_item_updated' => '2023-01-15 13:57:09',
                'company_expense_item_id' => 2194,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            27 => 
            array (
                'sync_company_expense_item_id' => 500,
                'sync_company_expense_id' => 239,
                'setting_expense_id' => 91,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '180.00',
                'sync_company_expense_item_total' => '180.00',
                'sync_company_expense_item_created' => '2023-01-15 13:54:36',
                'sync_company_expense_item_updated' => '2023-01-15 13:54:36',
                'company_expense_item_id' => 2195,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            28 => 
            array (
                'sync_company_expense_item_id' => 501,
                'sync_company_expense_id' => 240,
                'setting_expense_id' => 93,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 2,
                'sync_company_expense_item_unit_price' => '400.00',
                'sync_company_expense_item_total' => '800.00',
                'sync_company_expense_item_created' => '2023-01-15 13:54:04',
                'sync_company_expense_item_updated' => '2023-01-15 13:54:04',
                'company_expense_item_id' => 2196,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            29 => 
            array (
                'sync_company_expense_item_id' => 502,
                'sync_company_expense_id' => 241,
                'setting_expense_id' => 92,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '129.02',
                'sync_company_expense_item_total' => '129.02',
                'sync_company_expense_item_created' => '2023-01-15 13:52:53',
                'sync_company_expense_item_updated' => '2023-01-15 13:52:53',
                'company_expense_item_id' => 2197,
                'is_claim' => 0,
                'sync_supplier_id' => NULL,
            ),
            30 => 
            array (
                'sync_company_expense_item_id' => 503,
                'sync_company_expense_id' => 242,
                'setting_expense_id' => 92,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '113.31',
                'sync_company_expense_item_total' => '113.31',
                'sync_company_expense_item_created' => '2023-01-15 13:52:12',
                'sync_company_expense_item_updated' => '2023-01-15 13:52:12',
                'company_expense_item_id' => 2198,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            31 => 
            array (
                'sync_company_expense_item_id' => 504,
                'sync_company_expense_id' => 243,
                'setting_expense_id' => 59,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '47.00',
                'sync_company_expense_item_total' => '47.00',
                'sync_company_expense_item_created' => '2023-01-15 13:51:00',
                'sync_company_expense_item_updated' => '2023-01-15 13:51:00',
                'company_expense_item_id' => 2199,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            32 => 
            array (
                'sync_company_expense_item_id' => 505,
                'sync_company_expense_id' => 244,
                'setting_expense_id' => 96,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '259.00',
                'sync_company_expense_item_total' => '259.00',
                'sync_company_expense_item_created' => '2023-01-15 14:02:46',
                'sync_company_expense_item_updated' => '2023-01-15 14:02:46',
                'company_expense_item_id' => 2200,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            33 => 
            array (
                'sync_company_expense_item_id' => 586,
                'sync_company_expense_id' => 259,
                'setting_expense_id' => 88,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '200.00',
                'sync_company_expense_item_total' => '200.00',
                'sync_company_expense_item_created' => '2023-01-29 20:50:56',
                'sync_company_expense_item_updated' => '2023-01-29 20:50:56',
                'company_expense_item_id' => 2312,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            34 => 
            array (
                'sync_company_expense_item_id' => 587,
                'sync_company_expense_id' => 260,
                'setting_expense_id' => 84,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 114,
                'sync_company_expense_item_unit_price' => '114.00',
                'sync_company_expense_item_total' => '12996.00',
                'sync_company_expense_item_created' => '2023-01-29 20:49:51',
                'sync_company_expense_item_updated' => '2023-01-29 20:49:51',
                'company_expense_item_id' => 2313,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            35 => 
            array (
                'sync_company_expense_item_id' => 588,
                'sync_company_expense_id' => 261,
                'setting_expense_id' => 80,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '249.75',
                'sync_company_expense_item_total' => '249.75',
                'sync_company_expense_item_created' => '2023-01-29 20:48:51',
                'sync_company_expense_item_updated' => '2023-01-29 20:48:51',
                'company_expense_item_id' => 2314,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            36 => 
            array (
                'sync_company_expense_item_id' => 589,
                'sync_company_expense_id' => 262,
                'setting_expense_id' => 92,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '55.15',
                'sync_company_expense_item_total' => '55.15',
                'sync_company_expense_item_created' => '2023-01-29 20:47:54',
                'sync_company_expense_item_updated' => '2023-01-29 20:47:54',
                'company_expense_item_id' => 2315,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            37 => 
            array (
                'sync_company_expense_item_id' => 590,
                'sync_company_expense_id' => 263,
                'setting_expense_id' => 14,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '124.05',
                'sync_company_expense_item_total' => '124.05',
                'sync_company_expense_item_created' => '2023-01-29 20:47:12',
                'sync_company_expense_item_updated' => '2023-01-29 20:47:12',
                'company_expense_item_id' => 2316,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            38 => 
            array (
                'sync_company_expense_item_id' => 591,
                'sync_company_expense_id' => 264,
                'setting_expense_id' => 92,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '115.12',
                'sync_company_expense_item_total' => '115.12',
                'sync_company_expense_item_created' => '2023-01-29 20:46:28',
                'sync_company_expense_item_updated' => '2023-01-29 20:46:28',
                'company_expense_item_id' => 2317,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            39 => 
            array (
                'sync_company_expense_item_id' => 592,
                'sync_company_expense_id' => 265,
                'setting_expense_id' => 93,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '400.00',
                'sync_company_expense_item_total' => '400.00',
                'sync_company_expense_item_created' => '2023-01-29 20:45:17',
                'sync_company_expense_item_updated' => '2023-01-29 20:45:17',
                'company_expense_item_id' => 2318,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            40 => 
            array (
                'sync_company_expense_item_id' => 593,
                'sync_company_expense_id' => 266,
                'setting_expense_id' => 93,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '320.00',
                'sync_company_expense_item_total' => '320.00',
                'sync_company_expense_item_created' => '2023-01-29 20:44:38',
                'sync_company_expense_item_updated' => '2023-01-29 20:44:38',
                'company_expense_item_id' => 2319,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            41 => 
            array (
                'sync_company_expense_item_id' => 594,
                'sync_company_expense_id' => 267,
                'setting_expense_id' => 14,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '116.25',
                'sync_company_expense_item_total' => '116.25',
                'sync_company_expense_item_created' => '2023-01-29 20:43:36',
                'sync_company_expense_item_updated' => '2023-01-29 20:43:36',
                'company_expense_item_id' => 2320,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            42 => 
            array (
                'sync_company_expense_item_id' => 595,
                'sync_company_expense_id' => 268,
                'setting_expense_id' => 92,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '107.00',
                'sync_company_expense_item_total' => '107.00',
                'sync_company_expense_item_created' => '2023-01-29 21:15:34',
                'sync_company_expense_item_updated' => '2023-01-29 21:15:34',
                'company_expense_item_id' => 2321,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            43 => 
            array (
                'sync_company_expense_item_id' => 596,
                'sync_company_expense_id' => 269,
                'setting_expense_id' => 14,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '50.00',
                'sync_company_expense_item_total' => '50.00',
                'sync_company_expense_item_created' => '2023-01-29 21:14:54',
                'sync_company_expense_item_updated' => '2023-01-29 21:14:54',
                'company_expense_item_id' => 2322,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            44 => 
            array (
                'sync_company_expense_item_id' => 597,
                'sync_company_expense_id' => 270,
                'setting_expense_id' => 50,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '200.00',
                'sync_company_expense_item_total' => '200.00',
                'sync_company_expense_item_created' => '2023-01-29 21:12:55',
                'sync_company_expense_item_updated' => '2023-01-29 21:12:55',
                'company_expense_item_id' => 2323,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            45 => 
            array (
                'sync_company_expense_item_id' => 598,
                'sync_company_expense_id' => 271,
                'setting_expense_id' => 84,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '7.00',
                'sync_company_expense_item_total' => '7.00',
                'sync_company_expense_item_created' => '2023-01-29 21:11:19',
                'sync_company_expense_item_updated' => '2023-01-29 21:11:19',
                'company_expense_item_id' => 2324,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            46 => 
            array (
                'sync_company_expense_item_id' => 599,
                'sync_company_expense_id' => 272,
                'setting_expense_id' => 59,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '14.50',
                'sync_company_expense_item_total' => '14.50',
                'sync_company_expense_item_created' => '2023-01-29 21:10:24',
                'sync_company_expense_item_updated' => '2023-01-29 21:10:24',
                'company_expense_item_id' => 2325,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            47 => 
            array (
                'sync_company_expense_item_id' => 600,
                'sync_company_expense_id' => 273,
                'setting_expense_id' => 97,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '304.00',
                'sync_company_expense_item_total' => '304.00',
                'sync_company_expense_item_created' => '2023-01-29 21:22:18',
                'sync_company_expense_item_updated' => '2023-01-29 21:22:18',
                'company_expense_item_id' => 2326,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            48 => 
            array (
                'sync_company_expense_item_id' => 601,
                'sync_company_expense_id' => 274,
                'setting_expense_id' => 98,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '197.80',
                'sync_company_expense_item_total' => '197.80',
                'sync_company_expense_item_created' => '2023-01-29 21:21:46',
                'sync_company_expense_item_updated' => '2023-01-29 21:21:46',
                'company_expense_item_id' => 2327,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            49 => 
            array (
                'sync_company_expense_item_id' => 602,
                'sync_company_expense_id' => 275,
                'setting_expense_id' => 83,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '324.00',
                'sync_company_expense_item_total' => '324.00',
                'sync_company_expense_item_created' => '2023-01-29 21:36:46',
                'sync_company_expense_item_updated' => '2023-01-29 21:36:46',
                'company_expense_item_id' => 2328,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            50 => 
            array (
                'sync_company_expense_item_id' => 603,
                'sync_company_expense_id' => 276,
                'setting_expense_id' => 99,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '462.80',
                'sync_company_expense_item_total' => '462.80',
                'sync_company_expense_item_created' => '2023-01-29 21:46:44',
                'sync_company_expense_item_updated' => '2023-01-29 21:46:44',
                'company_expense_item_id' => 2329,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            51 => 
            array (
                'sync_company_expense_item_id' => 604,
                'sync_company_expense_id' => 277,
                'setting_expense_id' => 83,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '1214.00',
                'sync_company_expense_item_total' => '1214.00',
                'sync_company_expense_item_created' => '2023-01-29 21:46:03',
                'sync_company_expense_item_updated' => '2023-01-29 21:46:03',
                'company_expense_item_id' => 2330,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            52 => 
            array (
                'sync_company_expense_item_id' => 605,
                'sync_company_expense_id' => 278,
                'setting_expense_id' => 99,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '683.50',
                'sync_company_expense_item_total' => '683.50',
                'sync_company_expense_item_created' => '2023-01-29 21:40:04',
                'sync_company_expense_item_updated' => '2023-01-29 21:40:04',
                'company_expense_item_id' => 2331,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            53 => 
            array (
                'sync_company_expense_item_id' => 618,
                'sync_company_expense_id' => 281,
                'setting_expense_id' => 100,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '1021.00',
                'sync_company_expense_item_total' => '1021.00',
                'sync_company_expense_item_created' => '2023-01-31 21:48:30',
                'sync_company_expense_item_updated' => '2023-01-31 21:48:30',
                'company_expense_item_id' => 2423,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            54 => 
            array (
                'sync_company_expense_item_id' => 619,
                'sync_company_expense_id' => 282,
                'setting_expense_id' => 101,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '2640.00',
                'sync_company_expense_item_total' => '2640.00',
                'sync_company_expense_item_created' => '2023-01-31 21:54:21',
                'sync_company_expense_item_updated' => '2023-01-31 21:54:21',
                'company_expense_item_id' => 2424,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            55 => 
            array (
                'sync_company_expense_item_id' => 620,
                'sync_company_expense_id' => 283,
                'setting_expense_id' => 14,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '49.00',
                'sync_company_expense_item_total' => '49.00',
                'sync_company_expense_item_created' => '2023-01-31 22:00:59',
                'sync_company_expense_item_updated' => '2023-01-31 22:00:59',
                'company_expense_item_id' => 2425,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            56 => 
            array (
                'sync_company_expense_item_id' => 621,
                'sync_company_expense_id' => 284,
                'setting_expense_id' => 102,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '18.50',
                'sync_company_expense_item_total' => '18.50',
                'sync_company_expense_item_created' => '2023-01-31 21:59:29',
                'sync_company_expense_item_updated' => '2023-01-31 21:59:29',
                'company_expense_item_id' => 2426,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            57 => 
            array (
                'sync_company_expense_item_id' => 622,
                'sync_company_expense_id' => 285,
                'setting_expense_id' => 103,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '11.30',
                'sync_company_expense_item_total' => '11.30',
                'sync_company_expense_item_created' => '2023-01-31 22:03:23',
                'sync_company_expense_item_updated' => '2023-01-31 22:03:23',
                'company_expense_item_id' => 2427,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            58 => 
            array (
                'sync_company_expense_item_id' => 623,
                'sync_company_expense_id' => 286,
                'setting_expense_id' => 105,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '14.00',
                'sync_company_expense_item_total' => '14.00',
                'sync_company_expense_item_created' => '2023-01-31 22:07:12',
                'sync_company_expense_item_updated' => '2023-01-31 22:07:12',
                'company_expense_item_id' => 2428,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            59 => 
            array (
                'sync_company_expense_item_id' => 2551,
                'sync_company_expense_id' => 1375,
                'setting_expense_id' => 429,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '44.00',
                'sync_company_expense_item_total' => '44.00',
                'sync_company_expense_item_created' => '2023-05-08 09:57:13',
                'sync_company_expense_item_updated' => '2023-05-08 09:57:13',
                'company_expense_item_id' => 5622,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            60 => 
            array (
                'sync_company_expense_item_id' => 2552,
                'sync_company_expense_id' => 1376,
                'setting_expense_id' => 50,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '100.00',
                'sync_company_expense_item_total' => '100.00',
                'sync_company_expense_item_created' => '2023-05-08 09:56:48',
                'sync_company_expense_item_updated' => '2023-05-08 09:56:48',
                'company_expense_item_id' => 5623,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            61 => 
            array (
                'sync_company_expense_item_id' => 2553,
                'sync_company_expense_id' => 1377,
                'setting_expense_id' => 429,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '73.80',
                'sync_company_expense_item_total' => '73.80',
                'sync_company_expense_item_created' => '2023-05-08 09:56:13',
                'sync_company_expense_item_updated' => '2023-05-08 09:56:13',
                'company_expense_item_id' => 5624,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            62 => 
            array (
                'sync_company_expense_item_id' => 2554,
                'sync_company_expense_id' => 1378,
                'setting_expense_id' => 226,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '50.00',
                'sync_company_expense_item_total' => '50.00',
                'sync_company_expense_item_created' => '2023-05-08 09:55:35',
                'sync_company_expense_item_updated' => '2023-05-08 09:55:35',
                'company_expense_item_id' => 5625,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            63 => 
            array (
                'sync_company_expense_item_id' => 2555,
                'sync_company_expense_id' => 1379,
                'setting_expense_id' => 50,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '50.00',
                'sync_company_expense_item_total' => '50.00',
                'sync_company_expense_item_created' => '2023-05-08 09:55:05',
                'sync_company_expense_item_updated' => '2023-05-08 09:55:05',
                'company_expense_item_id' => 5626,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            64 => 
            array (
                'sync_company_expense_item_id' => 2556,
                'sync_company_expense_id' => 1380,
                'setting_expense_id' => 226,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 30,
                'sync_company_expense_item_unit_price' => '2.05',
                'sync_company_expense_item_total' => '62.02',
                'sync_company_expense_item_created' => '2023-05-08 09:54:30',
                'sync_company_expense_item_updated' => '2023-05-08 09:54:30',
                'company_expense_item_id' => 5627,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            65 => 
            array (
                'sync_company_expense_item_id' => 2557,
                'sync_company_expense_id' => 1381,
                'setting_expense_id' => 226,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 2,
                'sync_company_expense_item_unit_price' => '2.05',
                'sync_company_expense_item_total' => '6.10',
                'sync_company_expense_item_created' => '2023-05-08 09:53:50',
                'sync_company_expense_item_updated' => '2023-05-08 09:53:50',
                'company_expense_item_id' => 5628,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            66 => 
            array (
                'sync_company_expense_item_id' => 2558,
                'sync_company_expense_id' => 1382,
                'setting_expense_id' => 226,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 9,
                'sync_company_expense_item_unit_price' => '2.05',
                'sync_company_expense_item_total' => '18.75',
                'sync_company_expense_item_created' => '2023-05-08 09:52:50',
                'sync_company_expense_item_updated' => '2023-05-08 09:52:50',
                'company_expense_item_id' => 5629,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            67 => 
            array (
                'sync_company_expense_item_id' => 2559,
                'sync_company_expense_id' => 1383,
                'setting_expense_id' => 226,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 15,
                'sync_company_expense_item_unit_price' => '2.05',
                'sync_company_expense_item_total' => '31.27',
                'sync_company_expense_item_created' => '2023-05-08 09:52:09',
                'sync_company_expense_item_updated' => '2023-05-08 09:52:09',
                'company_expense_item_id' => 5630,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            68 => 
            array (
                'sync_company_expense_item_id' => 2560,
                'sync_company_expense_id' => 1384,
                'setting_expense_id' => 226,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 18,
                'sync_company_expense_item_unit_price' => '2.05',
                'sync_company_expense_item_total' => '38.11',
                'sync_company_expense_item_created' => '2023-05-08 09:51:25',
                'sync_company_expense_item_updated' => '2023-05-08 09:51:25',
                'company_expense_item_id' => 5631,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
            69 => 
            array (
                'sync_company_expense_item_id' => 2561,
                'sync_company_expense_id' => 1385,
                'setting_expense_id' => 50,
                'sync_company_expense_item_detail' => NULL,
                'sync_company_expense_item_unit' => 1,
                'sync_company_expense_item_unit_price' => '150.00',
                'sync_company_expense_item_total' => '150.00',
                'sync_company_expense_item_created' => '2023-05-08 09:50:38',
                'sync_company_expense_item_updated' => '2023-05-08 09:50:38',
                'company_expense_item_id' => 5632,
                'is_claim' => 1,
                'sync_supplier_id' => NULL,
            ),
        ));
        
        
    }
}