<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TblSettingFormulaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_setting_formula')->delete();
        
        \DB::table('tbl_setting_formula')->insert(array (
            0 => 
            array (
                'setting_formula_id' => 50,
                'setting_formula_name' => '{"en":"Platinum Plus","cn":"Platinum Plus"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 1,
                'setting_formula_created' => '2022-07-20 01:13:28',
                'setting_formula_updated' => '2022-07-20 01:13:28',
                'setting_formula_unit' => 'kg',
            ),
            1 => 
            array (
                'setting_formula_id' => 51,
                'setting_formula_name' => '{"en":"Gold Plus","cn":"Gold Plus"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 1,
                'setting_formula_created' => '2022-07-20 01:13:45',
                'setting_formula_updated' => '2022-07-20 01:13:45',
                'setting_formula_unit' => 'kg',
            ),
            2 => 
            array (
                'setting_formula_id' => 52,
                'setting_formula_name' => '{"en":"Rustica Plus","cn":"Rustica Plus"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 1,
                'setting_formula_created' => '2022-07-20 01:14:01',
                'setting_formula_updated' => '2022-07-20 01:14:01',
                'setting_formula_unit' => 'kg',
            ),
            3 => 
            array (
                'setting_formula_id' => 53,
                'setting_formula_name' => '{"en":"Yaraliva Nitrabor","cn":"Yaraliva Nitrabor"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 1,
                'setting_formula_created' => '2022-07-20 01:14:28',
                'setting_formula_updated' => '2022-07-20 01:14:28',
                'setting_formula_unit' => 'kg',
            ),
            4 => 
            array (
                'setting_formula_id' => 54,
                'setting_formula_name' => '{"en":"Yaramila","cn":"Yaramila"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 1,
                'setting_formula_created' => '2022-07-20 01:14:46',
                'setting_formula_updated' => '2022-07-20 01:14:46',
                'setting_formula_unit' => 'kg',
            ),
            5 => 
            array (
                'setting_formula_id' => 55,
                'setting_formula_name' => '{"en":"OM - Organic Fertilizer","cn":"OM - Organic Fertilizer"}',
                'setting_formula_category_id' => 4,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 1,
                'setting_formula_created' => '2022-07-20 01:15:09',
                'setting_formula_updated' => '2022-07-20 03:12:34',
                'setting_formula_unit' => 'kg',
            ),
            6 => 
            array (
                'setting_formula_id' => 56,
                'setting_formula_name' => '{"en":"Pre Bloom","cn":"Pre Bloom"}',
                'setting_formula_category_id' => 2,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'litre',
                'company_id' => 1,
                'setting_formula_created' => '2022-07-20 01:32:38',
                'setting_formula_updated' => '2022-07-20 01:32:38',
                'setting_formula_unit' => 'litre',
            ),
            7 => 
            array (
                'setting_formula_id' => 57,
                'setting_formula_name' => '{"en":"Post Bloom","cn":"Post Bloom"}',
                'setting_formula_category_id' => 2,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'litre',
                'company_id' => 1,
                'setting_formula_created' => '2022-07-20 01:34:08',
                'setting_formula_updated' => '2022-07-20 01:34:08',
                'setting_formula_unit' => 'litre',
            ),
            8 => 
            array (
                'setting_formula_id' => 58,
                'setting_formula_name' => '{"en":"BDP500","cn":"BDP500"}',
                'setting_formula_category_id' => 3,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'litre',
                'company_id' => 1,
                'setting_formula_created' => '2022-07-20 01:34:48',
                'setting_formula_updated' => '2022-07-20 01:34:48',
                'setting_formula_unit' => 'litre',
            ),
            9 => 
            array (
                'setting_formula_id' => 59,
                'setting_formula_name' => '{"en":"Cow Manure","cn":"Cow Manure"}',
                'setting_formula_category_id' => 3,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 1,
                'setting_formula_created' => '2022-07-20 01:35:29',
                'setting_formula_updated' => '2022-07-20 01:35:29',
                'setting_formula_unit' => 'kg',
            ),
            10 => 
            array (
                'setting_formula_id' => 60,
                'setting_formula_name' => '{"en":"WUXAL P45","cn":"WUXAL P45"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2022-08-25 12:46:35',
                'setting_formula_updated' => '2022-08-25 12:46:35',
                'setting_formula_unit' => 'kg',
            ),
            11 => 
            array (
                'setting_formula_id' => 61,
                'setting_formula_name' => '{"en":"NON ORGANIC","cn":"NON ORGANIC"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2022-08-25 13:04:09',
                'setting_formula_updated' => '2022-08-25 13:04:09',
                'setting_formula_unit' => 'kg',
            ),
            12 => 
            array (
                'setting_formula_id' => 62,
                'setting_formula_name' => '{"en":"GRASS RICE","cn":"GRASS RICE"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2022-08-29 09:49:52',
                'setting_formula_updated' => '2022-08-29 09:49:52',
                'setting_formula_unit' => 'kg',
            ),
            13 => 
            array (
                'setting_formula_id' => 63,
                'setting_formula_name' => '{"en":"BIO SOIL PLUS","cn":"BIO SOIL PLUS"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2022-08-29 10:44:03',
                'setting_formula_updated' => '2022-08-29 10:44:03',
                'setting_formula_unit' => 'kg',
            ),
            14 => 
            array (
                'setting_formula_id' => 64,
                'setting_formula_name' => '{"en":"SS MICROBES","cn":"SS MICROBES"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2022-08-29 10:44:31',
                'setting_formula_updated' => '2022-08-29 10:44:31',
                'setting_formula_unit' => 'kg',
            ),
            15 => 
            array (
                'setting_formula_id' => 65,
                'setting_formula_name' => '{"en":"GRANULAR TRIPLE SUPER PHOSPHATE","cn":"GRANULAR TRIPLE SUPER PHOSPHATE"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2022-10-25 15:40:14',
                'setting_formula_updated' => '2022-10-25 15:40:14',
                'setting_formula_unit' => 'kg',
            ),
            16 => 
            array (
                'setting_formula_id' => 66,
                'setting_formula_name' => '{"en":"GRANULAR TRIPLE SUPER PHOSPHATE","cn":"GRANULAR TRIPLE SUPER PHOSPHATE"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2022-10-25 15:46:31',
                'setting_formula_updated' => '2022-10-25 15:46:31',
                'setting_formula_unit' => 'kg',
            ),
            17 => 
            array (
                'setting_formula_id' => 67,
                'setting_formula_name' => '{"en":"SIKKO 250","cn":"SIKKO 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 10,
                'setting_formula_created' => '2023-03-10 11:46:47',
                'setting_formula_updated' => '2023-03-10 11:46:47',
                'setting_formula_unit' => 'kg',
            ),
            18 => 
            array (
                'setting_formula_id' => 68,
                'setting_formula_name' => '{"en":"SIKKO 250","cn":"SIKKO 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 8,
                'setting_formula_created' => '2023-03-10 11:46:47',
                'setting_formula_updated' => '2023-03-10 11:46:47',
                'setting_formula_unit' => 'kg',
            ),
            19 => 
            array (
                'setting_formula_id' => 69,
                'setting_formula_name' => '{"en":"SIKKO 250","cn":"SIKKO 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 5,
                'setting_formula_created' => '2023-03-10 11:46:47',
                'setting_formula_updated' => '2023-03-10 11:46:47',
                'setting_formula_unit' => 'kg',
            ),
            20 => 
            array (
                'setting_formula_id' => 70,
                'setting_formula_name' => '{"en":"SIKKO 250","cn":"SIKKO 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 6,
                'setting_formula_created' => '2023-03-10 11:46:47',
                'setting_formula_updated' => '2023-03-10 11:46:47',
                'setting_formula_unit' => 'kg',
            ),
            21 => 
            array (
                'setting_formula_id' => 71,
                'setting_formula_name' => '{"en":"SIKKO 250","cn":"SIKKO 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-10 11:46:47',
                'setting_formula_updated' => '2023-03-10 11:46:47',
                'setting_formula_unit' => 'kg',
            ),
            22 => 
            array (
                'setting_formula_id' => 72,
                'setting_formula_name' => '{"en":"SIKKO 250","cn":"SIKKO 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 7,
                'setting_formula_created' => '2023-03-10 11:46:47',
                'setting_formula_updated' => '2023-03-10 11:46:47',
                'setting_formula_unit' => 'kg',
            ),
            23 => 
            array (
                'setting_formula_id' => 73,
                'setting_formula_name' => '{"en":"SIKKO 250","cn":"SIKKO 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 4,
                'setting_formula_created' => '2023-03-10 11:46:47',
                'setting_formula_updated' => '2023-03-10 11:46:47',
                'setting_formula_unit' => 'kg',
            ),
            24 => 
            array (
                'setting_formula_id' => 74,
                'setting_formula_name' => '{"en":"SIKKO 250","cn":"SIKKO 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 9,
                'setting_formula_created' => '2023-03-10 11:46:47',
                'setting_formula_updated' => '2023-03-10 11:46:47',
                'setting_formula_unit' => 'kg',
            ),
            25 => 
            array (
                'setting_formula_id' => 75,
                'setting_formula_name' => '{"en":"IMID","cn":"IMID"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 10,
                'setting_formula_created' => '2023-03-10 11:47:31',
                'setting_formula_updated' => '2023-03-10 11:47:31',
                'setting_formula_unit' => 'kg',
            ),
            26 => 
            array (
                'setting_formula_id' => 76,
                'setting_formula_name' => '{"en":"IMID","cn":"IMID"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 8,
                'setting_formula_created' => '2023-03-10 11:47:31',
                'setting_formula_updated' => '2023-03-10 11:47:31',
                'setting_formula_unit' => 'kg',
            ),
            27 => 
            array (
                'setting_formula_id' => 77,
                'setting_formula_name' => '{"en":"IMID","cn":"IMID"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 5,
                'setting_formula_created' => '2023-03-10 11:47:31',
                'setting_formula_updated' => '2023-03-10 11:47:31',
                'setting_formula_unit' => 'kg',
            ),
            28 => 
            array (
                'setting_formula_id' => 78,
                'setting_formula_name' => '{"en":"IMID","cn":"IMID"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 6,
                'setting_formula_created' => '2023-03-10 11:47:31',
                'setting_formula_updated' => '2023-03-10 11:47:31',
                'setting_formula_unit' => 'kg',
            ),
            29 => 
            array (
                'setting_formula_id' => 79,
                'setting_formula_name' => '{"en":"IMID","cn":"IMID"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-10 11:47:31',
                'setting_formula_updated' => '2023-03-10 11:47:31',
                'setting_formula_unit' => 'kg',
            ),
            30 => 
            array (
                'setting_formula_id' => 80,
                'setting_formula_name' => '{"en":"IMID","cn":"IMID"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 7,
                'setting_formula_created' => '2023-03-10 11:47:31',
                'setting_formula_updated' => '2023-03-10 11:47:31',
                'setting_formula_unit' => 'kg',
            ),
            31 => 
            array (
                'setting_formula_id' => 81,
                'setting_formula_name' => '{"en":"IMID","cn":"IMID"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 4,
                'setting_formula_created' => '2023-03-10 11:47:31',
                'setting_formula_updated' => '2023-03-10 11:47:31',
                'setting_formula_unit' => 'kg',
            ),
            32 => 
            array (
                'setting_formula_id' => 82,
                'setting_formula_name' => '{"en":"IMID","cn":"IMID"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 9,
                'setting_formula_created' => '2023-03-10 11:47:31',
                'setting_formula_updated' => '2023-03-10 11:47:31',
                'setting_formula_unit' => 'kg',
            ),
            33 => 
            array (
                'setting_formula_id' => 83,
                'setting_formula_name' => '{"en":"FERTIUM 19\\/19\\/19","cn":"FERTIUM 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 10,
                'setting_formula_created' => '2023-03-10 11:49:51',
                'setting_formula_updated' => '2023-03-10 11:49:51',
                'setting_formula_unit' => 'kg',
            ),
            34 => 
            array (
                'setting_formula_id' => 84,
                'setting_formula_name' => '{"en":"FERTIUM 19\\/19\\/19","cn":"FERTIUM 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 8,
                'setting_formula_created' => '2023-03-10 11:49:51',
                'setting_formula_updated' => '2023-03-10 11:49:51',
                'setting_formula_unit' => 'kg',
            ),
            35 => 
            array (
                'setting_formula_id' => 85,
                'setting_formula_name' => '{"en":"FERTIUM 19\\/19\\/19","cn":"FERTIUM 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 5,
                'setting_formula_created' => '2023-03-10 11:49:51',
                'setting_formula_updated' => '2023-03-10 11:49:51',
                'setting_formula_unit' => 'kg',
            ),
            36 => 
            array (
                'setting_formula_id' => 86,
                'setting_formula_name' => '{"en":"FERTIUM 19\\/19\\/19","cn":"FERTIUM 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 6,
                'setting_formula_created' => '2023-03-10 11:49:51',
                'setting_formula_updated' => '2023-03-10 11:49:51',
                'setting_formula_unit' => 'kg',
            ),
            37 => 
            array (
                'setting_formula_id' => 87,
                'setting_formula_name' => '{"en":"FERTIUM 19\\/19\\/19","cn":"FERTIUM 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-10 11:49:51',
                'setting_formula_updated' => '2023-03-10 11:49:51',
                'setting_formula_unit' => 'kg',
            ),
            38 => 
            array (
                'setting_formula_id' => 88,
                'setting_formula_name' => '{"en":"FERTIUM 19\\/19\\/19","cn":"FERTIUM 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 7,
                'setting_formula_created' => '2023-03-10 11:49:51',
                'setting_formula_updated' => '2023-03-10 11:49:51',
                'setting_formula_unit' => 'kg',
            ),
            39 => 
            array (
                'setting_formula_id' => 89,
                'setting_formula_name' => '{"en":"FERTIUM 19\\/19\\/19","cn":"FERTIUM 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 4,
                'setting_formula_created' => '2023-03-10 11:49:51',
                'setting_formula_updated' => '2023-03-10 11:49:51',
                'setting_formula_unit' => 'kg',
            ),
            40 => 
            array (
                'setting_formula_id' => 90,
                'setting_formula_name' => '{"en":"FERTIUM 19\\/19\\/19","cn":"FERTIUM 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 9,
                'setting_formula_created' => '2023-03-10 11:49:51',
                'setting_formula_updated' => '2023-03-10 11:49:51',
                'setting_formula_unit' => 'kg',
            ),
            41 => 
            array (
                'setting_formula_id' => 91,
                'setting_formula_name' => '{"en":"HUSKY 250","cn":"HUSKY 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 10,
                'setting_formula_created' => '2023-03-13 11:27:53',
                'setting_formula_updated' => '2023-03-13 11:27:53',
                'setting_formula_unit' => 'kg',
            ),
            42 => 
            array (
                'setting_formula_id' => 92,
                'setting_formula_name' => '{"en":"HUSKY 250","cn":"HUSKY 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 8,
                'setting_formula_created' => '2023-03-13 11:27:53',
                'setting_formula_updated' => '2023-03-13 11:27:53',
                'setting_formula_unit' => 'kg',
            ),
            43 => 
            array (
                'setting_formula_id' => 93,
                'setting_formula_name' => '{"en":"HUSKY 250","cn":"HUSKY 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 5,
                'setting_formula_created' => '2023-03-13 11:27:53',
                'setting_formula_updated' => '2023-03-13 11:27:53',
                'setting_formula_unit' => 'kg',
            ),
            44 => 
            array (
                'setting_formula_id' => 94,
                'setting_formula_name' => '{"en":"HUSKY 250","cn":"HUSKY 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 6,
                'setting_formula_created' => '2023-03-13 11:27:53',
                'setting_formula_updated' => '2023-03-13 11:27:53',
                'setting_formula_unit' => 'kg',
            ),
            45 => 
            array (
                'setting_formula_id' => 95,
                'setting_formula_name' => '{"en":"HUSKY 250","cn":"HUSKY 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-13 11:27:53',
                'setting_formula_updated' => '2023-03-13 11:27:53',
                'setting_formula_unit' => 'kg',
            ),
            46 => 
            array (
                'setting_formula_id' => 96,
                'setting_formula_name' => '{"en":"HUSKY 250","cn":"HUSKY 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 7,
                'setting_formula_created' => '2023-03-13 11:27:53',
                'setting_formula_updated' => '2023-03-13 11:27:53',
                'setting_formula_unit' => 'kg',
            ),
            47 => 
            array (
                'setting_formula_id' => 97,
                'setting_formula_name' => '{"en":"HUSKY 250","cn":"HUSKY 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 4,
                'setting_formula_created' => '2023-03-13 11:27:53',
                'setting_formula_updated' => '2023-03-13 11:27:53',
                'setting_formula_unit' => 'kg',
            ),
            48 => 
            array (
                'setting_formula_id' => 98,
                'setting_formula_name' => '{"en":"HUSKY 250","cn":"HUSKY 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 9,
                'setting_formula_created' => '2023-03-13 11:27:53',
                'setting_formula_updated' => '2023-03-13 11:27:53',
                'setting_formula_unit' => 'kg',
            ),
            49 => 
            array (
                'setting_formula_id' => 99,
                'setting_formula_name' => '{"en":"SIKOR 250","cn":"SIKOR 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 10,
                'setting_formula_created' => '2023-03-13 11:45:14',
                'setting_formula_updated' => '2023-03-13 11:45:14',
                'setting_formula_unit' => 'kg',
            ),
            50 => 
            array (
                'setting_formula_id' => 100,
                'setting_formula_name' => '{"en":"SIKOR 250","cn":"SIKOR 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 8,
                'setting_formula_created' => '2023-03-13 11:45:14',
                'setting_formula_updated' => '2023-03-13 11:45:14',
                'setting_formula_unit' => 'kg',
            ),
            51 => 
            array (
                'setting_formula_id' => 101,
                'setting_formula_name' => '{"en":"SIKOR 250","cn":"SIKOR 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 5,
                'setting_formula_created' => '2023-03-13 11:45:14',
                'setting_formula_updated' => '2023-03-13 11:45:14',
                'setting_formula_unit' => 'kg',
            ),
            52 => 
            array (
                'setting_formula_id' => 102,
                'setting_formula_name' => '{"en":"SIKOR 250","cn":"SIKOR 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 6,
                'setting_formula_created' => '2023-03-13 11:45:14',
                'setting_formula_updated' => '2023-03-13 11:45:14',
                'setting_formula_unit' => 'kg',
            ),
            53 => 
            array (
                'setting_formula_id' => 103,
                'setting_formula_name' => '{"en":"SIKOR 250","cn":"SIKOR 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-13 11:45:14',
                'setting_formula_updated' => '2023-03-13 11:45:14',
                'setting_formula_unit' => 'kg',
            ),
            54 => 
            array (
                'setting_formula_id' => 104,
                'setting_formula_name' => '{"en":"SIKOR 250","cn":"SIKOR 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 7,
                'setting_formula_created' => '2023-03-13 11:45:14',
                'setting_formula_updated' => '2023-03-13 11:45:14',
                'setting_formula_unit' => 'kg',
            ),
            55 => 
            array (
                'setting_formula_id' => 105,
                'setting_formula_name' => '{"en":"SIKOR 250","cn":"SIKOR 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 4,
                'setting_formula_created' => '2023-03-13 11:45:14',
                'setting_formula_updated' => '2023-03-13 11:45:14',
                'setting_formula_unit' => 'kg',
            ),
            56 => 
            array (
                'setting_formula_id' => 106,
                'setting_formula_name' => '{"en":"SIKOR 250","cn":"SIKOR 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 9,
                'setting_formula_created' => '2023-03-13 11:45:14',
                'setting_formula_updated' => '2023-03-13 11:45:14',
                'setting_formula_unit' => 'kg',
            ),
            57 => 
            array (
                'setting_formula_id' => 107,
                'setting_formula_name' => '{"en":"FARMTROBIN 250","cn":"FARMTROBIN 250"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-13 11:45:48',
                'setting_formula_updated' => '2023-03-13 11:45:48',
                'setting_formula_unit' => 'kg',
            ),
            58 => 
            array (
                'setting_formula_id' => 108,
                'setting_formula_name' => '{"en":"DIFUSE SC","cn":"DIFUSE SC"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-13 11:46:13',
                'setting_formula_updated' => '2023-03-13 11:46:13',
                'setting_formula_unit' => 'kg',
            ),
            59 => 
            array (
                'setting_formula_id' => 109,
                'setting_formula_name' => '{"en":"DIMEXION","cn":"DIMEXION"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-13 11:46:39',
                'setting_formula_updated' => '2023-03-13 11:46:39',
                'setting_formula_unit' => 'kg',
            ),
            60 => 
            array (
                'setting_formula_id' => 110,
                'setting_formula_name' => '{"en":"WETCIT","cn":"WETCIT"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-13 11:47:01',
                'setting_formula_updated' => '2023-03-13 11:47:01',
                'setting_formula_unit' => 'kg',
            ),
            61 => 
            array (
                'setting_formula_id' => 111,
                'setting_formula_name' => '{"en":"C-THRIPS","cn":"C-THRIPS"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-13 11:47:25',
                'setting_formula_updated' => '2023-03-13 11:47:25',
                'setting_formula_unit' => 'kg',
            ),
            62 => 
            array (
                'setting_formula_id' => 112,
                'setting_formula_name' => '{"en":"16\\/16\\/16","cn":"16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-13 11:48:58',
                'setting_formula_updated' => '2023-03-13 11:48:58',
                'setting_formula_unit' => 'kg',
            ),
            63 => 
            array (
                'setting_formula_id' => 113,
                'setting_formula_name' => '{"en":"ANTRACOL 70WP","cn":"ANTRACOL 70WP"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-13 11:49:49',
                'setting_formula_updated' => '2023-03-13 11:49:49',
                'setting_formula_unit' => 'kg',
            ),
            64 => 
            array (
                'setting_formula_id' => 114,
                'setting_formula_name' => '{"en":"COMPO EXPERT BASAPLANT 19\\/19\\/19","cn":"COMPO EXPERT BASAPLANT 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-13 11:50:52',
                'setting_formula_updated' => '2023-03-13 11:50:52',
                'setting_formula_unit' => 'kg',
            ),
            65 => 
            array (
                'setting_formula_id' => 115,
                'setting_formula_name' => '{"en":"AZATIN","cn":"AZATIN"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-13 12:15:26',
                'setting_formula_updated' => '2023-03-13 12:15:26',
                'setting_formula_unit' => 'kg',
            ),
            66 => 
            array (
                'setting_formula_id' => 116,
                'setting_formula_name' => '{"en":"GARSOMI NPK 16\\/16\\/16","cn":"GARSOMI NPK 16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-13 12:16:02',
                'setting_formula_updated' => '2023-03-13 12:16:02',
                'setting_formula_unit' => 'kg',
            ),
            67 => 
            array (
                'setting_formula_id' => 117,
                'setting_formula_name' => '{"en":"HERO AMINOMAR 5L","cn":"HERO AMINOMAR 5L"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 2,
                'setting_formula_created' => '2023-03-13 12:16:28',
                'setting_formula_updated' => '2023-03-13 12:16:28',
                'setting_formula_unit' => 'kg',
            ),
            68 => 
            array (
                'setting_formula_id' => 118,
                'setting_formula_name' => '{"en":"HERO AMINOMAR 5L","cn":"HERO AMINOMAR 5L"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 10,
                'setting_formula_created' => '2023-08-04 10:04:14',
                'setting_formula_updated' => '2023-08-04 10:04:14',
                'setting_formula_unit' => 'kg',
            ),
            69 => 
            array (
                'setting_formula_id' => 119,
                'setting_formula_name' => '{"en":"HERO AMINOMAR 5L","cn":"HERO AMINOMAR 5L"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 8,
                'setting_formula_created' => '2023-08-04 10:04:14',
                'setting_formula_updated' => '2023-08-04 10:04:14',
                'setting_formula_unit' => 'kg',
            ),
            70 => 
            array (
                'setting_formula_id' => 120,
                'setting_formula_name' => '{"en":"HERO AMINOMAR 5L","cn":"HERO AMINOMAR 5L"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 5,
                'setting_formula_created' => '2023-08-04 10:04:14',
                'setting_formula_updated' => '2023-08-04 10:04:14',
                'setting_formula_unit' => 'kg',
            ),
            71 => 
            array (
                'setting_formula_id' => 121,
                'setting_formula_name' => '{"en":"HERO AMINOMAR 5L","cn":"HERO AMINOMAR 5L"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 6,
                'setting_formula_created' => '2023-08-04 10:04:14',
                'setting_formula_updated' => '2023-08-04 10:04:14',
                'setting_formula_unit' => 'kg',
            ),
            72 => 
            array (
                'setting_formula_id' => 122,
                'setting_formula_name' => '{"en":"HERO AMINOMAR 5L","cn":"HERO AMINOMAR 5L"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 7,
                'setting_formula_created' => '2023-08-04 10:04:14',
                'setting_formula_updated' => '2023-08-04 10:04:14',
                'setting_formula_unit' => 'kg',
            ),
            73 => 
            array (
                'setting_formula_id' => 123,
                'setting_formula_name' => '{"en":"HERO AMINOMAR 5L","cn":"HERO AMINOMAR 5L"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 4,
                'setting_formula_created' => '2023-08-04 10:04:14',
                'setting_formula_updated' => '2023-08-04 10:04:14',
                'setting_formula_unit' => 'kg',
            ),
            74 => 
            array (
                'setting_formula_id' => 124,
                'setting_formula_name' => '{"en":"HERO AMINOMAR 5L","cn":"HERO AMINOMAR 5L"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 9,
                'setting_formula_created' => '2023-08-04 10:04:14',
                'setting_formula_updated' => '2023-08-04 10:04:14',
                'setting_formula_unit' => 'kg',
            ),
            75 => 
            array (
                'setting_formula_id' => 125,
                'setting_formula_name' => '{"en":"GARSOMI NPK 16\\/16\\/16","cn":"GARSOMI NPK 16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 10,
                'setting_formula_created' => '2023-08-04 10:04:20',
                'setting_formula_updated' => '2023-08-04 10:04:20',
                'setting_formula_unit' => 'kg',
            ),
            76 => 
            array (
                'setting_formula_id' => 126,
                'setting_formula_name' => '{"en":"GARSOMI NPK 16\\/16\\/16","cn":"GARSOMI NPK 16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 8,
                'setting_formula_created' => '2023-08-04 10:04:20',
                'setting_formula_updated' => '2023-08-04 10:04:20',
                'setting_formula_unit' => 'kg',
            ),
            77 => 
            array (
                'setting_formula_id' => 127,
                'setting_formula_name' => '{"en":"GARSOMI NPK 16\\/16\\/16","cn":"GARSOMI NPK 16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 5,
                'setting_formula_created' => '2023-08-04 10:04:20',
                'setting_formula_updated' => '2023-08-04 10:04:20',
                'setting_formula_unit' => 'kg',
            ),
            78 => 
            array (
                'setting_formula_id' => 128,
                'setting_formula_name' => '{"en":"GARSOMI NPK 16\\/16\\/16","cn":"GARSOMI NPK 16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 6,
                'setting_formula_created' => '2023-08-04 10:04:20',
                'setting_formula_updated' => '2023-08-04 10:04:20',
                'setting_formula_unit' => 'kg',
            ),
            79 => 
            array (
                'setting_formula_id' => 129,
                'setting_formula_name' => '{"en":"GARSOMI NPK 16\\/16\\/16","cn":"GARSOMI NPK 16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 7,
                'setting_formula_created' => '2023-08-04 10:04:20',
                'setting_formula_updated' => '2023-08-04 10:04:20',
                'setting_formula_unit' => 'kg',
            ),
            80 => 
            array (
                'setting_formula_id' => 130,
                'setting_formula_name' => '{"en":"GARSOMI NPK 16\\/16\\/16","cn":"GARSOMI NPK 16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 4,
                'setting_formula_created' => '2023-08-04 10:04:20',
                'setting_formula_updated' => '2023-08-04 10:04:20',
                'setting_formula_unit' => 'kg',
            ),
            81 => 
            array (
                'setting_formula_id' => 131,
                'setting_formula_name' => '{"en":"GARSOMI NPK 16\\/16\\/16","cn":"GARSOMI NPK 16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 9,
                'setting_formula_created' => '2023-08-04 10:04:20',
                'setting_formula_updated' => '2023-08-04 10:04:20',
                'setting_formula_unit' => 'kg',
            ),
            82 => 
            array (
                'setting_formula_id' => 132,
                'setting_formula_name' => '{"en":"AZATIN","cn":"AZATIN"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 10,
                'setting_formula_created' => '2023-08-04 10:04:28',
                'setting_formula_updated' => '2023-08-04 10:04:28',
                'setting_formula_unit' => 'kg',
            ),
            83 => 
            array (
                'setting_formula_id' => 133,
                'setting_formula_name' => '{"en":"AZATIN","cn":"AZATIN"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 8,
                'setting_formula_created' => '2023-08-04 10:04:28',
                'setting_formula_updated' => '2023-08-04 10:04:28',
                'setting_formula_unit' => 'kg',
            ),
            84 => 
            array (
                'setting_formula_id' => 134,
                'setting_formula_name' => '{"en":"AZATIN","cn":"AZATIN"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 5,
                'setting_formula_created' => '2023-08-04 10:04:28',
                'setting_formula_updated' => '2023-08-04 10:04:28',
                'setting_formula_unit' => 'kg',
            ),
            85 => 
            array (
                'setting_formula_id' => 135,
                'setting_formula_name' => '{"en":"AZATIN","cn":"AZATIN"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 6,
                'setting_formula_created' => '2023-08-04 10:04:28',
                'setting_formula_updated' => '2023-08-04 10:04:28',
                'setting_formula_unit' => 'kg',
            ),
            86 => 
            array (
                'setting_formula_id' => 136,
                'setting_formula_name' => '{"en":"AZATIN","cn":"AZATIN"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 7,
                'setting_formula_created' => '2023-08-04 10:04:28',
                'setting_formula_updated' => '2023-08-04 10:04:28',
                'setting_formula_unit' => 'kg',
            ),
            87 => 
            array (
                'setting_formula_id' => 137,
                'setting_formula_name' => '{"en":"AZATIN","cn":"AZATIN"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 4,
                'setting_formula_created' => '2023-08-04 10:04:28',
                'setting_formula_updated' => '2023-08-04 10:04:28',
                'setting_formula_unit' => 'kg',
            ),
            88 => 
            array (
                'setting_formula_id' => 138,
                'setting_formula_name' => '{"en":"AZATIN","cn":"AZATIN"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 9,
                'setting_formula_created' => '2023-08-04 10:04:28',
                'setting_formula_updated' => '2023-08-04 10:04:28',
                'setting_formula_unit' => 'kg',
            ),
            89 => 
            array (
                'setting_formula_id' => 139,
                'setting_formula_name' => '{"en":"COMPO EXPERT BASAPLANT 19\\/19\\/19","cn":"COMPO EXPERT BASAPLANT 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 10,
                'setting_formula_created' => '2023-08-04 10:04:37',
                'setting_formula_updated' => '2023-08-04 10:04:37',
                'setting_formula_unit' => 'kg',
            ),
            90 => 
            array (
                'setting_formula_id' => 140,
                'setting_formula_name' => '{"en":"COMPO EXPERT BASAPLANT 19\\/19\\/19","cn":"COMPO EXPERT BASAPLANT 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 8,
                'setting_formula_created' => '2023-08-04 10:04:37',
                'setting_formula_updated' => '2023-08-04 10:04:37',
                'setting_formula_unit' => 'kg',
            ),
            91 => 
            array (
                'setting_formula_id' => 141,
                'setting_formula_name' => '{"en":"COMPO EXPERT BASAPLANT 19\\/19\\/19","cn":"COMPO EXPERT BASAPLANT 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 5,
                'setting_formula_created' => '2023-08-04 10:04:37',
                'setting_formula_updated' => '2023-08-04 10:04:37',
                'setting_formula_unit' => 'kg',
            ),
            92 => 
            array (
                'setting_formula_id' => 142,
                'setting_formula_name' => '{"en":"COMPO EXPERT BASAPLANT 19\\/19\\/19","cn":"COMPO EXPERT BASAPLANT 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 6,
                'setting_formula_created' => '2023-08-04 10:04:37',
                'setting_formula_updated' => '2023-08-04 10:04:37',
                'setting_formula_unit' => 'kg',
            ),
            93 => 
            array (
                'setting_formula_id' => 143,
                'setting_formula_name' => '{"en":"COMPO EXPERT BASAPLANT 19\\/19\\/19","cn":"COMPO EXPERT BASAPLANT 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 7,
                'setting_formula_created' => '2023-08-04 10:04:37',
                'setting_formula_updated' => '2023-08-04 10:04:37',
                'setting_formula_unit' => 'kg',
            ),
            94 => 
            array (
                'setting_formula_id' => 144,
                'setting_formula_name' => '{"en":"COMPO EXPERT BASAPLANT 19\\/19\\/19","cn":"COMPO EXPERT BASAPLANT 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 4,
                'setting_formula_created' => '2023-08-04 10:04:37',
                'setting_formula_updated' => '2023-08-04 10:04:37',
                'setting_formula_unit' => 'kg',
            ),
            95 => 
            array (
                'setting_formula_id' => 145,
                'setting_formula_name' => '{"en":"COMPO EXPERT BASAPLANT 19\\/19\\/19","cn":"COMPO EXPERT BASAPLANT 19\\/19\\/19"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 9,
                'setting_formula_created' => '2023-08-04 10:04:37',
                'setting_formula_updated' => '2023-08-04 10:04:37',
                'setting_formula_unit' => 'kg',
            ),
            96 => 
            array (
                'setting_formula_id' => 146,
                'setting_formula_name' => '{"en":"ANTRACOL 70WP","cn":"ANTRACOL 70WP"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 10,
                'setting_formula_created' => '2023-08-04 10:05:07',
                'setting_formula_updated' => '2023-08-04 10:05:07',
                'setting_formula_unit' => 'kg',
            ),
            97 => 
            array (
                'setting_formula_id' => 147,
                'setting_formula_name' => '{"en":"ANTRACOL 70WP","cn":"ANTRACOL 70WP"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 8,
                'setting_formula_created' => '2023-08-04 10:05:07',
                'setting_formula_updated' => '2023-08-04 10:05:07',
                'setting_formula_unit' => 'kg',
            ),
            98 => 
            array (
                'setting_formula_id' => 148,
                'setting_formula_name' => '{"en":"ANTRACOL 70WP","cn":"ANTRACOL 70WP"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 5,
                'setting_formula_created' => '2023-08-04 10:05:07',
                'setting_formula_updated' => '2023-08-04 10:05:07',
                'setting_formula_unit' => 'kg',
            ),
            99 => 
            array (
                'setting_formula_id' => 149,
                'setting_formula_name' => '{"en":"ANTRACOL 70WP","cn":"ANTRACOL 70WP"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 6,
                'setting_formula_created' => '2023-08-04 10:05:07',
                'setting_formula_updated' => '2023-08-04 10:05:07',
                'setting_formula_unit' => 'kg',
            ),
            100 => 
            array (
                'setting_formula_id' => 150,
                'setting_formula_name' => '{"en":"ANTRACOL 70WP","cn":"ANTRACOL 70WP"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 7,
                'setting_formula_created' => '2023-08-04 10:05:07',
                'setting_formula_updated' => '2023-08-04 10:05:07',
                'setting_formula_unit' => 'kg',
            ),
            101 => 
            array (
                'setting_formula_id' => 151,
                'setting_formula_name' => '{"en":"ANTRACOL 70WP","cn":"ANTRACOL 70WP"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 4,
                'setting_formula_created' => '2023-08-04 10:05:07',
                'setting_formula_updated' => '2023-08-04 10:05:07',
                'setting_formula_unit' => 'kg',
            ),
            102 => 
            array (
                'setting_formula_id' => 152,
                'setting_formula_name' => '{"en":"ANTRACOL 70WP","cn":"ANTRACOL 70WP"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 9,
                'setting_formula_created' => '2023-08-04 10:05:07',
                'setting_formula_updated' => '2023-08-04 10:05:07',
                'setting_formula_unit' => 'kg',
            ),
            103 => 
            array (
                'setting_formula_id' => 153,
                'setting_formula_name' => '{"en":"16\\/16\\/16","cn":"16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 10,
                'setting_formula_created' => '2023-08-04 10:05:14',
                'setting_formula_updated' => '2023-08-04 10:05:14',
                'setting_formula_unit' => 'kg',
            ),
            104 => 
            array (
                'setting_formula_id' => 154,
                'setting_formula_name' => '{"en":"16\\/16\\/16","cn":"16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 8,
                'setting_formula_created' => '2023-08-04 10:05:14',
                'setting_formula_updated' => '2023-08-04 10:05:14',
                'setting_formula_unit' => 'kg',
            ),
            105 => 
            array (
                'setting_formula_id' => 155,
                'setting_formula_name' => '{"en":"16\\/16\\/16","cn":"16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 5,
                'setting_formula_created' => '2023-08-04 10:05:14',
                'setting_formula_updated' => '2023-08-04 10:05:14',
                'setting_formula_unit' => 'kg',
            ),
            106 => 
            array (
                'setting_formula_id' => 156,
                'setting_formula_name' => '{"en":"16\\/16\\/16","cn":"16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 6,
                'setting_formula_created' => '2023-08-04 10:05:14',
                'setting_formula_updated' => '2023-08-04 10:05:14',
                'setting_formula_unit' => 'kg',
            ),
            107 => 
            array (
                'setting_formula_id' => 157,
                'setting_formula_name' => '{"en":"16\\/16\\/16","cn":"16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 7,
                'setting_formula_created' => '2023-08-04 10:05:14',
                'setting_formula_updated' => '2023-08-04 10:05:14',
                'setting_formula_unit' => 'kg',
            ),
            108 => 
            array (
                'setting_formula_id' => 158,
                'setting_formula_name' => '{"en":"16\\/16\\/16","cn":"16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 4,
                'setting_formula_created' => '2023-08-04 10:05:14',
                'setting_formula_updated' => '2023-08-04 10:05:14',
                'setting_formula_unit' => 'kg',
            ),
            109 => 
            array (
                'setting_formula_id' => 159,
                'setting_formula_name' => '{"en":"16\\/16\\/16","cn":"16\\/16\\/16"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 9,
                'setting_formula_created' => '2023-08-04 10:05:14',
                'setting_formula_updated' => '2023-08-04 10:05:14',
                'setting_formula_unit' => 'kg',
            ),
            110 => 
            array (
                'setting_formula_id' => 160,
                'setting_formula_name' => '{"en":"C-THRIPS","cn":"C-THRIPS"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 10,
                'setting_formula_created' => '2023-08-04 10:05:21',
                'setting_formula_updated' => '2023-08-04 10:05:21',
                'setting_formula_unit' => 'kg',
            ),
            111 => 
            array (
                'setting_formula_id' => 161,
                'setting_formula_name' => '{"en":"C-THRIPS","cn":"C-THRIPS"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 8,
                'setting_formula_created' => '2023-08-04 10:05:21',
                'setting_formula_updated' => '2023-08-04 10:05:21',
                'setting_formula_unit' => 'kg',
            ),
            112 => 
            array (
                'setting_formula_id' => 162,
                'setting_formula_name' => '{"en":"C-THRIPS","cn":"C-THRIPS"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 5,
                'setting_formula_created' => '2023-08-04 10:05:21',
                'setting_formula_updated' => '2023-08-04 10:05:21',
                'setting_formula_unit' => 'kg',
            ),
            113 => 
            array (
                'setting_formula_id' => 163,
                'setting_formula_name' => '{"en":"C-THRIPS","cn":"C-THRIPS"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 6,
                'setting_formula_created' => '2023-08-04 10:05:21',
                'setting_formula_updated' => '2023-08-04 10:05:21',
                'setting_formula_unit' => 'kg',
            ),
            114 => 
            array (
                'setting_formula_id' => 164,
                'setting_formula_name' => '{"en":"C-THRIPS","cn":"C-THRIPS"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 7,
                'setting_formula_created' => '2023-08-04 10:05:21',
                'setting_formula_updated' => '2023-08-04 10:05:21',
                'setting_formula_unit' => 'kg',
            ),
            115 => 
            array (
                'setting_formula_id' => 165,
                'setting_formula_name' => '{"en":"C-THRIPS","cn":"C-THRIPS"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 4,
                'setting_formula_created' => '2023-08-04 10:05:21',
                'setting_formula_updated' => '2023-08-04 10:05:21',
                'setting_formula_unit' => 'kg',
            ),
            116 => 
            array (
                'setting_formula_id' => 166,
                'setting_formula_name' => '{"en":"C-THRIPS","cn":"C-THRIPS"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 9,
                'setting_formula_created' => '2023-08-04 10:05:21',
                'setting_formula_updated' => '2023-08-04 10:05:21',
                'setting_formula_unit' => 'kg',
            ),
            117 => 
            array (
                'setting_formula_id' => 167,
                'setting_formula_name' => '{"en":"WETCIT","cn":"WETCIT"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 10,
                'setting_formula_created' => '2023-08-04 10:05:28',
                'setting_formula_updated' => '2023-08-04 10:05:28',
                'setting_formula_unit' => 'kg',
            ),
            118 => 
            array (
                'setting_formula_id' => 168,
                'setting_formula_name' => '{"en":"WETCIT","cn":"WETCIT"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 8,
                'setting_formula_created' => '2023-08-04 10:05:28',
                'setting_formula_updated' => '2023-08-04 10:05:28',
                'setting_formula_unit' => 'kg',
            ),
            119 => 
            array (
                'setting_formula_id' => 169,
                'setting_formula_name' => '{"en":"WETCIT","cn":"WETCIT"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 5,
                'setting_formula_created' => '2023-08-04 10:05:28',
                'setting_formula_updated' => '2023-08-04 10:05:28',
                'setting_formula_unit' => 'kg',
            ),
            120 => 
            array (
                'setting_formula_id' => 170,
                'setting_formula_name' => '{"en":"WETCIT","cn":"WETCIT"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 6,
                'setting_formula_created' => '2023-08-04 10:05:28',
                'setting_formula_updated' => '2023-08-04 10:05:28',
                'setting_formula_unit' => 'kg',
            ),
            121 => 
            array (
                'setting_formula_id' => 171,
                'setting_formula_name' => '{"en":"WETCIT","cn":"WETCIT"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 7,
                'setting_formula_created' => '2023-08-04 10:05:28',
                'setting_formula_updated' => '2023-08-04 10:05:28',
                'setting_formula_unit' => 'kg',
            ),
            122 => 
            array (
                'setting_formula_id' => 172,
                'setting_formula_name' => '{"en":"WETCIT","cn":"WETCIT"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 4,
                'setting_formula_created' => '2023-08-04 10:05:28',
                'setting_formula_updated' => '2023-08-04 10:05:28',
                'setting_formula_unit' => 'kg',
            ),
            123 => 
            array (
                'setting_formula_id' => 173,
                'setting_formula_name' => '{"en":"WETCIT","cn":"WETCIT"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 9,
                'setting_formula_created' => '2023-08-04 10:05:28',
                'setting_formula_updated' => '2023-08-04 10:05:28',
                'setting_formula_unit' => 'kg',
            ),
            124 => 
            array (
                'setting_formula_id' => 174,
                'setting_formula_name' => '{"en":"BDC Set 1","cn":"BDC Set 1"}',
                'setting_formula_category_id' => 1,
                'setting_formula_status' => 'active',
                'setting_formula_measurement' => 'pack',
                'company_id' => 10,
                'setting_formula_created' => '2023-08-04 11:41:32',
                'setting_formula_updated' => '2023-08-04 11:43:44',
                'setting_formula_unit' => 'kg',
            ),
        ));
        
        
    }
}