<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TblUserTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_user')->delete();
        
        \DB::table('tbl_user')->insert(array (
            0 => 
            array (
                'user_id' => 1,
                'user_email' => 'support@webby.com.my',
                'password' => '$2y$10$dlcZSj4xDoB98KwvCkgegOnAjeuBb5FcEoCbAfbKsWxyTOkCutpte',
                'user_fullname' => 'Webby',
                'user_profile_photo' => NULL,
                'user_nric' => NULL,
                'user_nationality' => 'Malaysian',
                'user_gender' => 'male',
                'user_address' => NULL,
                'user_address2' => NULL,
                'user_city' => NULL,
                'user_state' => NULL,
                'user_postcode' => NULL,
                'user_dob' => NULL,
                'user_status' => 'active',
                'user_logindate' => NULL,
                'user_cdate' => '0008-08-23 08:08:11',
                'user_udate' => '0008-08-23 08:08:11',
                'user_ip' => NULL,
                'is_deleted' => 0,
                'user_mobile' => '60133212943',
                'user_join_date' => '2008-08-23',
                'user_remember_token' => NULL,
                'user_admin_skin' => NULL,
                'email_verified_at' => NULL,
                'user_type_id' => 1,
                'user_language' => 'en',
                'company_id' => 0,
                'user_unique_code' => 'dwa3',
                'user_token' => NULL,
                'user_wallet_amount' => NULL,
            ),
            1 => 
            array (
                'user_id' => 2,
                'user_email' => 'farmmanager@webby.com.my',
                'password' => '$2y$10$dlcZSj4xDoB98KwvCkgegOnAjeuBb5FcEoCbAfbKsWxyTOkCutpte',
                'user_fullname' => 'Farm Manager',
                'user_profile_photo' => NULL,
                'user_nric' => NULL,
                'user_nationality' => 'Malaysian',
                'user_gender' => 'male',
                'user_address' => NULL,
                'user_address2' => NULL,
                'user_city' => NULL,
                'user_state' => NULL,
                'user_postcode' => NULL,
                'user_dob' => NULL,
                'user_status' => 'active',
                'user_logindate' => NULL,
                'user_cdate' => '0008-08-23 08:08:11',
                'user_udate' => '0008-08-23 08:08:11',
                'user_ip' => NULL,
                'is_deleted' => 0,
                'user_mobile' => '60192828321',
                'user_join_date' => '2008-08-23',
                'user_remember_token' => NULL,
                'user_admin_skin' => NULL,
                'email_verified_at' => NULL,
                'user_type_id' => 1,
                'user_language' => 'en',
                'company_id' => 1,
                'user_unique_code' => 'ksa7',
                'user_token' => NULL,
                'user_wallet_amount' => NULL,
            ),
            2 => 
            array (
                'user_id' => 3,
                'user_email' => 'admin@huaxin.global',
                'password' => '$2y$10$XUX1i5oW7IRBcY4TfI4qI.z817CNjWNjsk69Mi.kGptpWg2wxp4Ia',
                'user_fullname' => 'Huaxin Berhad',
                'user_profile_photo' => '',
                'user_nric' => NULL,
                'user_nationality' => 'Malaysian',
                'user_gender' => 'male',
                'user_address' => '',
                'user_address2' => '',
                'user_city' => '',
                'user_state' => '',
                'user_postcode' => '',
                'user_dob' => NULL,
                'user_status' => 'active',
                'user_logindate' => '2022-10-23 17:46:47',
                'user_cdate' => '2022-10-23 17:46:47',
                'user_udate' => '2022-10-23 17:46:47',
                'user_ip' => '',
                'is_deleted' => 0,
                'user_mobile' => '60139874921',
                'user_join_date' => '2022-10-23',
                'user_remember_token' => 'pJnwaHK6RKu1GYqNzLB1ACFTRu7ElY21HaFtr95JgIpP1Qbw4F29GOvGZ0Ll',
                'user_admin_skin' => NULL,
                'email_verified_at' => NULL,
                'user_type_id' => 1,
                'user_language' => 'en',
                'company_id' => 1,
                'user_unique_code' => 'HB',
                'user_token' => NULL,
                'user_wallet_amount' => NULL,
            ),
            3 => 
            array (
                'user_id' => 4,
                'user_email' => 'dorees419@gmail.com',
                'password' => '$2y$10$XBo44B4SS01Tqku4tuxfw.4K6bmZDVCEQYzJMmVuQnxuyQR1KftYi',
                'user_fullname' => 'Acid Yong',
                'user_profile_photo' => '',
                'user_nric' => NULL,
                'user_nationality' => 'Malaysia',
                'user_gender' => 'female',
                'user_address' => '',
                'user_address2' => '',
                'user_city' => '',
                'user_state' => '',
                'user_postcode' => '',
                'user_dob' => '2022-03-01',
                'user_status' => 'active',
                'user_logindate' => '2022-12-19 06:46:34',
                'user_cdate' => '2022-12-19 06:46:34',
                'user_udate' => '2022-12-19 06:46:34',
                'user_ip' => '',
                'is_deleted' => 0,
                'user_mobile' => '60149449868',
                'user_join_date' => '2022-12-19',
                'user_remember_token' => 'dvHBHOXXpG6j1tCSZpTs5bhYU930XRm6mjo9gsK6OO2ijLx7kfJNh2tV90mZ',
                'user_admin_skin' => NULL,
                'email_verified_at' => NULL,
                'user_type_id' => 2,
                'user_language' => 'en',
                'company_id' => 5,
                'user_unique_code' => 'ACID',
                'user_token' => NULL,
                'user_wallet_amount' => NULL,
            ),
            4 => 
            array (
                'user_id' => 5,
                'user_email' => 'ziwei@gmail.com',
                'password' => '$2y$10$.b6YsKTQ9Mfrs.cVuxy5XOfgk5M1ZyyCsISJSywJ/y.Z/EGDBgU/u',
                'user_fullname' => 'Zi Wei',
                'user_profile_photo' => '',
                'user_nric' => NULL,
                'user_nationality' => 'Malaysian',
                'user_gender' => 'female',
                'user_address' => '',
                'user_address2' => '',
                'user_city' => '',
                'user_state' => '',
                'user_postcode' => '',
                'user_dob' => '2022-03-01',
                'user_status' => 'active',
                'user_logindate' => '2022-10-28 10:29:50',
                'user_cdate' => '2022-10-28 10:29:50',
                'user_udate' => '2023-08-08 16:20:30',
                'user_ip' => '',
                'is_deleted' => 0,
                'user_mobile' => '60104601175',
                'user_join_date' => '2022-10-28',
                'user_remember_token' => NULL,
                'user_admin_skin' => NULL,
                'email_verified_at' => NULL,
                'user_type_id' => 2,
                'user_language' => 'en',
                'company_id' => 1,
                'user_unique_code' => 'ZW',
                'user_token' => '2376|wR69X6IeDa8aPrCSKmNN8lb6lCi72BJKJM7WKD7j',
                'user_wallet_amount' => NULL,
            ),
            5 => 
            array (
                'user_id' => 6,
                'user_email' => 'hejaya319@gmail.com',
                'password' => '$2y$10$uVDacqY5.pd5OojFk3laXuSqheLc1DUf1CKVMVlq89ytRT9/n/Biu',
                'user_fullname' => 'Hee Yu Hock',
                'user_profile_photo' => NULL,
                'user_nric' => NULL,
                'user_nationality' => 'Malaysia',
                'user_gender' => 'male',
                'user_address' => NULL,
                'user_address2' => NULL,
                'user_city' => NULL,
                'user_state' => NULL,
                'user_postcode' => NULL,
                'user_dob' => '2022-03-01',
                'user_status' => 'active',
                'user_logindate' => NULL,
                'user_cdate' => '2022-03-07 18:01:59',
                'user_udate' => '2022-03-07 18:01:59',
                'user_ip' => NULL,
                'is_deleted' => 0,
                'user_mobile' => '60197854666',
                'user_join_date' => '2022-03-07',
                'user_remember_token' => 'ov73bl5UVGGBgMY8GggBEqHYd10d72gzUVE48LM0nI5lVGCdOoAu1leR2psi',
                'user_admin_skin' => NULL,
                'email_verified_at' => NULL,
                'user_type_id' => 2,
                'user_language' => 'en',
                'company_id' => 7,
                'user_unique_code' => 'HYH',
                'user_token' => NULL,
                'user_wallet_amount' => NULL,
            ),
            6 => 
            array (
                'user_id' => 7,
                'user_email' => 'ctfruitchain@gmail.com',
                'password' => '$2y$10$E.Lo.la/KSkQkV4Bc5547O1sGpFIhc83/jhlMsOPtICtfwo/8wC9a',
                'user_fullname' => 'Calvin Teoh',
                'user_profile_photo' => NULL,
                'user_nric' => NULL,
                'user_nationality' => 'Malaysia',
                'user_gender' => 'male',
                'user_address' => NULL,
                'user_address2' => NULL,
                'user_city' => NULL,
                'user_state' => NULL,
                'user_postcode' => NULL,
                'user_dob' => '2022-03-01',
                'user_status' => 'active',
                'user_logindate' => NULL,
                'user_cdate' => '2022-03-07 18:04:23',
                'user_udate' => '2022-03-07 18:04:23',
                'user_ip' => NULL,
                'is_deleted' => 0,
                'user_mobile' => '60127029132',
                'user_join_date' => '2022-03-07',
                'user_remember_token' => 'BgjvRRmrLOSy5CgiBi26TqykbfiuQLpl0FOt6c53ZlIZA8k6grnw4Gy3Ls38',
                'user_admin_skin' => NULL,
                'email_verified_at' => NULL,
                'user_type_id' => 2,
                'user_language' => 'en',
                'company_id' => 8,
                'user_unique_code' => 'CT',
                'user_token' => NULL,
                'user_wallet_amount' => NULL,
            ),
            7 => 
            array (
                'user_id' => 8,
                'user_email' => 'Patric.lcy@gmail.com',
                'password' => '$2y$10$ma3uiEl1aoIsUYZRz/UV1ONQA5hvZOoJyvyFXjBpuV62pnrVYuA.S',
                'user_fullname' => 'Looi Chee Yang',
                'user_profile_photo' => NULL,
                'user_nric' => NULL,
                'user_nationality' => 'Malaysia',
                'user_gender' => 'male',
                'user_address' => NULL,
                'user_address2' => NULL,
                'user_city' => NULL,
                'user_state' => NULL,
                'user_postcode' => NULL,
                'user_dob' => '2022-03-01',
                'user_status' => 'active',
                'user_logindate' => NULL,
                'user_cdate' => '2022-03-07 18:08:43',
                'user_udate' => '2022-03-07 18:08:43',
                'user_ip' => NULL,
                'is_deleted' => 0,
                'user_mobile' => '60128942008',
                'user_join_date' => '2022-03-07',
                'user_remember_token' => 'HlsFohZJwc3r0XSLZABmwShtSrS8gXblWmdgDpuDhdTLDHN9LEOK7OxpvsOu',
                'user_admin_skin' => NULL,
                'email_verified_at' => NULL,
                'user_type_id' => 2,
                'user_language' => 'en',
                'company_id' => 2,
                'user_unique_code' => 'LCY',
                'user_token' => NULL,
                'user_wallet_amount' => NULL,
            ),
            8 => 
            array (
                'user_id' => 9,
                'user_email' => 'iqbal@webby.com.my',
                'password' => '$2y$10$Ls.Hzoyj2OWhaHG8QPLF6.xpxQoWFOJ9sNBV2OIRS/VWQObcASG.K',
                'user_fullname' => 'Iqbal Sadiq',
                'user_profile_photo' => '',
                'user_nric' => NULL,
                'user_nationality' => 'Malaysian',
                'user_gender' => 'male',
                'user_address' => '3-1, Jalan Merbah 1,',
                'user_address2' => 'Bandar Puchong Jaya',
                'user_city' => 'Puchong',
                'user_state' => 'Selangor',
                'user_postcode' => '47170',
                'user_dob' => '1998-11-20',
                'user_status' => 'active',
                'user_logindate' => '2022-04-25 12:00:09',
                'user_cdate' => '2022-04-25 12:00:09',
                'user_udate' => '2022-04-25 12:00:09',
                'user_ip' => '',
                'is_deleted' => 0,
                'user_mobile' => '60136163626',
                'user_join_date' => '2022-04-25',
                'user_remember_token' => NULL,
                'user_admin_skin' => NULL,
                'email_verified_at' => NULL,
                'user_type_id' => 2,
                'user_language' => 'en',
                'company_id' => 1,
                'user_unique_code' => 'BL20',
                'user_token' => '1092|lA2TpjJzQ1iL5ZUCtj1EsDNtGrL9Co5gKpyqQv2N',
                'user_wallet_amount' => NULL,
            ),
            9 => 
            array (
                'user_id' => 10,
                'user_email' => 'JoannaYap@huaxin.global',
                'password' => '$2y$10$pCiY/41vH6mg70gUEEDaLOkudfnQWIlNJpSDz7cQkvj9rfavrBI1O',
                'user_fullname' => 'Joanna Yap',
                'user_profile_photo' => '',
                'user_nric' => NULL,
                'user_nationality' => 'Malaysian',
                'user_gender' => 'female',
                'user_address' => '3-1, JALAN MERBAH 1',
                'user_address2' => 'Jalan Putra Prima Utama, Taman Putra Prima',
                'user_city' => 'PUCHONG',
                'user_state' => 'SELANGOR',
                'user_postcode' => '47130',
                'user_dob' => NULL,
                'user_status' => 'active',
                'user_logindate' => '2022-06-23 19:06:13',
                'user_cdate' => '2022-06-23 19:06:13',
                'user_udate' => '2023-08-08 19:29:52',
                'user_ip' => '',
                'is_deleted' => 0,
                'user_mobile' => '60137327016',
                'user_join_date' => '2022-06-23',
                'user_remember_token' => NULL,
                'user_admin_skin' => NULL,
                'email_verified_at' => NULL,
                'user_type_id' => 2,
                'user_language' => 'en',
                'company_id' => 4,
                'user_unique_code' => 'JYAP',
                'user_token' => '2382|j7bKtGwX2C6JeBYzgVCnrav5mJV2jUyzhEBXug2l',
                'user_wallet_amount' => NULL,
            ),
        ));
        
        
    }
}